### ISSUE TITLE
Add structured version info to all build artifacts

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1023]
Make each build artifact (usually: container image) aware of its own 'version string'. Examples:

- controller
- UI app image

Then, make it so that there is an easy way to retrieve this version information.

UI: show the UI app image version info

CLI: show everything, also see https://github.com/opstrace/opstrace/issues/454

In a fresh setup, all versions will be equal.

During an upgrade, versions may differ.

Maybe _after_ an upgrade, versions may differ.

**Comment by jgehrcke** [comment]
This is the foundation for https://github.com/opstrace/opstrace/issues/1024.

**Comment by MoSattler** [comment]
@jgehrcke where is the relevant version currently defined in the build steps. Is it this?
https://github.com/opstrace/opstrace/blob/03f91eb8a57ef9b10f152d87a070df97a64d2b30/.buildkite/pipeline.yml#L3

Thinking about app specifically, I was wondering if it would be enough to pass this as a build var to the `app` docker container, to have it persisted during build time. What do you think?

**Comment by jgehrcke** [comment]
> I was wondering if it would be enough to pass CHECKOUT_VERSION_STRING as a build arg to the docker images, to apply the value during image build time.

Injecting CHECKOUT_VERSION_STRING via env would already be a great start, but I think maybe it's better to have a _static_ and _structured_ thing baked into artifacts, something like a `buildinfo.json`, containing more pieces of information than just CHECKOUT_VERSION_STRING.

The complete build info that we encode as of today in the CLI build artifact (which is not a container image) can be seen here:
https://github.com/opstrace/opstrace/blob/717d5b940dcc95740d51f215aaa90dd6c8eac030/Makefile#L337

So, there's the branch name, the time, ...

I am thinking that we should improve upon that approach.

Thoughts:
* Generate `buildinfo.json` once, and then use it for building artifacts
* For container images, `COPY` it into the image as pretty much the last step (to make most of Docker image layer cache)
* For the pkg-based CLI build, find a way to inject this as a static file

If you'd like to, I can work on that, so that after all there is a `buildinfo.json` in the UI/app container image placed at a well-known path -- you could take it from there, towards https://github.com/opstrace/opstrace/issues/1024.

**Comment by MoSattler** [comment]
@jgehrcke sounds good!

**Comment by MoSattler** [comment]
@jgehrcke do you know in how far #1047 addresses part of this?

**Comment by jgehrcke** [comment]
@MoSattler now all Docker container images we build have a `/buildinfo.json` artifact at the root of the file system that you can read, and expose version information from. 

https://github.com/opstrace/opstrace/blob/2d8adb6fe1228f8f06df9d4e11e7461879f76bac/packages/app/Dockerfile.app#L65
