### ISSUE TITLE
investigate per-tenant retention limits in Cortex and Loki

### ISSUE THREAD

**Issue by triclambert** [opstrace/opstrace#1027]
Is it possible to set retention limits on a per-tenant basis?  If not, what would be required?

**Comment by jgehrcke** [comment]
Not just per-tenant, but even per-stream: 

> Retention through the Compactor is experimental. The Compactor retention will become the default and have long term support. It supports more granular retention policies on per tenant and per stream use cases.

https://grafana.com/docs/loki/latest/operations/storage/retention/

**Comment by nickbp** [comment]
FWIW the current global retention value would act as a cap, since it's applied to the S3/GCS buckets themselves. Increasing the cap would involve updating the retention setting in the buckets.
