### ISSUE TITLE
ci: upgrade tests: collect looker artifacts

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1033]
This part is missing in https://github.com/opstrace/opstrace/blob/36c26899948d2bad1e46376c3d5b8c515743e470/ci/test-upgrade/run.sh:
```
    # make sure that looker-related artifacts are collected, but don't fail
    # when these files do not exist (rely on +e before)
    cat /build/looker*report.json
    cp looker*log /build/bk-artifacts
    cp /build/looker*report.json /build/bk-artifacts
```

Maybe add this to the target `make ci-testupgrade-create-cluster-artifacts`.

**Comment by jgehrcke** [comment]
Got failures during looker tests in an upgrade test run here: https://buildkite.com/opstrace/upgrade-tests/builds/972#94732ccb-7ce1-4247-abe7-46170eeb484a/3570-8148 -- but cannot debug because looker's output is missing.

**Comment by sreis** [comment]
> Got failures during looker tests in an upgrade test run here: https://buildkite.com/opstrace/upgrade-tests/builds/972#94732ccb-7ce1-4247-abe7-46170eeb484a/3570-8148 -- but cannot debug because looker's output is missing.

#861 introduced a new env var, OPSTRACE_INSTANCE_DNS_NAME. Fixed with commit https://github.com/opstrace/opstrace/commit/9dab16018ed89e72ac15845707538074983c7617.
