### ISSUE TITLE
old favicon.ico shown in app

### ISSUE THREAD

**Issue by triclambert** [opstrace/opstrace#104]
In a cluster off the latest build, I see the following:

![image](https://user-images.githubusercontent.com/19239758/101246886-d634a480-36ca-11eb-9856-900f51322132.png)

Although I'm not sure why:

```
$ ./opstrace --version --log-level debug
72923d74-ci
2020-12-05T15:28:20.341Z debug: BUILD_INFO_COMMIT: 72923d7
2020-12-05T15:28:20.341Z debug: BUILD_INFO_TIME_RFC3339: 2020-12-05 12:13:25+00:00
2020-12-05T15:28:20.341Z debug: BUILD_INFO_HOSTNAME: ea43460ee841
2020-12-05T15:28:20.342Z debug: BUILD_INFO_BRANCH_NAME: main
2020-12-05T15:28:20.342Z debug: shut down logger, then exit with code 0
```

https://github.com/opstrace/opstrace/tree/72923d7489915907626ac5881eaf56da0080685c/packages/app/public

**Comment by MatApple** [comment]
Can you close all tabs that have the Opstrace UI open, then reopen this URL that has the outdated favicon and clear the browser cache. 

Dev tools > application > clear data.

**Comment by triclambert** [comment]
Tried that.  I still see it on all devices and all networks I have access to.  

I'm going to close this, and let someone reopen it if they can repro.

**Comment by triclambert** [comment]
Reopening to allow others to explicitly allow others to attempt a repro.

**Comment by MatApple** [comment]
I can confirm that I also have this issue, although not sure why yet. Reassigning to @juliachvyrova!

**Comment by jgehrcke** [comment]
It's in the cluster, it's served under `/favicon.ico`
```
curl -k https://bk-3285-2fc-g.opstrace.io/favicon.ico -o favicon.ico && display favicon.ico
```
result:
![Screenshot from 2020-12-15 13-43-34](https://user-images.githubusercontent.com/265630/102216565-a0b66500-3edb-11eb-915c-52f57f21c62b.png)

**Comment by jgehrcke** [comment]
I have always used https://realfavicongenerator.net/ in the past -- great software, great flexibility, correctness -- modern.

![Screenshot from 2020-12-15 13-51-52](https://user-images.githubusercontent.com/265630/102217803-68b02180-3edd-11eb-91c3-2206219f5d35.png)

... and after all:

![Screenshot from 2020-12-15 13-56-19](https://user-images.githubusercontent.com/265630/102217843-706fc600-3edd-11eb-8af5-bc8d6e9ab427.png)

**Comment by jgehrcke** [comment]
Going to push a commit to https://github.com/opstrace/opstrace/pull/171 with the amended favicon.ico.

**Comment by jgehrcke** [comment]
should be fixed with https://github.com/opstrace/opstrace/pull/171 -- closing, but let's double-check :).

**Comment by jgehrcke** [comment]
> It's this, I suppose: https://github.com/opstrace/opstrace/blob/f610692c86d0da1d16165c89c22d814594940523/packages/app/public/favicon.ico

I should have clicked `View raw` in this view -- it would have shown the oktopus, and _not_ the old logo. So, that hypothesis was wrong.

**Comment by jgehrcke** [comment]
Coincidentally, in this PR we have a ci run now that should use app docker images built from scratch: https://github.com/opstrace/opstrace/pull/174

I'll look at the /favicon.ico in those clusters, and update the issue (maybe the app image rebuild helped).

**Comment by jgehrcke** [comment]
```
$ grep -nR 'favicon'
yarn.lock:4005:    serve-favicon "^2.5.0"
yarn.lock:19465:serve-favicon@^2.5.0:
yarn.lock:19467:  resolved "https://registry.yarnpkg.com/serve-favicon/-/serve-favicon-2.5.0.tgz#935d240cdfe0f5805307fdfe967d88942a2cbcf0"
packages/app/public/manifest.json:7:      "src": "favicon.ico",
packages/app/public/index.html:5:    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
packages/app/config/webpackDevServer.config.js:64:    // <link rel="icon" href="%PUBLIC_URL%/favicon.ico">
packages/app/config/webpackDevServer.config.js:67:    // for files like `favicon.ico`, `manifest.json`, and libraries that are
packages/app/config/webpack.config.js:579:      // <link rel="icon" href="%PUBLIC_URL%/favicon.ico">
```

**Comment by jgehrcke** [comment]
> Coincidentally, in this PR we have a ci run now that should use app docker images built from scratch: #174
> I'll look at the /favicon.ico in those clusters, and update the issue (maybe the app image rebuild helped).

Yei! That was it: 

![Screenshot from 2020-12-15 15-55-54](https://user-images.githubusercontent.com/265630/102231270-14616d80-3eee-11eb-82cf-db633a724863.png)

(i.e., the app image rebuild was required an _potentially_ the manual modification of docker-images.json (maybe the automatic update doesn't work).
