### ISSUE TITLE
ui: blank screen after logging in

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#1057]
We're continually seeing a blank screen (entirely white) after logging in. Clearing cookies and/or trying different browser then returning the original browser seems to correct the issue, but then it pops up again a day or so later.

Note: This might also be when going to the website in a new browser tab while still having a valid session - still need to investigate this though.

[Issue #1000 ](https://github.com/opstrace/opstrace/issues/1000) has the same white screen symptom and has been recently resolved with PR #1031. No idea if it is related.

**Comment by jgehrcke** [comment]
Also https://github.com/opstrace/opstrace/issues/1005

**Comment by jgehrcke** [comment]
And it might be that the CI instabilities around browser execution are actually as of this problem / this class of problems.

**Comment by terrcin** [comment]
@jgehrcke yeah I had wondered that too.

I've cleared most of the browser problems by putting in bigger timeouts for when waiting on things to happen in the browser. But there are still some occasional issues. I'm hoping that goving over the auth0 code+flow to track down this problem and trying to resolve why login can be frustratingly slow will help with a few things. Worst case we'll learn that the other problems we've seen are not related to this. :-)

**Comment by jgehrcke** [comment]
We also have a blank screen _before_ logging in sometimes. At https://buildkite.com/opstrace/scheduled-main-builds/builds/2692#94af77ac-516e-4f7c-bb12-aecb5be99dd2/2972-3081 the `uishot-lasterr.png` is all white, upon a timeout waiting for the Login button to appear.
