### ISSUE TITLE
feat: multi-user add

### ISSUE THREAD

**Issue by triclambert** [opstrace/opstrace#1063]
It would be nice to add multiple users at the same time, separated by commas.

**Comment by jgehrcke** [comment]
> separated by commas.

To be a little less solution-centered, I suppose the requirement here is that the following combo should be possible
1) **copy text** from somewhere
2) in Opstrace UI press 'add users'
3) **paste text** into a form field / text area
4) press button

done

Single copy/paste operation seems to be key; whether that's newline-separated or comma-separated or whitespace-separated: :shrug:

**Comment by triclambert** [comment]
That sounds good to me.  Though I would not assume that it is a single copy/paste operation—there may be more than one, depending on the format of the source information.
