### ISSUE TITLE
ui app: review login security

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1078]
https://github.com/opstrace/opstrace/blob/afe3b291e27ad7cef24e11a1812e4b1a73372dda/packages/app/src/client/views/login/index.tsx#L161

**Comment by terrcin** [comment]
@jgehrcke if you could to explain why you think that data is suspicious that would be helpful.

My understanding of the situation is that we've outsourced being responsible for all of this this to Auth0 (ie experts in this field so we don't have to be) and they have decided it's safe to include that data when redirecting the user back to our site.

**Comment by jgehrcke** [comment]
> if you could to explain why you think that data is suspicious that would be helpful.

That is explained in the code comment, pretty exhaustively even. I don't expect everyone to necessarily understand that, but maybe you can ask a question based on what is written in the code comment :).

**Comment by jgehrcke** [comment]
> (ie experts in this field so we don't have to be)

And we absolutely have to understand the basic building blocks, to be able to use them responsibly :).
