### ISSUE TITLE
ci: test-remote: reduce runtime of longest-running tests

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1086]
test-remote takes about 20 minutes as of now:
```
[2021-07-22T08:24:55Z] ++ make test-remote

[2021-07-22T08:44:32Z] ++ echo '--- Exit status of make test-remote: 0'
```

The top N contributors:
```
✓[0m[90m End-to-end alerts for default tenant[0m[31m (190718ms)[0m
✓[0m[90m End-to-end alerts for system tenant[0m[31m (163280ms)[0m

✓[0m[90m dummyseries short write, smoke read[0m[31m (701174ms)[0m
```

@nickbp do you have a smart idea for significantly reducing the runtime of the alerting tests?

`dummyseries short write, smoke read` can easily be shortened, I can do that.

This is not a top contributor, but can easily be shortened:
```
 [32m  ✓[0m[90m long dummystream insert, validate via query[0m[31m (20026ms)[0m
```
I'll also look into that.

**Comment by jgehrcke** [comment]
In `make test-remote-ui` the dominating test is 
```
[32m  ✓[0m[90m create_tenant_and_use_custom_authn_token[0m[31m (166200ms)[0m
```
which waits for the new API endpoints to be DNS-resolvable after adding a tenant. How can we make this more snappy @sreis?

**Comment by sreis** [comment]
> which waits for the new API endpoints to be DNS-resolvable after adding a tenant. (How) can we make this more snappy @sreis?

Maybe use [`waitUntilRoute53EntriesAreAvailable`](https://github.com/opstrace/opstrace/blob/sreis/integrate-cortex-operator/packages/installer/src/aws.ts#L1003:L1003) to help shave off a few minutes there.

**Comment by jgehrcke** [comment]
see on https://buildkite.com/opstrace/prs/builds/5168#832ec800-832b-43db-a40c-2b089497f46a/2980-4943 where I did a little bit of work towards reducing that runtime again:
```
[2021-07-26T14:38:29Z] ++ make test-remote

...

[2021-07-26T14:47:47Z]   23 passing (9m)
[2021-07-26T14:47:47Z]   4 pending
...
[2021-07-26T14:47:47Z] ++ echo '--- Exit status of make test-remote: 0'
```

Cut by 50 %, from 20 to 10 mins.

**Comment by nickbp** [comment]
Started on some time saving improvements here, will see how much of a difference it makes...: https://github.com/opstrace/opstrace/pull/1118

**Comment by jgehrcke** [comment]
Lovely. We're now down to five minutes.
```
[2021-07-27T05:38:16Z] ++ make test-remote
...
[2021-07-27T05:43:23Z] ++ echo '--- Exit status of make test-remote: 0'
```

**Comment by jgehrcke** [comment]
This was a huge success, closing.
