### ISSUE TITLE
Integrations across types with the same integration name hit a uniqueness constraint

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#1090]
Steps to reproduce:
1. Create k8s metrics integration named `nick`. This works fine.
2. Create k8s logs integration named `nick`. When clicking create button for k8s logs integration, nothing happens.
3. Check browser console and see constraint violation:
> Uncaught (in promise) Error: Uniqueness violation. duplicate key value violates unique constraint "integrations_name_tenant_id_key": {"response":{"errors":[{"extensions":{"path":"$.selectionSet.insert_integration_one.args.object","code":"constraint-violation"},"message":"Uniqueness violation. duplicate key value violates unique constraint \"integrations_name_tenant_id_key\""}],"status":200,"headers":{"map":{"access-control-allow-credentials":"true","access-control-allow-methods":"GET,POST,PUT,PATCH,DELETE,OPTIONS","access-control-allow-origin":"https://terrcin10.opstrace.io","content-encoding":"gzip","content-type":"application/json; charset=utf-8","date":"Thu, 22 Jul 2021 23:41:55 GMT","strict-transport-security":"max-age=15724800; includeSubDomains","vary":"Accept-Encoding","x-content-type-options":"nosniff","x-dns-prefetch-control":"off","x-download-options":"noopen","x-firefox-spdy":"h2","x-frame-options":"SAMEORIGIN","x-xss-protection":"1; mode=block"}}},"request":{"query":"mutation InsertIntegration($name: String!, $kind: String!, $data: jsonb!, $tenant_id: uuid!) {\n  insert_integration_one(object: {name: $name, kind: $kind, data: $data, tenant_id: $tenant_id}) {\n    id\n    kind\n    name\n    key\n    data\n    tenant_id\n    created_at\n    updated_at\n  }\n}\n","variables":{"name":"nick","kind":"k8s-logs","data":{"deployNamespace":"opstrace"},"tenant_id":"1a473fd6-d17d-4c1b-9076-883620d12dde"}}}

Specifically, this is two different integrations across two different integration types, where both have the same name. In this case I was installing both a metrics integration and a logs integration for a single target cluster and was wanting to use the same name for both to reflect that.

**Comment by nickbp** [comment]
(Checked with nahum if this was expected and it sounds like it was at least worth investigating)

**Comment by terrcin** [comment]
had a brief play with this. not 100% straight forward as the `key` field is generated from the `name` field and needs to be unique per tenant. having a think about how to proceed

**Comment by nickbp** [comment]
Another potential issue is that in Grafana, the integration folders are based on the name, as `Integration: <name>`. Might have collisions there if two integrations (with their own predefined grafana dashboards) had the same name?

**Comment by terrcin** [comment]
I've followed up with @MatApple about this, and we're fine with this constraint for the time being. @MoSattler could you please check to make sure we're correctly exposing when this occurs to the user.
