### ISSUE TITLE
Grafana Folder API error

### ISSUE THREAD

**Issue by MoSattler** [opstrace/opstrace#1098]
[Whenever uninstalling an integration, there is a request made to grafana to remove a corresponding folder.](https://github.com/opstrace/opstrace/blob/main/packages/app/src/client/integrations/common/UninstallIntegrationBtn.tsx#L58-L61)
Locally, when developing with the remote setup, this does not work for me. The server returns a 500 with the body:
> { message: “Folder API error” }

@MatApple suggested to assign @terrcin (see [here](https://opstrace-community.slack.com/archives/C01KZS8JRNC/p1627061939183400))

**Comment by MoSattler** [comment]
@MatApple suggested to assign @terrcin (see [here](https://opstrace-community.slack.com/archives/C01KZS8JRNC/p1627061939183400))

**Comment by terrcin** [comment]
closing as potentially resolved by #1128
