### ISSUE TITLE
ERROR: (gcloud.dns.managed-zones.create) Resource in projects [ci-shard-eee] is the subject of a conflict: The resource 'entity.managedZone' named x already exists

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#1129]
Maybe related or due to hitting rebuild on the GCP cluster tests directly (rather that the whole PR) after failing due to `HTTPError 412: Precondition not met for 'entity.change.deletions[0]'` recorded in here: https://github.com/opstrace/opstrace/issues/1068

```
create cluster | 1s
-- | --
  | [2021-07-28T02:01:46Z] + [[ gcp == \a\w\s ]]
  | [2021-07-28T02:01:46Z] + export OPSTRACE_INSTANCE_DNS_NAME=prs-bk-5218-8c4-g.opstracegcp.com
  | [2021-07-28T02:01:46Z] + OPSTRACE_INSTANCE_DNS_NAME=prs-bk-5218-8c4-g.opstracegcp.com
  | [2021-07-28T02:01:46Z] + echo -e '\ncustom_dns_name: prs-bk-5218-8c4-g.opstracegcp.com'
  | [2021-07-28T02:01:46Z] + SUBZONE_NAME=zone-prs-bk-5218-8c4-g
  | [2021-07-28T02:01:46Z] + gcloud dns managed-zones create zone-prs-bk-5218-8c4-g '--description=zone used by CI cluster prs-bk-5218-8c4-g' --dns-name=prs-bk-5218-8c4-g.opstracegcp.com.
  | [2021-07-28T02:01:46Z] ERROR: (gcloud.dns.managed-zones.create) Resource in projects [ci-shard-eee] is the subject of a conflict: The resource 'entity.managedZone' named 'zone-prs-bk-5218-8c4-g' already exists
  | [2021-07-28T02:01:46Z] + teardown
  | [2021-07-28T02:01:46Z] + LAST_EXITCODE_BEFORE_TEARDOWN=1
  | [2021-07-28T02:01:46Z] + echo '+++ Exit status before entering teardown(): 1'
```

https://buildkite.com/opstrace/prs/builds/5218#07372a91-a740-494a-a400-ce77ed6d58dd/382-389

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/prs/builds/5218#4a308834-e500-4491-9dde-af362db62941/353-369

happened again, at this stage gonna assume it's related to rerunning the failed ci task multiple times.

**Comment by jgehrcke** [comment]
>  at this stage gonna assume it's related to rerunning the failed ci task multiple times.

Yes, there are a number of imperfections in CI that don't really allow for proper continuation. The safest best is to generate a fresh instance name, i.e. change the build number, i.e. restart the _entire build_, instead of just an individual step. Of course that depends on the step. The preamble step for example can safely be retried as of today.
