### ISSUE TITLE
ui: remove now unused "withAuthentication" component and related views

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#1135]
Branch containing this work: https://github.com/opstrace/opstrace/tree/terrcin/remove-with-authentication

Once we are satisfied that the replacement to withAuthentication is working as intended, this branch should be turned into a PR and merged. withAuthentication had been left in to make a rollback easy.

**Comment by MatApple** [comment]
done https://github.com/opstrace/opstrace/pull/1234
