### ISSUE TITLE
 CI build healthy but tests failed

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#115]
**Describe the bug**

At least these two AWS CI runs were healthy but the tests failed.

https://buildkite.com/opstrace/scheduled-main-builds/builds/1307#94793a21-0bb4-4677-b286-68198da035b1/3094-5153
https://buildkite.com/opstrace/prs/builds/3165#6357df46-61ad-4aa0-bda7-881c7c8b0b14/2261-4062

**To Reproduce**

Not sure if it's AWS only.

**Expected behavior**

When tests fail the CI run must also fail.

**Comment by jgehrcke** [comment]
Oh sheeet :) Thanks for tackling this :hankey:
