### ISSUE TITLE
Update Kubernetes cluster version

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1169]
## Problem
According to [GKE release schedule](https://cloud.google.com/kubernetes-engine/docs/release-schedule#fn6), version 1.18 (what we currently support) will be unavailable for new clusters sometime this month. There is also the following limitation regarding upgrades in GKE that we need to be aware of:

> You cannot upgrade your cluster more than one minor version at a time. For example, you can upgrade a cluster from version 1.12.x to 1.13.x, but not directly from 1.11.x to 1.13.x.

This means we need to upgrade to at least version 1.19 as soon as possible. This version, 1.19, will be unavailable for new clusters in 2021-10. Which gives us around two months to work on AWS.

Amazon EKS's [end of support](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) for version 1.18 is December 2021. We are not using EKS managed nodes so we need to spend some time researching what is the best path to upgrade the node pool.

## Proposal
In our product, it should be safe to have version skew in EKS and GKE because we don't leverage any special 1.18 features. At most, it might mean we need to bump the API version in some resources we install. This means the EKS cluster version will stay at 1.18 until we figure out an upgrade path for EKS.

The plan is basically:

1) Bump GKE version to 1.19 as soon as possible
2) Figure out an upgrade path for EKS and upgrade to 1.19 later

**Comment by opstracy** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Bump GKE version to 1.19  #1170](https://github.com/opstrace/opstrace/issues/1170) | N/A | sreis | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by jgehrcke** [comment]
Ha. Dependency hell on a new level :) Good stuff

I think I have not understood everything here.. let's maybe be explicit about the challenges imposed by these two different scenarios:

1. initial Opstrace instance creation
2. Opstrace instance upgrade

About (1), could it be that there are no actual challenges? Did I understand correctly that there may be a time window where we use a different k8s version on GKE than on EKS given the same Opstrace release version? And if yes: that's maybe just a cosmetic weirdness, but not an issue, correct?

About (2): do we have code / design at all so far in our current upgrade architecture that takes the EKS/GKE upgrade into account? 

> we need to spend some time researching what is the best path to upgrade the node pool

*if* that involves some kind of downtime anyway, I'd like to spend at least a tiny bit of time to discuss the 'hibernation-based' upgrade here ... I think we have seen in different kinds of contexts that this might be an important concept we have to build anyway (for saving cost, for changing hardware spec etc, also see https://github.com/opstrace/opstrace/issues/1028#issuecomment-879236408)

Some specific ideas:
https://github.com/opstrace/opstrace/issues/326#issuecomment-891833665

**Comment by sreis** [comment]
> I think I have not understood everything here.. let's maybe be explicit about the challenges imposed by these two different scenarios:
> 
> 1. initial Opstrace instance creation
> 2. Opstrace instance upgrade
> 
> About (1), could it be that there are no actual challenges?

The [PR](https://github.com/opstrace/opstrace/pull/1171) I opened to explore GKE upgrade is throwing some errors but it doesn't seem like it'll be blockers for very long.

> Did I understand correctly that there may be a time window where we use a different k8s version on GKE than on EKS given the same Opstrace release version? And if yes: that's maybe just a cosmetic weirdness, but not an issue, correct?
> 

Yes, there will be version skew until we can bump EKS version to 1.19. I don't think it'll be an issue but we'll never know for sure until we run more tests in CI.

> About (2): do we have code / design at all so far in our current upgrade architecture that takes the EKS/GKE upgrade into account?
> 

I've only looked at GKE so far and the code changes are mainly in the [`ensureGKEExists`](https://github.com/opstrace/opstrace/blob/main/packages/installer/src/gcp.ts#L147:L147) function. 

> > we need to spend some time researching what is the best path to upgrade the node pool
> 
> _if_ that involves some kind of downtime anyway, I'd like to spend at least a tiny bit of time to discuss the 'hibernation-based' upgrade here ... I think we have seen in different kinds of contexts that this might be an important concept we have to build anyway (for saving cost, for changing hardware spec etc, also see [#1028 (comment)](https://github.com/opstrace/opstrace/issues/1028#issuecomment-879236408))
> 
> Some specific ideas:
> [#326 (comment)](https://github.com/opstrace/opstrace/issues/326#issuecomment-891833665)

Regarding EKS upgrade, I haven't done any research besides checking their release schedule. I don't know what we need to do besides recommending moving to EKS managed nodes since that seems to be, on paper, the better option. Hopefully the SDK is good enough.

About the hibernate, I don't see why that can't start in parallel. If it's required for the EKS upgrade then we have to build it anyway. If not then it's also a nice feature to announce.
