### ISSUE TITLE
Manually test custom auth0 client ID feature

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1175]
I was relying on automated tests where we did _not_ change the corresponding 'domain'.  That was a pitfall. I think this is actually broken for people other than us!

Rethink, manually test.

**Comment by puntakana** [comment]
Hi,

I tried to install opstrace with a custom dns and custom auth0 id and when I tried to enter on the application, I'm redirected to : https://opstrace-dev.us.auth0.com/authorize?audience=https%3A%2F%2Fuser-cluster.opstrace.io%2Fapi&client_id= blablabbla

So I can confirm It's broken for others :-)

**Comment by MatApple** [comment]
Thanks for varifying @puntakana!

**Comment by puntakana** [comment]
I guess you need to add a third parameter like custom_auth0_dns. I don’t know auth0 service very well but for me with only auth0 client id you can’t find the auth0 url. Indeed, opstrace cluster name can be different than auth0 tenant name and tenant can be in us/eu/asia so the auth0 url can be https://TENANT_NAME.{us,eu,….}.auth0.com

**Comment by jgehrcke** [comment]
@puntakana I am super happy that you're actually interested in this feature :) And sorry that we shipped something so obviously broken :fire:. We would love to hear about your use case! 

Let me try to get this right for the next release. :)

**Comment by MatApple** [comment]
Also linking to another question relating to this in our Opstrace Community Slack: https://opstrace-community.slack.com/archives/C01KZS8JRNC/p1629491378082700
