### ISSUE TITLE
Expose Alertmanager API to the internet using the auth proxy

### ISSUE THREAD

**Issue by MatApple** [opstrace/opstrace#1192]
As an operations engineer, I'd like to also use Opstrace's Alertmanager for managing alerts that originate outside of Opstrace.

**Comment by nickbp** [comment]
Would this be for configuring alertmanager, or something else? If just setting config via an authenticated API endpoint, there's support for that [via the `config` service](https://github.com/opstrace/opstrace/tree/main/go/cmd/config#alertmanager-http-examples)

**Comment by triclambert** [comment]
I think the keyword here is "outside"; for example, sending alerts to Alertmanager from some client that you control.

See: https://prometheus.io/docs/alerting/latest/clients/
