### ISSUE TITLE
aws: enable EKS console access to Opstrace cluster for certain AWS IAM roles

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#120]
AWS EKS introduced the Amazon EKS console:

* https://aws.amazon.com/blogs/containers/introducing-the-new-amazon-eks-console/
* https://docs.aws.amazon.com/eks/latest/userguide/getting-started-console.html

This is great: allows for introspection and debugging of an Opstrace cluster deployed on AWS. Brings it en par with the GKE UI.

But..does it? Well. No. Not by default.

Even when you operate under the AWS-provided IAM role `AdministratorAccess` you cannot inspect the nodes and workloads of your EKS cluster:

![Screenshot from 2020-12-06 14-48-49](https://user-images.githubusercontent.com/265630/101357077-41cc6c80-3899-11eb-8d4d-b32bdf5e5c2a.png)

That's probably OK / sane default behavior: principle of least privilege taken almost to the extreme (with `AdministratorAccess` not having access).

Proposal: introduce a mechanism, likely to be controlled via the `aws` cluster config field, via which certain AWS IAM roles are granted full access to the EKS cluster: read/write (so that nodes and workloads can be inspected and mutated) -- through the EKS console.

Resources:
* https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting_iam.html
* https://stackoverflow.com/q/50791303/145400
* https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access/
* https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html
* https://kubernetes.io/docs/reference/access-authn-authz/rbac/
* https://medium.com/faun/add-new-user-to-manage-aws-eks-e487c5d10ee3

**Comment by jgehrcke** [comment]
WIP/experimentation here: https://github.com/opstrace/opstrace/pull/112

**Comment by jgehrcke** [comment]
Initial stab at ref docs here: https://github.com/opstrace/opstrace/pull/121
Cleanup here: https://github.com/opstrace/opstrace/pull/122

**Comment by sreis** [comment]
I was able to login to EKS UI with the role defined in ci/cluster-config.yaml .

**Comment by jgehrcke** [comment]
> was able to login to EKS UI 

And you did saw workloads and nodes for your cluster @sreis? :)

**Comment by sreis** [comment]
> And you did saw workloads and nodes for your cluster @sreis? :)

Yes!
