### ISSUE TITLE
GCP Error: Quota exceeded for quota metric 'Mutate requests' and limit 'Mutate requests per minute'

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#1213]
```
[2021-08-08T18:10:55Z] 2021-08-08T18:10:55.577Z error: set up peering between CloudSQL VPC and Opstrace instance VPC: error during services.connections.create: Error: Quota exceeded for quota metric 'Mutate requests' and limit 'Mutate requests per minute' of service 'servicenetworking.googleapis.com' for consumer 'project_number:949705083365'.
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2818#aad3c57d-4ebb-47db-800a-a55e5f6dc839/6-28

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2817#f5f840c5-e14b-4ce0-922c-3c064932ccae/6-47

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2817#18ea427e-cd00-4ef0-985a-ba0c11518eed/6-34

**Comment by nickbp** [comment]
>  [2021-08-07T00:29:03Z] 2021-08-07T00:29:03.008Z [31merror[39m: set up peering between CloudSQL VPC and Opstrace instance VPC: error during services.connections.create: Error: Quota exceeded for quota metric 'Mutate requests' and limit 'Mutate requests per minute' of service 'servicenetworking.googleapis.com' for consumer 'project_number:949705083365'.

https://buildkite.com/opstrace/scheduled-main-builds/builds/2808#19a442c3-27c6-422c-a559-2dcfb0019cb1

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2816#e0a51924-0146-4d3d-a534-9d3f699dcc6b/6-14

**Comment by nickbp** [comment]
> [2021-08-07T00:31:15Z] 2021-08-07T00:31:15.066Z [31merror[39m: set up peering between CloudSQL VPC and Opstrace instance VPC: error during services.connections.create: Error: Quota exceeded for quota metric 'Mutate requests' and limit 'Mutate requests per minute' of service 'servicenetworking.googleapis.com' for consumer 'project_number:949705083365'.

https://buildkite.com/opstrace/scheduled-main-builds/builds/2808#b8e96e1f-80b2-4fa9-921c-c7cf364be451 (same as above except under `test upgrades (GCP)`)

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2814#e4915e77-55d8-43a8-8f1b-95d0ad32b425/6-21

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2814#5b18987b-15fa-41a6-b3e6-1582ce08aecf/6-11

**Comment by terrcin** [comment]
Got alot further this time before hitting the quote limit:

https://buildkite.com/opstrace/upgrade-tests/builds/1154#f8eb7ea6-ce80-4aac-acbb-a9ef840ff920/455-732

```
[2021-08-08T00:53:29Z] 2021-08-08T00:53:29.726Z info: Global Address is RESERVED
--
  | [2021-08-08T00:53:29Z] 2021-08-08T00:53:29.726Z info: Peering cluster vpc with cloudSQL services vpc
  | [2021-08-08T00:53:30Z] 2021-08-08T00:53:30.041Z error: failed creating service peering for cloudSQL and cluster vpc: % Quota exceeded for quota metric 'Mutate requests' and limit 'Mutate requests per minute' of service 'servicenetworking.googleapis.com' for consumer 'project_number:949705083365'.: Error: Quota exceeded for quota metric 'Mutate requests' and limit 'Mutate requests per minute' of service 'servicenetworking.googleapis.com' for consumer 'project_number:949705083365'.
  | [2021-08-08T00:53:30Z]     at Gaxios._request (/snapshot/build/node_modules/gaxios/src/gaxios.ts:140:15)
  | [2021-08-08T00:53:30Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  | [2021-08-08T00:53:30Z]     at JWT.requestAsync (/snapshot/build/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18)
  | [2021-08-08T00:53:30Z]     at peerVpcs (/snapshot/build/lib/gcp/build/cloudSQL.js)
  | [2021-08-08T00:53:30Z] 2021-08-08T00:53:30.042Z info: Ensure SQLInstance exists
  | [2021-08-08T00:53:30Z] 2021-08-08T00:53:30.042Z info: Attempt 0 to create SQLInstance
  | [2021-08-08T00:53:36Z] 2021-08-08T00:53:36.868Z info: GKECluster is PROVISIONING
  | [2021-08-08T00:53:40Z] 2021-08-08T00:53:40.421Z info: create SQLInstance
  | [2021-08-08T00:53:47Z] 2021-08-08T00:53:47.219Z info: GKECluster is PROVISIONING
  | [2021-08-08T00:53:47Z] 2021-08-08T00:53:47.495Z debug: Creating SQLInstance failed, retrying: GaxiosError: Invalid request: Incorrect Service Networking config for instance: ci-shard-ddd:upgrade-bk-1154-83d-g-1628384020044:NETWORK_NOT_PEERED.
  | [2021-08-08T00:53:47Z]     at Gaxios._request (/snapshot/build/node_modules/gaxios/src/gaxios.ts:140:15)
  | [2021-08-08T00:53:47Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  | [2021-08-08T00:53:47Z]     at JWT.requestAsync (/snapshot/build/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18) {
  | [2021-08-08T00:53:47Z]   response: [Object],
  | [2021-08-08T00:53:47Z]   config: [Object],
  | [2021-08-08T00:53:47Z]   code: 400,
  | [2021-08-08T00:53:47Z]   errors: [Array]
  | [2021-08-08T00:53:47Z] }
  | [2021-08-08T00:53:47Z] 2021-08-08T00:53:47.495Z info: Attempt 1 to create SQLInstance
  | [2021-08-08T00:53:57Z] 2021-08-08T00:53:57.579Z info: GKECluster is PROVISIONING
  | [2021-08-08T00:53:57Z] 2021-08-08T00:53:57.934Z info: create SQLInstance
```

and then hit this issue: https://github.com/opstrace/opstrace/issues/293

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2813#f238b8a1-feca-49d1-a166-93303943360d/6-51

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2812#37b03f81-06c1-40f3-a3e1-6c2bddba1625/6-39

**Comment by terrcin** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2811#347daca5-7e05-45ea-815c-00563acff477/6-13

**Comment by nickbp** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2810#ff3672a2-5237-42f6-8f30-05d008cbfab3

**Comment by nickbp** [comment]
gcp main and upgrade: https://buildkite.com/opstrace/scheduled-main-builds/builds/2820

**Comment by jgehrcke** [comment]
I had a look into this on my Saturday morning and found that it's "just" a properly working rate limit. That is, the service connection CREATE requests are incoming at a certain rate. That rate exceeds a threshold. Some of these requests are responded to with this `'Mutate requests per minute'` response. Those requests then do not count into the limit, and after a while a CREATE request then goes through again.

High-level conclusion: only a cosmetic problem.

Still, of course it makes sense to reduce the rate of retrying the CREATE request. Doing so.

**Comment by jgehrcke** [comment]
The retry rate gets elevated across high-level retries because the individual retrying executor does not get stopped: 
https://github.com/opstrace/opstrace/issues/26

I have seen that by looking at the attempt numbers in adjacent log lines:
```
[2021-08-08T14:23:26Z] 2021-08-08T14:23:26.032Z info: set up peering between CloudSQL VPC and Opstrace instance VPC: connections.create(): attempt 350 failed, retry soon
...
[2021-08-08T14:23:27Z] 2021-08-08T14:23:27.371Z info: set up peering between CloudSQL VPC and Opstrace instance VPC: connections.create(): attempt 673 failed, retry soon
```

**Comment by jgehrcke** [comment]
closing this already after landing #1219.
