### ISSUE TITLE
cli(upgrade): check controller version before running the upgrade

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1223]
**Describe the bug**

Discovered while triaging #1217.

The `upgrade` command flow stops the opstrace controller (sets the number of replicas in the deployment to zero) and then proceeds to check the controller image tag version. If they don't match then the image tag version is updated and the deployment is restarted (sets the number of replicas back to one).

When the opstrace controller image tags match the number of replicas is never set back to one.

**Comment by jgehrcke** [comment]
bug could be worded as `upgrade initiated when versions match`.

It's an interesting question to ask which piece of information _in_ the Opstrace instance is used to determine the _current_ Opstrace instance version. The controller config now contains the last CLI version used to create/upgrade. That could be semantically the best reference. However, it should be a system invariant that the controller version actually matches that.

Maybe the upgrade command should actually check both and validate the invariant, and error out with an error message about bad state being observed when the invariant is violated.

**Comment by sreis** [comment]
> It's an interesting question to ask which piece of information in the Opstrace instance is used to determine the current Opstrace instance version. The controller config now contains the last CLI version used to create/upgrade: #1047
> That (last CLI version) could be semantically the best reference. However, it should be a system invariant that the controller version actually matches that.

We were on the same page regarding this.

> Maybe the upgrade command should actually check both and validate the invariant, and error out with an error message about bad state being observed when the invariant is violated.

Nice catch. Added a check for this in #1225.
