### ISSUE TITLE
proposal: extra validation of initial instance config

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1239]
## Current Behavior / Proposed Behavior

How can we avoid creating instances with broken configs before the user even attempts the `create` operation?

## Context

Users can create an Opstrace instance with a broken configuration, for example, use small nodes in combination with small node counts which prevents all required pods from being deployed.

## Possible Technical Solution

Add a validation step in the `create` command that validates the user config. For example, using the [number of max pods per instance type](https://github.com/awslabs/amazon-eks-ami/blob/master/files/eni-max-pods.txt) calculate the minimum number of required nodes given our default configuration. This will also require calculating the number of pods per deployment given the tenant count as input as well.

## Alternatives Considered

NA

**Comment by triclambert** [comment]
+1
