### ISSUE TITLE
chore: automate the procedure to regenerate the alerts and rules from source:

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1252]
Procedure to regenerate the alerts and rules from source:

1.  Create YAML from JSONNET:

   ```
   gh repo clone grafana/cortex-jsonnet
   cd cortex-jsonnet
   make build-mixin
   yq eval cortex-mixin/out/alerts.yaml -j -P > alerts.json
   sed -i '' 's/#.*//' -e '^$' cortex-mixin/out/rules.yaml
   yq eval cortex-mixin/out/rules.yaml -j -P > rules.json
   ```

2. Open the JSON in VScode and convert it to a Javascript object.
   * Would be nice to find a command-line tool for this; a quick search come up empty.

3. Manually remove the `cortex_storage` group, which had references to Cassandra, Bigtable, and DynamoDB.
   * This could be automated with `jq` in the future.

4. Paste into the right spot of `alerts.ts` and `rules.ts` (being careful not to delete other content).
   * Perhaps in the future, we could decompose these files to make it easier to paste the content in.

Hopefully, these manual steps can be automated for the future so we can keep them up-to-date on a regular basis.

_Originally posted by @triclambert in https://github.com/opstrace/opstrace/issues/1189#issuecomment-896264438_

**Comment by sreis** [comment]
Automate it in order to follow the rule sin upstream cortex-jsonnet.

**Comment by triclambert** [comment]
It looks like `cortex-jsonnet` does not keep up with `cortex` proper.  Right now, there is [Cortex 1.10](https://github.com/cortexproject/cortex/releases/tag/v1.10.0) but only [Cortex JSONNET 1.9.0](https://github.com/grafana/cortex-jsonnet/releases).

**Comment by triclambert** [comment]
The Loki mixins do not seem to have a default build mechanism; we will need to create one.

https://github.com/grafana/loki/issues/2468
