### ISSUE TITLE
Make fluentd support GKE 1.18 log format

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1254]
With #1171 we now handle pods logs on GKE 1.19 but we're not forcing the GKE node upgrade and instead rely on the automatic upgrades. The node upgrade will only occur when the default GKE version is bumped (sometime this month). 

Unfortunately, it looks like the fluentd CRI plugin doesn't handle pods logs on GKE 1.18.

We need to have the opstrace controller deploy a version of fluentd that is compatible with GKE 1.18.

**Comment by sreis** [comment]
I suspect this is what's caused #1247 since fluentd logs a bunch of `/` (dashes) to stdout when it fails to parse a log.

**Comment by jgehrcke** [comment]
Let's remember https://github.com/opstrace/opstrace/issues/407
