### ISSUE TITLE
test-upgrade artifacts are not collected

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1256]
**Describe the bug**

While [triaging](https://github.com/opstrace/opstrace/pull/1253#issuecomment-897176617) another issue I noticed the artifacts for the test-upgrade build are not collected. 

Confirmed in one of the recent [main builds](https://buildkite.com/opstrace/scheduled-main-builds/builds/2838#5870a81f-d840-4943-8a18-1480840f213f/7402-7404)
```
[2021-08-11T21:23:01Z] $ buildkite-agent artifact upload /tmp/builddir-prs-upgr-bk-2838-3c8-g/bk-artifacts/**/*
[2021-08-11T21:23:01Z] 2021-08-11 21:23:01 INFO   No files matched paths: /tmp/builddir-prs-upgr-bk-2838-3c8-g/bk-artifacts/**/*
```

**Comment by jgehrcke** [comment]
I closed https://github.com/opstrace/opstrace/issues/1241 with a commit but I think that was premature. Will look into that now! Sorry for the hassle. Meh.

**Comment by sreis** [comment]
@jgehrcke no worries. I was going to pick it up now but thank you for taking care of it.
