### ISSUE TITLE
AWS S3 buckets aren't fully cleared on cluster teardown

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#1258]
We use lifecycle rules to delete the contents of S3 buckets, with a default of checking for a subdir named `system` for the system tenant. But we don't do anything for other subdirs. As a result we can see leftover buckets after CI runs and similar, even well beyond the expected 24H delay.

For example an old CI run will leave behind these buckets, because they aren't successfully emptied:
```
$ aws s3 ls s3://upgrade-bk-1179-c45-a-cortex-config/
                           PRE alertmanager/
                           PRE alerts/
                           PRE rules/

$ aws s3 ls s3://upgrade-bk-1179-c45-a-loki/
                           PRE default/
                           PRE index/
```

The problem seems to be an interaction between the uninstaller's `aws.ts` and the aws utility library's `bucket.ts`:
- uninstaller `aws.ts`:
    ```
      for (const bn of [
        lokiBucketName,
        lokiConfigBucketName,
        cortexDataBucketName,
        cortexConfigBucketName
      ]) {
        taskGroup4.push(
          yield fork([new S3BucketRes(destroyConfig.clusterName, bn), "teardown"])
        );
      }
    ```
- `lib/aws/bucket.ts`:
    ```
      constructor( // S3BucketRes
        opstraceClusterName: string,
        bucketName: string,
        retentionPeriod = 0,
        tenants: string[] = []
      ) {
        [...]
        // Don't forget the system tenant in the lifecycle rules
        const tnames = [...tenants];
        tnames.push("system");

        // For each tenant create a lifecycle rule that deletes data when retention
        // period is reached. The retention period follows the following rules (from
        // https://aws.amazon.com/premiumsupport/knowledge-center/s3-lifecycle-rule-delay/):
        [...]
    ```

So the AWS code is always trying to delete a `system` subdir, but nothing else since the caller isn't passing the list of tenants. Meanwhile the non-tenant subdirs like `index` are ignored as well.

This doesn't fix our problem (why are buckets disappearing during test runs) but it does at least explain the leftover buckets that we keep getting: their contents aren't fully erased. I wonder why we can't just set the lifecycle rule to delete everything under `/` rather than requiring names of all the subdirs...

**Comment by nickbp** [comment]
Actually from looking more at `bucket.ts`, it looks like there are two different sets of lifecycle rules added. The first set is for the "tenant directories" (only `system/*` in practice) and has a retention period of `Days: 0`, while the other one that I hadn't seen is for the full bucket and has a retention period of `Days: 1`. So in the above `s3://upgrade-bk-1179-c45-a-*` example the other dirs may just not have had enough time to get deleted fully.

I think it'd make sense to just clean up the lifecycle policy creation to skip the special tenant subdir case, since many buckets do not have tenant subdirs and it's a little confusing seeing the partially erased buckets. If we wanted to be really careful, we could have an initial retention policy that tries to delete everything with `Days: 0`, and then another (the current one) that tries again with `Days: 1`.

**Comment by nickbp** [comment]
For reference the tenant cleanup is [here](https://github.com/opstrace/opstrace/blob/main/lib/aws/src/bucket.ts#L69) while the `/*` cleanup is [further down](https://github.com/opstrace/opstrace/blob/main/lib/aws/src/bucket.ts#L249) in the same file.

**Comment by nickbp** [comment]
Agh I just noticed that further up in that `S3BucketRes` constructor there's this check:
```
    if (retentionPeriod === 0) {
      // Retention period disabled, skip configuration of lifecycle rules
      return;
    }
```

So only the 1D `/*` cleanup should be occurring in the uninstall case, while the per-tenant cleanups would only be defined in the install case. So it's a bit of a mystery why we're seeing a missing `system` dir in the `loki` bucket while `default` is still present. It does nonetheless look like there's something weird going on with the S3 cleanup, but maybe my initial assumptions aren't it.

**Comment by nickbp** [comment]
Something I discovered is that the installer side of things doesn't clean up any policies that may already be there on the `config` buckets. For example I recreated the `nick-test` opstrace instance and it reused the prior buckets. The `loki-config` and `cortex-config` buckets both have the uninstaller's 1D policy from the prior instance of `nick-test`, while the `loki` and `cortex` buckets only have the per-tenant-subdir policies. So this would be something to fix in the refactoring.

**Comment by jgehrcke** [comment]
> For reference the tenant cleanup is here while the /* cleanup is further down in the same file.

https://gehrcke.de/2020/03/github-y-y/ :)

**Comment by jgehrcke** [comment]
>  They all have opstrace-uninstall-auto-delete-after-one-day (aka the 1D /* policy) and no others.

**Comment by jgehrcke** [comment]
> Something I discovered is that the installer side of things doesn't clean up any policies that may already be there on the config buckets. For example I recreated the nick-test opstrace instance and it reused the prior buckets. The loki-config and cortex-config buckets both have the uninstaller's 1D policy from the prior instance of nick-test, while the loki and cortex buckets only have the per-tenant-subdir policies. So this would be something to fix in the refactoring.

Oh great point. And that relates to a wider discussion. Mixing old and new state in an unconscious way is always a recipe for disaster. 

When we find buckets pre-existing upon `create`, we have to -- in theory -- do a whole lot of analysis on them to see if we can and should "continue using" the current state, or if we have to cleanly wipe state and start from scratch. And that of course affects bucket contents as well as bucket configuration including lifecycle rules.

Relates to https://github.com/opstrace/opstrace/issues/20

I think a specific follow-up task to fix an obvious 'continuation' bug is:  upon `create`, remove all current lifecycle rules
