### ISSUE TITLE
UI: shows wrong build information

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1292]
build info in UI is wrong. tested manually. opstrace instance created with
```
± ./opstrace --version --log-level=debug
4c0b00ef-ci
2021-08-17T12:33:19.253Z debug: BUILD_INFO_COMMIT: 4c0b00ef
2021-08-17T12:33:19.253Z debug: BUILD_INFO_TIME_RFC3339: 2021-08-17 06:01:44+00:00
2021-08-17T12:33:19.253Z debug: BUILD_INFO_HOSTNAME: ip-10-0-2-39.us-west-2.compute.internal
2021-08-17T12:33:19.253Z debug: BUILD_INFO_BRANCH_NAME: main
2021-08-17T12:33:19.254Z debug: shut down logger, then exit with code 0
```
UI shows `6e9a12df-ci` and branch `jp/ui-retry-auth-status-request`.

**Comment by jgehrcke** [comment]
Problem is this discrepancy:

https://github.com/opstrace/opstrace/blob/11f1de65e6ba279d532d58ae5d74b0ff3a87fb49/packages/app/Makefile#L8

https://github.com/opstrace/opstrace/blob/11f1de65e6ba279d532d58ae5d74b0ff3a87fb49/packages/app/Dockerfile.app#L65

Not all input into the Docker image build is used for the 'shortcut' checksum calculation. This will always happen. I think we should simply to make the Docker image build as fast as possible (using proper layer caching), and otherwise live with the fact that we need a new app image for _every_ build / commit, otherwise we cannot bake the version information into the image. And that's really no problem if that tiny detail changes in the last layer or one of the last layers.

**Comment by triclambert** [comment]
From Settlemint:

![image](https://user-images.githubusercontent.com/19239758/130692174-ad8c029c-9b3a-4707-9596-11104c7d531c.png)
