### ISSUE TITLE
yup: bump beyond 0.28.5

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1301]
We are stuck with https://github.com/jquense/yup/blob/master/CHANGELOG.md#0285-2020-04-30 because the typing changes after that were pretty significant. I touched this two or three times. Pain was significant and I backed out. Yet, we have to overcome this.

**Comment by MatApple** [comment]
@MoSattler perhaps you can take a swing at this once you're in a good spot with the error handling UX
