### ISSUE TITLE
graphql-hasura maintenance bump: make 1.3 -> 2.x transition

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1302]
See https://github.com/opstrace/opstrace/blob/b00d2a20701f2455f1340bb1b23a5de9b85011ca/packages/app/Dockerfile.graphqlserver#L1 

We are on 1.x, the ecosystem has moved forward to 2.x with several point releases.

**Comment by MoSattler** [comment]
This transition would alleviate a security problem we have where a dependency in app, `hasura-cli@1.3.3`, adds vulnerable packages to our app.
There is a hot fix for this problem in https://github.com/opstrace/opstrace/pull/1433, but the proper way of handling this would be updating all the tooling to version >2.
