### ISSUE TITLE
error boolean@3.1.3: The engine "node" is incompatible with this module. Expected version ">= 16.7.0". Got "16.4.2"

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1308]
**Describe the bug**
[Third-party dependency](https://www.npmjs.com/package/boolean) had a release that [broke our build](https://github.com/thenativeweb/boolean/issues/317). Noticed it running builds locally but it seems to have affected CI as well. 

https://buildkite.com/opstrace/scheduled-main-builds/builds/2903#68069503-ff47-4e95-ac01-9b29a5ff0f25/1336-1343

**Comment by jgehrcke** [comment]
oh and the looker "dev env build" is btw 'on purpose' not using a yarn.lock file; has pros and cons of course :)
