### ISSUE TITLE
Add support for using existing network in GCP

### ISSUE THREAD

**Issue by agarat** [opstrace/opstrace#1347]
## Current Behavior / Proposed Behavior
At the moment, the opstrace cli creates a new network in the project. It would be helpful if it could use an already created network. This would allow us to control the network segment that Opstrace uses.

## Context
Suppose you want to send your metrics and logs via the internal network in GCP to avoid egress traffic (using vpc peering), if you have a project which uses the same network as the opstrace cluster, it would cause IP conflicts. On the other hand, if you have networks in different segments, it would be easier to set up the network peering.

**Comment by jgehrcke** [comment]
Thank you @agarat! Makes sense. Connecting the dots: while this ticket here is GCP, specific, I think the same high-level idea is expressed in  https://github.com/opstrace/opstrace/issues/1236.
