### ISSUE TITLE
Expose Grafana API endpoints for tenants

### ISSUE THREAD

**Issue by agarat** [opstrace/opstrace#1369]
## Current Behavior / Proposed Behavior
At the moment it's not possible to access the Grafana API in our tenants. This would be helpful, for example when using tools to migrate dashboards or create dashboards backups.

## Context
We are trying to migrate a significant amount of dashboards from our current Grafana instance. It would be easier to do this via API.

**Comment by Yasumoto** [comment]
Came here to post exactly this! Definitely would be helpful to start to populate Grafana with interesting dashboards much more quickly.

**Comment by Yasumoto** [comment]
Here's a real quick workaround for the terraform provider for now:

1. [Client](https://github.com/Yasumoto/grafana-api-golang-client/commit/fc620acbdb3e582833334f19fc011ddc2f8a2126)
2. [Provider](https://github.com/Yasumoto/terraform-provider-grafana/commit/6b9fd5e17a5869f5ed7d661ff3134d5ea7755069)
