### ISSUE TITLE
Expectation not fulfilled within 30 s (check loki ingester logs & check cortex ingester logs)

### ISSUE THREAD

**Issue by MatApple** [opstrace/opstrace#1381]
Only appeared on AWS.

https://buildkite.com/opstrace/scheduled-main-builds/builds/3066#6b28ccaf-2c3e-43dd-90f7-16fde8527184/713-2615

<img width="1076" alt="Screen Shot 2021-09-08 at 6 27 51 PM" src="https://user-images.githubusercontent.com/465022/132607004-64465834-89a6-4b28-a47e-aeb6b7f0499d.png">

**Comment by jgehrcke** [comment]
That's #1226, carried over to here: https://github.com/opstrace/opstrace/issues/1226#issuecomment-916020197
