### ISSUE TITLE
chore: increase hop limit to access AWS instance metadata service during upgrade

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1383]
Apply the fix described in #1382 but during an infra upgrade.

**Comment by jgehrcke** [comment]
https://docs.aws.amazon.com/autoscaling/ec2/userguide/change-launch-config.html

> An Auto Scaling group is associated with one launch configuration at a time, and you can't modify a launch configuration after you've created it. To change the launch configuration for an Auto Scaling group, use an existing launch configuration as the basis for a new launch configuration. Then, update the Auto Scaling group to use the new launch configuration.

If we "modify instance metadata" for each instance that the upgrader can see when it runs then the change is not persistent: if an instance goes away, then the auto-scaling group (ASG) will launch a new instance based on the old launch configuration (LC), and the relevant patch will be reverted.

Looks like what we really want to do also is "update the Auto Scaling group to use the new launch configuration". Question is: in the moment an ASG is updated with a new LC -- does this trigger an immediate rollover of instances?

**Comment by jgehrcke** [comment]
> https://docs.aws.amazon.com/cli/latest/reference/autoscaling/update-auto-scaling-group.html

https://docs.aws.amazon.com/cli/latest/reference/autoscaling/update-auto-scaling-group.html should provide answers.

> The new settings take effect on any scaling activities after this call returns.

> If you associate a new launch configuration or template with an Auto Scaling group, all new instances will get the updated configuration. Existing instances continue to run with the configuration that they were originally launched with.

beautiful.

**Comment by jgehrcke** [comment]
So. What we want to do: create a new launch configuration. We use a rather strict naming convention, and another interesting question is if we can 'replace' the LC with the new one, keeping that name, while the ASG that consumes the old LC is still in place (there might be a dependency error as of which the old LC cannot be deleted, and the new LC might need to get a new name deviating from the naming convention which might require new installer/uninstaller logic :fire:)

**Comment by sreis** [comment]
> If we "modify instance metadata" for each instance that the upgrader can see when it runs then the change is not persistent: if an instance goes away, then the auto-scaling group (ASG) will launch a new instance based on the old launch configuration (LC), and the relevant patch will be reverted.

I would be ok with this in the short term to have the fix available for the next release. An instance disappearing is an unlikely scenario and mostly because as you say:

> What we want to do: create a new launch configuration.

We'll also need to do this to upgrade the EKS version (for https://github.com/opstrace/opstrace/issues/1169). I was evaluating the managed EKS nodes but they have  

Thoughts on providing a workaround as soon as possible and add the fix in the new ASG when we bump the EKS version?

**Comment by jgehrcke** [comment]
> Thoughts on providing a workaround as soon as possible and add the fix in the new ASG when we bump the EKS version?

as always; if things can be split and done in small units, and if an individual unit brings improvement: :rocket:

**Comment by sreis** [comment]
Addressed in #1390.
