### ISSUE TITLE
Some source code files are missing license header

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#139]
**Describe the bug**

Some files are missing the license header which is currently breaking the builds

https://buildkite.com/opstrace/scheduled-main-builds/builds/1331#4398ea90-3355-4d9f-b79b-1612c62b13cc/1163-1649
```
[2020-12-09T00:11:43Z] make[1]: *** [Makefile:267: check-license-headers] Error 1
```

**To Reproduce**

Run:
```
make check-license-headers
```

**Expected behavior**

All source code files should have a header with the license.

**Comment by jgehrcke** [comment]
Thanks for creating the ticket @sreis!

I had a quick look -- the directory `packages/app/src/state/file/hooks/__tests__/` was added yesterday, and the green CI on the corresponding PR didn't yet represent that new CI check. That's a bit of a relief (an expected race condition).

Also see https://github.com/opstrace/opstrace/pull/140#discussion_r539229001.
