### ISSUE TITLE
Updating runtime config yaml triggers a restart of the ingesters

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#1391]
**Describe the bug**

Copying comment from @nickbp: 

> It's been a couple months but I think I saw edits to the cortex-runtime-config ConfigMap triggering a rolling restart for the pods using that ConfigMap. Again could be wrong though - or it may have been fixed via the cortex operator?

**Comment by nickbp** [comment]
Example from before was via manually applying `ingester_limits` in a [`cortex/cortex-runtime-config` ConfigMap](https://github.com/opstrace/test-infra/blob/main/opstrace-kube-overrides.yaml#L51)

The rollout may have been a side effect of applying the ConfigMap directly, rather than changing limit values via the UI config?

**Comment by jgehrcke** [comment]
From Cortex' point of view, a process restart is not part of the runtime config design. Cortex processes read the runtime config file periodically, and pick up changes at runtime.

**Comment by jgehrcke** [comment]
We can answer this hypothesis using logs/artifacts from any CI run.

We have `test_submit_cortex_runtime_config` as part of `test-remote`: https://github.com/opstrace/opstrace/blob/d301732acf85d5c48f76d9a753c82466832690ef/test/test-remote/test_ui_api.ts#L521

looking at the GCP part of https://buildkite.com/opstrace/scheduled-main-builds/builds/3110.

runtime config update was triggered at `09:36:28Z`:

```
[2021-09-14T09:36:28Z] 2021-09-14T09:36:28.146Z info: HTTP resp to POST(https://schedul-bk-3110-d30-g.opstracegcp.com/_/cortex/runtime_config):
[2021-09-14T09:36:28Z]   status: 202
[2021-09-14T09:36:28Z]   body[:500]: accepted: change is expected to take effect soon
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/3110#ca752c56-63b6-43af-80a2-7e693e3ce453/4852-5180

change was reflected about 50 s later:

```
09:37:18.981Z info: found "tenantnamebar" in response body:
```

but most importantly, we can look at when ingesters got restarted as part of this ci run via `tmp/builddir-schedul-bk-3110-d30-g/bk-artifacts/kubectl_controller_describe-schedul-bk-3110-d30-g.log`:

```
Name:         ingester-0
Namespace:    cortex
Priority:     0

...
Events:
  Type     Reason                  Age                From                     Message
  ----     ------                  ----               ----                     -------
  Normal   Scheduled               26m                default-scheduler        Successfully assigned cortex/ingester-0 to gke-schedul-bk-3110-d30-g-primary-73039aee-gls0
  Normal   SuccessfulAttachVolume  26m                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-631bf29f-f758-409d-a9dc-c848bf1620fd"
  Normal   Pulled                  26m                kubelet                  Container image "cortexproject/cortex:master-74055d8" already present on machine
  Normal   Created                 26m                kubelet                  Created container ingester
  Normal   Started                 26m                kubelet                  Started container ingester
  Warning  Unhealthy               25m (x2 over 25m)  kubelet                  Readiness probe failed: HTTP probe failed with statuscode: 503
```

now via grep:
```
$ cat kubectl_describe_all-schedul-bk-3110-d30-g.txt | grep cortex/ingester-0
  Normal   Scheduled               26m                default-scheduler        Successfully assigned cortex/ingester-0 to gke-schedul-bk-3110-d30-g-primary-73039aee-gls0
```

@sreis @nickbp maybe you can also review the `kubectl_controller_describe-schedul-bk-3110-d30-g.log` to double-check, but this looks like the ingesters were not restarted as of said runtime config update.

On the other hand, the controller log file contains:

```
2021-09-14T09:36:28.763Z [32minfo[39m: API update request 1 of 1
2021-09-14T09:36:28.764Z [32minfo[39m: Updating 1 Cortices:
2021-09-14T09:36:28.764Z [32minfo[39m: Updating Cortices: cortex/opstrace-cortex
```
What exactly did the controller update here?
