### ISSUE TITLE
Invalid url in the ending metrics from an existing system

### ISSUE THREAD

**Issue by ajayk** [opstrace/opstrace#1396]
**Describe the bug**
invalid domain name displayed on the "Sending metrics from an existing system" page of Getting started 

**To Reproduce**
1. Go to Getting started Page 
2. CHeck the url in the Sending metrics from an existing system

**Expected behavior**
Extra opstrace.io subdomain should not be present 

<img width="992" alt="Screen Shot 2021-09-15 at 12 20 45 PM" src="https://user-images.githubusercontent.com/1015125/133499832-bd6ec936-010e-49c9-ad00-946c28782b10.png">

**Comment by jgehrcke** [comment]
Resolved via https://github.com/opstrace/opstrace/pull/1397.
