### ISSUE TITLE
ci: scheduled main build errors with 'custom_auth0_client_id' requires 'custom_auth0_domain' and vice versa

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1405]
```
[2021-09-20T15:07:55Z] 2021-09-20T15:07:55.421Z error: invalid config document: 'custom_auth0_client_id' requires 'custom_auth0_domain' and vice versa
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/3160#fcf60e47-a465-461c-be48-52bb1131477d/318-366

**Comment by jgehrcke** [comment]
Requires expected follow-up, as noted in this commit msg: https://github.com/opstrace/opstrace/pull/1380/commits/3c57e86900d90dc82f2015b9d264cf2d0f8a8b3f

**Comment by MoSattler** [comment]
https://buildkite.com/opstrace/prs/builds/5822#ba5b8cc8-a150-4e06-84c5-9c28731c7e93/340-388

**Comment by jgehrcke** [comment]
> Had this issue in an unscheduled CI run

Rebasing your PR granch onto latest `main` should address this!
