### ISSUE TITLE
Auto-restart NotReady EKS nodes?

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#1408]
I've occasionally seen instances of EKS nodes where the kubelet has stopped reporting and has become `NotReady`, but the EC2 instance never seems to get restarted. If I manually restart the EC2 instance, it comes back and everything is fine again, but it feels like there should be a mechanism to automate this.

**Comment by nickbp** [comment]
From some asking around it sounds like this should be possible via [health checks](https://docs.aws.amazon.com/autoscaling/ec2/userguide/healthcheck.html#as-configure-healthcheck) on the autoscale group

**Comment by triclambert** [comment]
What if we switch to managed node pools?  /cc @sreis

**Comment by omerfsen** [comment]
+1

**Comment by jgehrcke** [comment]
> What if we switch to managed node pools?

related: https://github.com/opstrace/opstrace/issues/1169#issuecomment-891868567
