### ISSUE TITLE
disaster debuggability: add system tenant prometheus as data source for system tenant grafana

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#1413]
In view of Cortex downtime it is highly valuable if we can populate system monitoring dashboards using metrics queried directly from the system tenant's Prometheus instance. Today one can set up a `kubectl`-based port forward and then add a new data source -- why not make this simpler by adding a corresponding drop-down item in the Grafana dashboard data source enumeration field. This also requires adding the corresponding HTTP proxy information flow, probably a simple thing to add.

**Comment by triclambert** [comment]
Along these lines, it would be nice to support a dual remote_write for the system prom to write to another Prom instance or another Opstrace instance.
