### ISSUE TITLE
ci: upgrade tests failing since monday

### ISSUE THREAD

**Issue by triclambert** [opstrace/opstrace#1415]
The [Upgrade Tests](https://buildkite.com/opstrace/upgrade-tests) pipeline has been failing since Monday morning PDT.

![image](https://user-images.githubusercontent.com/19239758/134422006-ddc72f76-5765-435b-af39-79c59e9b5294.png)

With the following error: 

```
error: invalid cluster config document: unexpected key(s): custom_auth0_domain
```

**Comment by jgehrcke** [comment]
In the failing scheduled upgrade tests the FROM version is `a0ce4722` (see [this log](https://buildkite.com/opstrace/upgrade-tests/builds/1443#77e9461a-955e-4573-902d-21a952f4f578/331-348) for example). That commit hash corresponds to the `v2021.08.13` tag.

It should however be the latest release which is `v2021.09.17`.

For the `v2021.08.13` release the `custom_auth0_domain` parameter is indeed unexpected, i.e. the config validation error is expected.

The FROM version for the scheduled upgrade test is not codified in our repo. It is configured in the Buildkite UI:

![Screenshot from 2021-09-23 13-18-07](https://user-images.githubusercontent.com/265630/134498187-7e8cc3c0-345b-4a1e-8525-386912af6a6e.png)

We are lacking a TODO item in the release checklist to update this as part of making a new release. Therefore I did not update that last Friday.

I have now updated this to be `OPSTRACE_CLI_VERSION_FROM: https://go.otr.dev/cli-latest-release-linux`. This is also what we use in the per-PR upgrade test: `https://github.com/opstrace/opstrace/blob/57110b800deb3078029c269e0666e1ea03cff386/.buildkite/pipeline.yml#L80`.
