### ISSUE TITLE
Support HA Prometheus setups

### ISSUE THREAD

**Issue by reinoudk** [opstrace/opstrace#1468]
## Current Behavior / Proposed Behavior
When sending data to Opstrace using `remote_write` config, from an HA Prometheus setup, configured with the following `external_labels` config:

```
cluster: some-cluster-identifier
__replica__: $(POD)
```

I expect the timeseries to be de-duplicated. As the config for the distributor currently has the `enable_ha_tracker` option set to `false`, this is not the case. 

## Context

Because the timeseries are not de-duplicated, we get double metric values, as can be seen from these Grafana screenshots:

**Local Grafana**
![local-grafana](https://user-images.githubusercontent.com/2184455/138250189-a46c20f2-a70c-44fe-8ae4-9cbccff96682.png)

**Opstrace Grafana**
![opstrace-grafana](https://user-images.githubusercontent.com/2184455/138250191-9557934e-99ad-46bb-bed5-9e751ca01d29.png)

For resilience purposes, we are running an HA Prometheus setup in all our clusters. We'd like to send metrics from both Prometheus instances to a central Opstrace installation. We are currently doing this with our "regular" Cortex setup as well, but we are evaluating whether we can replace that with Opstrace, to reduce management overhead.

Note: I've seen #214, but that seems focused on the configuration for the system tenant, not user tenants.

## Possible Technical Solution

Update the config to enable the HA tracker, or make this configurable, as described in the Cortex docs: https://cortexmetrics.io/docs/guides/ha-pair-handling/#server-side .

## Alternatives Considered

Not running an HA Prometheus setup, or configuring only a single instance for remote write would fix the duplicate metrics issues, but this is not an option because of resilience requirements.

**Comment by sreis** [comment]
Opstrace deploys Cortex using `memberlist` for the gossip protocol, and there's this caveat in the [documentation for Cortex distributor HA tracker](https://cortexmetrics.io/docs/configuration/configuration-file/#distributor_config): 

> Please be aware that memberlist is not supported by the HA tracker since gossip propagation is too slow for HA purposes.

To support HA Prometheus set-ups, we'll need to introduce a supported KV store (Consul or etcd). We'll need to do more research and discuss options.

**Comment by agermain** [comment]
@sreis Sorry if it seems obvious, but is it a correct assumption that `ha_replica_label` within Cortex is not honoured as of today?

**Comment by sreis** [comment]
@agermain The HA tracker is (currently) disabled by default so the `ha_replica_label` is not honored.
