### ISSUE TITLE
[GCP] Error: SQLInstance creation deadline hit after 60 attempts

### ISSUE THREAD

**Issue by nagyv** [opstrace/opstrace#1485]
**Describe the bug**

The `opstrace create gcp` command fails creating the SQLInstance. The GCP console does not even show any trials.

**To Reproduce**

1. Follow the quickstart with minor modifications
   - having a custom Auth0 app
   - having a custom `custom_dns_name`
   - having custom region
```
gcp:
  region: europe-west3
  zone_suffix: b
```

The script gives

```
2021-11-25T20:51:58.470Z info: Attempt 59 to create SQLInstance
2021-11-25T20:52:13.577Z error: error during cluster creation (attempt 2):
Error: SQLInstance creation deadline hit after 60 attempts
```

**Expected behavior**

Setup should succeed

**Comment by jgehrcke** [comment]
Maybe mail the debug log file to jp@opstrace.com -- thank you!

**Comment by nagyv** [comment]
Thanks! I've sent the logs.

**Comment by nagyv** [comment]
Sorry for the false alarm. The logs helped me too. I needed to enable the Cloud SQL Admin API.
