### ISSUE TITLE
Concerns on an issue with transfer to Gitlab:  

### ISSUE THREAD

**Issue by Daasin** [opstrace/opstrace#1490]
**In the event that this repo were to become inactive**

_Should this not have all pull requests merged as of time this issue is posted, or to keep in sync with Gitlab repo as a mirror untill the current 11/12 Pull Requests have been dealt with? Permits current GitHub forks to have a final 'latest' snapshot of the source to work with_  

Like when all issues from #1326 to #1488 _or even up to until a #1500 has been merged_ if possible to allow people to make any adjustments they may need.

**Comment by triclambert** [comment]
Hi @Daasin.  Thanks for this issue.  Effectively, this repo is now read-only.  We merged #1488 prior to the migration.  The remaining open issues/PRs have been [imported into GitLab](https://gitlab.com/gitlab-org/opstrace/opstrace), and they can be followed up with there.  No work should be lost.  Does that ease your concern?

**Comment by Daasin** [comment]
> Hi @Daasin.  Thanks for this issue.  Effectively, this repo is now read-only.  We merged #1488 prior to the migration.  The remaining open issues/PRs have been [imported into GitLab](https://gitlab.com/gitlab-org/opstrace/opstrace), and they can be followed up with there.  No work should be lost.  Does that ease your concern?

@triclambert Unfortunately not :/ wasn't about the work itself but more the work on this repo for those that would want to fork and then have issues due to the remaining pull requests that wouldn't be completed here. 

Ofcourse I'm not saying that the Gitlab progress be manually replicated here in the exact same way since that would be asking you to deal with hassle unecessarily 

but merely asking that this allow to be kept in-sync automatically with the Gitlabs repo until that range of 11 (Or 12) outstanding pull requests are merged or otherwise dealt with via rejections or amendments. Hopefully I helped clarify things, my apologies for the confusion  😅

**Comment by triclambert** [comment]
@Daasin at this time, there's not enough demand for us to invest in [bidirectional syncing](https://docs.gitlab.com/ee/user/project/repository/mirror/bidirectional.html) of the repos. The repo at GitLab is still in Git, so it's accessible much the same way as it is on GitHub. We won't be publishing another release via GitHub, so either way you look at it, you'll need to interact with GitLab. While it's not the same as GitHub, it's also not bad. We hope you'll join us [there](https://gitlab.com/gitlab-org/opstrace/opstrace).  It's easy and free to join.  You can even sign in to GitLab.com using your GitHub account!
