### ISSUE TITLE
ci: waiting "for Certificate ingress/https-cert to be ready" didn't resolve

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#151]
https://github.com/opstrace/opstrace/issues/62#issuecomment-742631003
https://buildkite.com/opstrace/scheduled-main-builds/builds/1341#d4dae6f8-41a1-4b9f-acdb-03dd9c577f21/221-6770
logs should be in builds.ci.aws.opstrace.io
similar to / same as https://github.com/opstrace/opstrace/issues/60?

**Comment by jgehrcke** [comment]
@sreis did some debugging (thank youu!): https://github.com/opstrace/opstrace/issues/62#issuecomment-742692632

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/3303#c6de932f-fc48-47c1-9479-33ad90ef66f1/256-4965

**Comment by sreis** [comment]
Another two:

https://buildkite.com/opstrace/scheduled-main-builds/builds/1423#ed528871-96aa-4227-a288-9e484569c9ce/222-6871

https://buildkite.com/opstrace/scheduled-main-builds/builds/1424#00b2e157-d0c7-4920-877b-b49bfee98d51/222-6819

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1539#be79e5cf-b481-4338-be27-5758491b1236/221-6820

```
[2021-01-12T05:45:58Z] 2021-01-12T05:45:58.219Z debug:     Waiting for Certificate ingress/https-cert to be ready
[2021-01-12T05:46:02Z] 2021-01-12T05:46:02.179Z warning: cluster creation attempt timed out after 2400 seconds
[2021-01-12T05:46:02Z] 2021-01-12T05:46:02.179Z debug: do not log error detail
```

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1550#375db81d-0482-4057-86fc-6d99ccdf1359/221-6815

```
[2021-01-14T01:47:15Z] 2021-01-14T01:47:15.706Z warning: cluster creation attempt timed out after 2400 seconds
[2021-01-14T01:47:15Z] 2021-01-14T01:47:15.706Z debug: do not log error detail
[2021-01-14T01:47:15Z] 2021-01-14T01:47:15.706Z error: 3 attempt(s) failed. Stop retrying. Exit.
```

**Comment by sreis** [comment]
Also affected AWS build this time:

https://buildkite.com/opstrace/scheduled-main-builds/builds/1592

**Comment by jgehrcke** [comment]
gcp build failure: https://buildkite.com/opstrace/prs/builds/3458#d5a02628-1dca-4767-8682-e88874e1a04f/251-6546

**Comment by sreis** [comment]
This CI for the upgrades test was [experiencing this issue](https://buildkite.com/opstrace/upgrade-tests/builds/44#1a0aee48-4a0b-4d6c-b491-231c59417ad6/1241-7700). 

I poked around the cluster and noticed the certificate was in the `Failed` state.

```
Status:
  Conditions:
    Last Transition Time:  2021-01-25T12:13:59Z
    Message:               The certificate request has failed to complete and will be retried: Failed to wait for order resource "https-cert-2svxf-2719157038" to become ready: order is in "invalid" state: 
    Reason:                Failed
    Status:                False
    Type:                  Issuing
    Last Transition Time:  2021-01-25T12:09:55Z
    Message:               Issuing certificate as Secret does not contain a private key
    Reason:                MissingData
    Status:                False
    Type:                  Ready
  Last Failure Time:       2021-01-25T12:13:59Z
Events:
  Type     Reason     Age   From          Message
  ----     ------     ----  ----          -------
  Normal   Issuing    25m   cert-manager  Issuing certificate as Secret does not contain a private key
  Normal   Generated  25m   cert-manager  Stored new private key in temporary Secret resource "https-cert-prfv5"
  Normal   Requested  25m   cert-manager  Created new CertificateRequest resource "https-cert-2svxf"
  Warning  Failed     21m   cert-manager  The certificate request has failed to complete and will be retried: Failed to wait for order resource "https-cert-2svxf-2719157038" to become ready: order is in "invalid" state:
```

cert-manager logs showed:

```
E0125 12:13:59.437421       1 sync.go:356] cert-manager/controller/challenges/acceptChallenge "msg"="error waiting for authorization" "error"="acme: authorization error for default.bk-44-5e1-a.opstrace.io: 400 urn:ietf:params:acme:error:dns: During secondary validation: DNS problem: query timed out looking up TXT for _acme-challenge.default.bk-44-5e1-a.opstrace.io" "dnsName"="default.bk-44-5e1-a.opstrace.io" "resource_kind"="Challenge" "resource_name"="https-cert-2svxf-2719157038-1180366330" "resource_namespace"="ingress" "resource_version"="v1" "type"="DNS-01" 
I0125 12:13:59.599647       1 conditions.go:162] Found status change for Certificate "https-cert" condition "Issuing": "True" -> "False"; setting lastTransitionTime to 2021-01-25 12:13:59.599637194 +0000 UTC m=+244.458502337
I0125 12:13:59.631289       1 trigger_controller.go:162] cert-manager/controller/CertificateTrigger "msg"="Not re-issuing certificate as an attempt has been made in the last hour" "key"="ingress/https-cert" "retry_after"="2021-01-25T13:13:59Z"
E0125 12:13:59.642040       1 controller.go:158] cert-manager/controller/CertificateReadiness "msg"="re-queuing item  due to error processing" "error"="Operation cannot be fulfilled on certificates.cert-manager.io \"https-cert\": the object has been modified; please apply your changes to the latest version and try again" "key"="ingress/https-cert" 
I0125 12:13:59.693703       1 trigger_controller.go:162] cert-manager/controller/CertificateTrigger "msg"="Not re-issuing certificate as an attempt has been made in the last hour" "key"="ingress/https-cert" "retry_after"="2021-01-25T13:13:59Z"
E0125 12:14:02.212482       1 sync.go:356] cert-manager/controller/challenges/acceptChallenge "msg"="error waiting for authorization" "error"="acme: authorization error for system.bk-44-5e1-a.opstrace.io: 400 urn:ietf:params:acme:error:dns: During secondary validation: DNS problem: query timed out looking up TXT for _acme-challenge.system.bk-44-5e1-a.opstrace.io" "dnsName"="system.bk-44-5e1-a.opstrace.io" "resource_kind"="Challenge" "resource_name"="https-cert-2svxf-2719157038-451256671" "resource_namespace"="ingress" "resource_version"="v1" "type"="DNS-01" 
```

I proceeded to delete the certificate and waited for the controller to recreate it. This seemed to unblock things and the certificate was issued successfully.

```
> k -n ingress get certificaterequests.cert-manager.io                       
NAME                         READY   AGE
https-cert-msrdh             True    108s
kubed-apiserver-cert-r9fsh   True    30m
```

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/3464#ebe2102f-d93a-4e29-9d6e-af680fecc658/247-6419

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1681#311bae0a-4856-4e59-b3b3-881ffc942b27/232-6434

https://buildkite.com/opstrace/scheduled-main-builds/builds/1682#fd5d8bb6-fd27-4edc-b776-608482822718/6-5027

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/3494#57de5977-1f5d-4835-a1d0-367d1ece5dc3/248-6371

**Comment by triclambert** [comment]
Seems like both GCP and AWS are failing now, two scheduled builds in a row:

https://buildkite.com/opstrace/scheduled-main-builds/builds/1686
https://buildkite.com/opstrace/scheduled-main-builds/builds/1687

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/3498#9ced1671-e6eb-407d-b37c-a55a87fb3761/250-6425

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/3498#0dd3ab4d-8b9e-4535-9c39-0b05f3039fec/6-5043

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1688#75797e9c-9d60-44ae-b502-a60bf55c7371/232-5946

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/3495#21795803-90a6-463e-b085-4c01df9bf5bb/6-5213

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1689#cd4c7d66-5ad1-4250-88e9-9b44ff7d7f3a/234-6422

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1697#43f20eeb-f7be-4e4a-96db-ac6a2952fd26/232-6388

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1696#7c6bcc90-28c2-454b-a626-70c3b8ae1315/232-6412

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1695#0272c9a3-490f-4b8c-a580-5e1d9c853378/232-6397

**Comment by jgehrcke** [comment]
https://github.com/opstrace/opstrace/pull/346#issuecomment-776605463

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1805#0fd15300-058a-415b-822d-9396e43f9211/237-9565

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/3696#06f6ee84-afa1-4b94-b62b-70298a9f2d04/251-4838

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1846#a88047bd-b894-462b-9f5c-8e3a34123819/236-8940

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1847#a7d3adf4-291d-424e-a4da-b3e4c4fd7bc3/237-6074

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1853#bfb51fc4-988f-4aaf-b500-c2433ab964b3

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1852#383aeac3-ca90-49e0-87e7-935376d7b8a0/238-9107

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1855#97ce2000-88af-4e77-b4e8-81f356c5908f/237-9096

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1866#8613ab54-5304-450f-aa9e-2b5dd66b444a/236-9082

**Comment by jgehrcke** [comment]
Thanks for working on this @sreis!!

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/3736#2d26e81f-d9ce-44e7-9279-4da043750069/253-9037

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2049#71a8016e-a142-4291-b9c4-1dd40cd67571/238-8850

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2052#59b72f84-7ebd-4a96-b698-4d5cf554d00c/6-69

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2075#d089fc3d-a5bb-4b41-9c64-58c211ca10c8/239-8960

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2078#8e90e2e3-ddd8-43a5-a574-8bf3287a8618

**Comment by terrcin** [comment]
This is occuring for me with me dev cluster at the moment. 
```
kubectl get certificaterequest -n ingress
NAME                         READY   AGE
https-cert-j54c7             False   70m
kubed-apiserver-cert-zhfvc   True    70m
```

Is it ment to be issuing from `letsencrypt-staging`?

```
Status:
  Conditions:
    Last Transition Time:  2021-04-12T03:44:41Z
    Message:               Waiting on certificate issuance from order ingress/https-cert-j54c7-2531617703: "pending"
    Reason:                Pending
    Status:                False
    Type:                  Ready
```

**Comment by sreis** [comment]
> Is it ment to be issuing from letsencrypt-staging?

@terrcin Yes, if you have `cert_issuer: letsencrypt-staging` on your cluster config or you're using a CLI build before #545 was merged when the default was changed to `letsencrypt-prod`.

Can you attach the output of

```bash
kubectl get orders.acme.cert-manager.io -n ingress -o yaml
```

**Comment by terrcin** [comment]
Update: @sreis worked with me over a screenshare to track this down to probably my DNS configuration not being correctly cleaned up when destroying a cluster due to me running the script unattended and missing the auth check. Then when creating a cluster it looks to not being correctly handling the un-cleaned-up DNS configuration. In this case the GCP names servers were wrong, @sreis updated them and after waiting on dns propergation everything is running as expecting with certs being correctly issued.

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2100
https://buildkite.com/opstrace/scheduled-main-builds/builds/2101
https://buildkite.com/opstrace/upgrade-tests/builds/400
https://buildkite.com/opstrace/scheduled-main-builds/builds/2102

**Comment by sreis** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/2133#13a889f4-c939-401d-ad95-706b5d156286

This time the certificate was never ready but it also never failed. The ca-injector logs showed

```
E0419 10:25:59.916062 1 internal.go:521] cert-manager/controller-runtime/manager "msg"="error received after stop sequence was engaged" "error"="leader election lost"
```

There's an open issue https://github.com/jetstack/cert-manager/issues/2362 but for an old version of cert-manager. It suggests setting leader-election to false. It shouldn't hurt since we only deploy one replica.

**Comment by jgehrcke** [comment]
Thank you @sreis for making further progress on this one!

**Comment by sreis** [comment]
FTR, I checked CI logs, and no failed builds with this issue this past week, but I also didn't see any of the log messages I added in https://github.com/opstrace/opstrace/commit/5f0d1f6bb23bb0b12b924047081d1e5de818f963.

**Comment by jgehrcke** [comment]
closing this, let's have a deeper look at #842.
