### ISSUE TITLE
ci: docs-only: breaks with new unit-tests job

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#153]
https://buildkite.com/opstrace/prs/builds/3247#785b6fa5-7060-4180-ab8c-561474bfef85/192-193

a good docs-only PR failed in the new unit-tests job:
```
make cli-crashtest
[2020-12-10T19:56:27Z] ./build/bin/opstrace crashtest || exit 0 # so that the output is visible in build log
[2020-12-10T19:56:27Z] /bin/bash: ./build/bin/opstrace: No such file or directory
[2020-12-10T19:56:27Z] set +o pipefail && ./build/bin/opstrace crashtest 2>&1 | grep 'cli/src/index.ts:'
```

**Comment by jgehrcke** [comment]
Need this:
https://github.com/opstrace/opstrace/blob/7f4dd7c6e858fcf4cfa9979625ea841bf03c4247/ci/deploy-testremote-teardown.sh#L3
```
# Skip steps if it's a docs pr
bash ci/check-if-docs-pr.sh && exit 0
```

to run as the first thing in https://github.com/opstrace/opstrace/blob/7f4dd7c6e858fcf4cfa9979625ea841bf03c4247/Makefile#L574.

**Comment by jgehrcke** [comment]
Let's maybe create a `ci/uni-tests.sh` and start with
```
# Skip steps if it's a docs pr
bash ci/check-if-docs-pr.sh && exit 0
```

**Comment by sreis** [comment]
This would be way easier if we could skip the steps after `check-docs`... 

We can also call `ci/check-if-docs-pr.sh` in the buildkite pipeline explicitly so we don't forget next time? I'll leave it to you to decide, I'm fine with the approach you pick.

**Comment by jgehrcke** [comment]
> We can also call ci/check-if-docs-pr.sh in the buildkite pipeline explicitly so we don't forget next time?

Yes.. but I think in practice this is also a little ugly.

If we were to add this as a command to the command list within a job we would want a  "skip the rest" (the remaining commands in the commands list) behavior.

The only way to do that is I think to construct a single, chained command, i.e. to only have one item in the command list. And because that's ugly we have this logic in scripts. We could also put it into the Makefile, but... for pulling it into the pipeline file I have not really seen a nice solution. 

It would be nice if individual jobs could set pipeline variables that are available in subsequent jobs, and then a `skip if` behavior based on these custom variables could be implemented rather nicely. 



- want to run this in our CI container, so must invoke with

**Comment by sreis** [comment]
```bash
ci/check-if-docs-pr.sh || make <target>
```
maybe rename to skip-if-docs-pr.sh too?... but beauty is in the eye of the beholder, right? :)

**Comment by jgehrcke** [comment]
I think we can consider this resolved.
