### ISSUE TITLE
cli: error handling: axios.request() not `await`ed in dns client

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#187]
:fire: 
https://github.com/opstrace/opstrace/blob/62790b691f9ace4a6851ef95c1e8ca52f6e05dff/lib/dns/src/opstrace.ts#L161

It's unclear which problems this really produced (no direct evidence), but it is not unlikely that this is the root cause for https://github.com/opstrace/opstrace/issues/180.

**Comment by MatApple** [comment]
I don't think so. Since this is the return value of the function, it's fine so long as the callers await.
https://github.com/opstrace/opstrace/blob/f610692c86d0da1d16165c89c22d814594940523/lib/dns/src/index.ts#L117

**Comment by jgehrcke** [comment]
> I don't think so. Since this is the return value of the function, it's fine so long as the callers await.

Yeah. Should be fine, right?

> A quick check reveals the callers handle this correctly (they would blow up reliably if they didn't).

I thought the same... can you say what you did / how you checked?

I wanted to properly validate this hypothesis, too. I was therefore working on a minimal working example (MWE) and in simple cases I saw that `yield call()` waited for the dangling promise to resolve.

However, in the context of the AWS uninstall there is quite a bit of complexity involved that probably has to be reflected in the MWE in order to show the problem in a reproducible way, if there is one. That complexity has to do with using concurrent task groups managed via the `fork()` effect and special cases around process termination. We know that _despite_ the fact that the code seemingly looks OK there are challenges around _waiting for all tasks to finish_ before doing proper process shutdown, also see https://github.com/opstrace/opstrace/issues/198.

I concluded that creating the MWE was too much effort. And concluded that this lack of clarity in how the code is _supposed to behave_ is absolutely worth addressing; even if there is no underlying technical problem.

For the patch, I was stressing the last part of this sentence:

> Likewise, any corresponding axios error corresponding with this dangling task would be **thrown in the context of things that are difficult see through**.

The complexity argument above (in the context of AWS uninstall) is by the way corroborated by the fact that among those entries that unexpectedly accumulated in the DNS service there were 11 for AWS clusters vs. just 1 for a GCP cluster.
