### ISSUE TITLE
controller OOM-killed N times in cluster; cluster never became healthy

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#21]
Carrying over main findings from https://github.com/opstrace/opstrace-prelaunch/issues/1840.

@triclambert reported that the cluster never became healthy.
@sreis found that the controller was OOM-killed, 4 times: https://github.com/opstrace/opstrace-prelaunch/issues/1840#issuecomment-722553747

We did not root-cause this, and as far as I understand we have no reason to believe this is fixed -- situation may happen again.

Might relate to
https://github.com/opstrace/opstrace-prelaunch/issues/1089
https://github.com/opstrace/opstrace-prelaunch/issues/1089#issuecomment-668786259
https://github.com/kubernetes-client/javascript/issues/494

**Comment by sreis** [comment]
After #444 we no longer see the opstrace-controller leaking memory and getting oom killed.

![Screenshot from 2021-03-08 09-45-46](https://user-images.githubusercontent.com/495294/110311384-3b15d880-7ff3-11eb-87eb-254d4e8be63b.png)

In blue is the behavior before the opstrace-controller upgrade. In green is the opstrace-controller running with the new version of client-node.

**Comment by jgehrcke** [comment]
Super nice. Glad we're leaving this behind us.
