### ISSUE TITLE
UI Release

### ISSUE THREAD

**Issue by MatApple** [opstrace/opstrace#225]

**Comment by opstracy** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Create system module for Chart #1311](https://github.com/opstrace/opstrace-prelaunch/issues/1311) | Post-Launch 🚀💼 | MatApple | Open


###### do-not-edit-end-codetree-epic-issues
