### ISSUE TITLE
cli: store cluster state in directory (or single-file container)

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#237]
- log files
- opstrace DNS service credentials
- what else?

Use a convention to translate the cluster name an provider to the path (of directory or single-file container).

That would make it easier to switch between clusters.

There may be downsides, too.

Notes:
- thought often times: cluster name should be in the log file names
- credential files need to have more expressive names, be hidden, and/or otherwise consolidated (only one of both should be needed)

This is brainstorm level.

**Comment by jgehrcke** [comment]
affects tenant API tokens, of course

**Comment by sreis** [comment]
A couple of questions to understand what you're trying to achieve.

> store cluster state in directory

In a way, we are already doing this. But you are proposing the target directory wouldn't be the current working dir?

> Use a convention to translate the cluster name an provider to the path (of directory or single-file container).

How would this work in practice, for example, for a user that wants cluster A in GCP and cluster B in AWS? What happens if the user runs the CLI first with `/home/user/Downloads` and then `/home/user/foo` as current working directories?

**Comment by triclambert** [comment]
Some additional thoughts...

* Configuration file
* kubeconfig.conf
* Downloaded YAML from one of our integrations
* Ancillary workload or configuration files

> How would this work in practice...

Download the CLI twice, once in each directory.  Inelegant, but practical.  (CLI management/versioning is probably something we should talk about in the future.)

**Comment by jgehrcke** [comment]
> But you are proposing the target directory wouldn't be the current working dir?

Yes, right. Could encode the instance name in the directory, and then put all files into that directory (tenant API authentication tokens, and also DNS service authentication state).

> How would this work in practice, for example, for a user that wants cluster A in GCP and cluster B in AWS? What happens if the user runs the CLI first with /home/user/Downloads and then /home/user/foo as current working directories

Oh, to keep things simple that state directory would still be stored _relative to CWD_. That is, when I do

```
cd /home/jp
./opstrace create aws powerinstance ..
```
I will get a directory  `/home/jp/opstrace-powerinstance` and when I do 

```
cd /home/user/Downloads
./opstrace create gcp powerinstance ..
```
I will get a directory  `/home/user/Downloads/opstrace-powerinstance`

**Comment by Yasumoto** [comment]
Some decent prior art:

1. I generally find how `terraform` handles [this to be relatively graceful](https://www.terraform.io/docs/language/settings/index.html#specifying-a-required-terraform-version). I have `~/workspace/bin` setup with a few tools (like the `aws` CLI, `terraform`, etc). When a new tf version releases, I move the old binary to something like `terraform-0.14.2` so it's still in `$PATH` and I can use the correct tool version for the right workspace.

2. The `aws` credentials flow uses a standard location but also allows [to swap between profiles](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html), which is nice. There are also standards for environment variables too, which makes it simple to override the profile or creds, which is very helpful.

    Pulling the creds out of the `cwd` of the cluster config does split out the locations to check things, but `$XDG_CONFIG_HOME` is a standard, after all, and we'd never want to accidentally check in the creds.
