### ISSUE TITLE
review cluster name length limitation (13 chars right now)

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#24]
The Opstrace cluster name is used in contexts that impose limitations on length and character set.

Historically, that's how we ended up with current cluster name limitations.

https://github.com/opstrace/opstrace/blob/7b6b7f589f069c53357be3a83be36e459998b6d1/packages/cli/src/util.ts#L25

Some of these limitations go back to infrastructure components that we don't use anymore, such as Bigtable. See this commit: https://github.com/opstrace/opstrace/commit/b1ea161f62d3be3a30fbea0c00a435f999aac3fe

```
  // const infraNamePrefix = getInfrastructureName(stack.org, stack.name);
  // return `${infraNamePrefix}-idx`;
  // Note that the derived Bigtable instance cluster ID must not get longer
  // than 30 chars.
  return `${stack.name}-idxdb`;
};
```

TODO: play with this, see which length limitation is as of 'today' still justified. Then adjust the limit.

**Comment by jgehrcke** [comment]
@triclambert what are your findings?

**Comment by triclambert** [comment]
I have not yet had time to investigate.  I will report back when I do.

**Comment by jgehrcke** [comment]
Investigation work and changes can be found in https://github.com/opstrace/opstrace/pull/423.

**Comment by jgehrcke** [comment]
The new cluster name length constraint is 23 (max length). Has been tested in https://github.com/opstrace/opstrace/pull/423.
