### ISSUE TITLE
reduce default instance size everywhere

### ISSUE THREAD

**Issue by triclambert** [opstrace/opstrace#262]
GCP already uses a 4-core configuration by default.  Let's make AWS match, using `t3.xlarge` instead of `t3.2xlarge`.

**Comment by jgehrcke** [comment]
And with "everywhere" we mean: change the default value in the `aws` cluster config parameter.
That default is used by CI (as of today).
Using that in CI, I suppose, is one of the actual goals here -- to save some cost/credits.
