### ISSUE TITLE
ci: aws: quota reached for elastic IP addresses

### ISSUE THREAD

**Issue by triclambert** [opstrace/opstrace#270]
Looks like we hit #71 again.  Several clusters I know I destroyed a while ago have stranded resources.  

Offending build:  https://buildkite.com/opstrace/scheduled-main-builds/builds/1589#9e9ce499-c6e0-4ecd-89e7-13cb7ca6b0c2

![image](https://user-images.githubusercontent.com/19239758/105098102-70279500-5a5e-11eb-8637-f62a0317614b.png)

**Comment by triclambert** [comment]
I deleted the NATGateway and then the VPC for `fossa-demo` and `saturn`.

While trying to destroy the previously-destroyed cluster `c001`, I got:
```
2021-01-19T22:27:37.318Z info: vpc teardown: tryDestroy(): ignore aws api error: DependencyViolation: The vpc 'vpc-0455fb68ffc0b0dd2' has dependencies and cannot be deleted. (HTTP status code: 400)
```

I deleted the VPC manually. 

I am currently destroying `c002` with our CLI.

I have requested an increased quota for "EC2-VPC Elastic IPs" from a limit of 15 up to 30.

**Comment by jgehrcke** [comment]
Running three destroys:

```
$ ./opstrace destroy aws bk-1588-092-a --region us-west-2

$ ./opstrace destroy aws bk-1594-3a3-a --region us-west-2

$ ./opstrace destroy aws bk-3355-f51-a --region us-west-2
```

**Comment by jgehrcke** [comment]
>  I got:
> 2021-01-19T22:27:37.318Z info: vpc teardown: tryDestroy(): ignore aws api error: DependencyViolation: The vpc 'vpc-0455fb68ffc0b0dd2' has dependencies and cannot be deleted. (HTTP status code: 400)

That is not per se bad. Can you share the entire debug log of that destroy operation?

**Comment by jgehrcke** [comment]
> I deleted the NATGateway and then the VPC for fossa-demo and saturn

Did you do that with `./opstrace destroy aws fossa-demo --region us-west-2`? if not: why not? :)

**Comment by jgehrcke** [comment]
last time we also 

> released some addresses manually

see https://github.com/opstrace/opstrace/issues/71#issuecomment-737193451

doing that now.

![Screenshot from 2021-01-20 15-18-39](https://user-images.githubusercontent.com/265630/105187275-e4336d00-5b32-11eb-8367-a0c3835597aa.png)
![Screenshot from 2021-01-20 15-18-56](https://user-images.githubusercontent.com/265630/105187277-e5649a00-5b32-11eb-87a9-aa3b5743b72c.png)

**Comment by triclambert** [comment]
> Did you do that with ./opstrace destroy aws fossa-demo --region us-west-2? if not: why not? :)

I did not, I guess because I had done that before.  In the case of the `saturn` cluster, I had done it several times to no avail.  (I think I talked to @sreis about it at the time, and he suggested doing exactly what you suggested, so I did it yet again.)

In the end, I only cleaned up a couple of the ones I knew about (and released their addresses) as a very temporary stopgap.  

Probably the title of this issue should be 'clean up stranded elastic IPs' or something like that, rather than trying to troubleshoot how we got into this situation.

**Comment by jgehrcke** [comment]
Thanks for the response, Chris. Makes sense!

> Probably the title of this issue should be 'clean up stranded elastic IPs' or something like that, rather than trying to troubleshoot how we got into this situation.

Yes! :) In spirit of that: pressure is off, can close this.
