### ISSUE TITLE
DNS service: do not use 429 response for 'quota reached', but a 400 response

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#30]
Got a 429 error from the DNS service in CI: https://github.com/opstrace/opstrace-prelaunch/issues/2035

No further detail in the log (no response body, in particular), so the error stayed mysterious for the moment. Improving that is now tracked in https://github.com/opstrace/opstrace/issues/2034.

I wondered why / how we would breach an HTTP request limit... then I went into the DNS service code and realized that 

https://github.com/opstrace/opstrace/blob/025fc0a3b3e405be5597d45c5128831ea3eb52a3/packages/dns-service/src/controllers/dns.ts#L55

Then I remembered that we had been talking about that. Did a bit of digging, here I was suggesting to not use a 429 response for that, but a 400 response:

See https://github.com/opstrace/opstrace-prelaunch/issues/1552#issuecomment-713424784

> Let's use 429 only for an actual HTTP request rate limit.
> For quota/limits I suggest using 400 responses:
> AWS VpcLimitExceeded example: #1459
> AWS TooManyBuckets example: #1323

(there was no reply about that in #1552).

Still very much my opinion :).

**Comment by triclambert** [comment]
+1 for not using 429.
