### ISSUE TITLE
proposal: If certificate is in failed state then proceed to delete it and then recreate

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#301]
## Current Behavior / Proposed Behavior

To tackle cert-manager issues like #151, #60, #172, we can delete the certificate when it reaches a `Failed` state. We can start by only deleting in some known `Failed` states like described in [this comment](https://github.com/opstrace/opstrace/issues/151#issuecomment-766791674).

## Context

We are seeing certificate not ready errors in CI runs, which prevent the cluster from being successfully created.

## Possible Technical Solution

When waiting for the certificate to be ready, the controller can check if it's in a known failed state and proceed to delete it as well as any `CertificateRequests` that it created. The resync loop will recreate the certificate, which will trigger the request to be reissued.

**Comment by jgehrcke** [comment]
Cool, let's do this, https://github.com/opstrace/opstrace/issues/151 is one of the most frequently occurring CI instabilities these days.

**Comment by sreis** [comment]
Caught this [CI run](https://buildkite.com/opstrace/prs/builds/3478#39fba8cf-eb60-4ae0-9956-2fad6d19add2/256-4819
) with the same issue and deleting the `Certificate` and `CertificateRequest` unblocked it.

**Comment by sreis** [comment]
I took a stab at implementing this workaround and pushed it to the `sreis/workaround-issue-151` branch. Been running tests in CI but haven't been able to trigger #151.

**Comment by sreis** [comment]
The issue has not occurred in some time now. I'll pause any further work until it starts reoccurring in CI again.

**Comment by MatApple** [comment]
Happened again here https://github.com/opstrace/opstrace/issues/172

**Comment by MatApple** [comment]
Seems this occurs more frequently again

**Comment by MatApple** [comment]
Again https://buildkite.com/opstrace/prs/builds/3615#dbccd7bf-dea1-4471-91b9-13422145d20f

**Comment by MatApple** [comment]
Also here on AWS https://buildkite.com/opstrace/prs/builds/3615#bb22471b-1d45-442d-878c-079284b65d1c

**Comment by sreis** [comment]
Implemented in #557
