### ISSUE TITLE
Collect metrics and logs from CloudWatch and Stackdriver

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#310]
There are many interesting metrics that existing only in cloud vendors' own metrics system. We should be able to ingest those (with an allowlist) into Opstrace.

Details TBD.

**Comment by opstracy** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Read cloudwatch/stackdriver exporter docs, get running locally #311](https://github.com/opstrace/opstrace/issues/311) | N/A | nickbp | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by nickbp** [comment]
Quick update:
- The graphql interface and associated golang service for accepting YAML payloads are "complete" but not merged into main yet (#314). This included a lot of initial investigative work around getting golang code to interact with graphql. There were some issues with the graphql code generator we're using but they had an easy temporary workaround. In the meantime it should be relatively straightforward to add more golang<->graphql interaction in the future.
- Next up is getting the controller to subscribe to the credentials/exporters tables and automatically syncing changes to K8s, and then ensuring that prometheus/cortex is able to find/scrape the exporters (#312).

**Comment by nickbp** [comment]
The main implementation was completed via #403. A user should be able to invoke the Go HTTP API to add/update/delete credentials/exporters, where the controller deploys them automatically to K8s. In manual testing, I was able to see exported metrics appearing in cortex.

Some loose ends are broken out into separate tickets, and may tie into the UI config interface when it's being implemented:
- #358: User/admin facing documentation for using curl (can derive from the current go/cmd/config/README.md)
- #373: Using Hasura Actions for running the Go config validation code on behalf of the UI
