### ISSUE TITLE
Upgrades: Phase 1

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#323]
Upgrades proposal document: https://docs.google.com/document/d/1_iJJAASFYt4xdkprkmEkjSMEFX2_PfLrFSyKDnSC1Ag/

**Comment by opstracy** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Discuss design proposal #324](https://github.com/opstrace/opstrace/issues/324) | Sprint: Week 05 (2021) | jgehrcke, MatApple, nickbp, spahl, sreis, triclambert | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by nickbp** [comment]
All the tasks in this epic are finished so I assume this is finished too
