### ISSUE TITLE
UI: Add validation to Tenant name as it's used in subdomain names and uri's

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#350]
## Current Behavior / Proposed Behavior

Currently there is no validation performed on user entered Tenant names and this is used in the URL for navigating around the UI and also as a subdomain for accessing Grafana. Users can include invalid chars.

## Context

Sufficiently invalid Tenant names can prevent the user from going to the associated url. For example:

```
https://terrcin.opstrace.io/cluster/tenants/foo bar
https://foo bar.terrcin.opstrace.io

https://terrcin.opstrace.io/cluster/tenants/potato: #$%^&*/
https://potato: #$%^&*/.terrcin.opstrace.io
```

A malicious actor might even be able to redirect the user elsewhere with a cleverly crafted Tenant name??

## Possible Technical Solution

Two options string to mind:

1. validate the Tenant name as [valid for a domain name](https://en.wikipedia.org/wiki/Domain_Name_System#Domain_name_syntax,_internationalization). 
2. have two fields for a Tenant - a display name and a code (with the above validation) that used in the uri and as a subdomain

**Comment by jgehrcke** [comment]
Also affects cluster configuration concept, i.e. the installer CLI.

I think we should do (1) for starters, using a regular expression that's shared between CLI and UI.

**Comment by terrcin** [comment]
@jgehrcke I've created a UI updating PR with regex validation on the Tenant name just to stop this being an issue. Not sure about the CLI.

```
/^(?!-)[A-Za-z0-9-]{1,63}(?<!-)$/
```

Ultimately I think that having a seperate `code` generated off the Tenant name but user editable is the way to go longer term. Or something to that effect.
