### ISSUE TITLE
Write guide for adding credentials and configuring/deploying exporters

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#358]
Write a guide covering:
- (brief, ideally external link) Getting credentials from AWS/GCP
- Adding those credentials into opstrace via curl
- Adding stackdriver/cloudwatch exporters into opstrace via curl, using a basic config example
- Observing the metrics appearing in opstrace

**Comment by triclambert** [comment]
Should this be a user guide or an administrator guide?

**Comment by nickbp** [comment]
I'm thinking it'd fall under administrator guides, since it'd mainly be about configuring retrieving metrics from other running systems.

But this assumes that a "user guide" would mainly be about building dashboards etc against metrics that are already being collected.

**Comment by nickbp** [comment]
WIP: https://docs.google.com/document/d/1DW2uRwLBkaDFhw81yfo3EC1aW40_oTCii_kKUQDqBZE/edit?usp=sharing
