### ISSUE TITLE
CLI create fails in wsl2

### ISSUE THREAD

**Issue by moenzuel** [opstrace/opstrace#372]
**Describe the bug**
Following the quick start guide and attempting to run `./opstrace create aws` leads to an error from what I believe is an attempt to open a browser window

Error given is:
`.....`
`Error: spawn WSL Interopability is disabled. Please enable it before using WSL.`
`C:/WINDOWS/System32/WindowsPowerShell/v1.0/powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**To Reproduce**
1. WSL2 running Ubuntu
2. Setup aws account for aws cli
2. Follow the linux quick start guide found at https://opstrace.com/docs/quickstart
3. Attempt `./opstrace create aws` as listed in guide

**Expected behavior**
If no browser window can be opened still allow manual opening of the url.

**Comment by spahl** [comment]
Hi, thank you for the report. This is weird, the case should be handled and end up showing the URL gracefully. See https://github.com/opstrace/opstrace/blob/cfe72b9b4d6887a288652b1dc52d86a5f5c1e7bd/lib/dns/src/opstrace.ts#L177

But then again, anything is possible. Could you provide the entire stack trace if possible, the extract it unfortunately is not enough to narrow it down.

Thanks!

**Comment by moenzuel** [comment]
I spent some more time trying to resolve `spawn WSL Interopability is disabled. Please enable it before using WSL.` and I think it was related to the `update-binfmts` ubuntu package and possibly the fact that I run the awscli via docker. I followed the manual restart found at https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1555760 and it seemed to then allow the opstrace create to continue.

The above error is everything related to the error that was outputted even with debug output enabled. Though if you are try-catching it is indeed wild that this error blew up node completely.

**Comment by jgehrcke** [comment]
Thanks for getting back at us so quickly @moenzuel. 

> The above error is everything related to the error that was outputted even with debug output enabled. Though if you are try-catching it is indeed wild that this error blew up node completely.

Would you mind sharing the complete terminal output of a crashing `./opstrace create aws` invocation with us so that we can have another look? I trust that you came to the right conclusion, but I'd really love to see with my own eyes how stderr and stdout evolved here. If you feel like there's too much personal/sensitive information in the output, feel free to share with jp@opstrace.com -- thank you!

**Comment by moenzuel** [comment]
I unfortunately have been unable to roll back my system and reproduce the exact same error.

**Comment by jgehrcke** [comment]
@moenzuel ok, and thanks for getting back at us!
