### ISSUE TITLE
cli: add command that allows for generating new data API authentication tokens

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#391]
Add option to read the private key from local file system.
If private key is not provided: generate a new key pair.
Add option to persist the private key (local file system).

The corresponding public key can then be injected into the cluster w/o invalidating previously issued authentication tokens; but that requires building https://github.com/opstrace/opstrace/issues/390 first.

**Comment by jgehrcke** [comment]
More work: https://github.com/opstrace/opstrace/pull/582

**Comment by triclambert** [comment]
I think we can call this closed after #582.
