### ISSUE TITLE
pragmatic "add new tenant" story w/ issuing data API authentication token

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#392]
Need these ingredients:

- Add tenant functionally, via UI (works today) or CLI (https://github.com/opstrace/opstrace/issues/22)
- Have data API authenticator be prepared for more than one public key: https://github.com/opstrace/opstrace/issues/390
- Cli: add command that allows for generating new data API authentication tokens https://github.com/opstrace/opstrace/issues/391

Prior art:
https://github.com/opstrace/opstrace/commit/daf25cbe8671ee670c92addd12b106dea7d3ec14#diff-699aaa125365c56e58b9d28702bfde728785ce37284ef084e0f4ff36827d890c

**Comment by jgehrcke** [comment]
Question was about being able to basically CRUD data API authentication tokens.

> We need a way to rotate/create/delete/view. @jp thoughts?

My response from Slack, here for the record:

We can have a way to add/delete public keys to the authenticator. Adding support for that in the authenticator is briefly captured by https://github.com/opstrace/opstrace/issues/390.

Managing (public) keys via the/a UI is not yet captured by any ticket, but would be the obvious extension of that idea, and is something we should do! Will be quite nice, actually.

Creating key pairs and deriving new tokens from a specific private key is something that the CLI should do -- tracked here: https://github.com/opstrace/opstrace/issues/391

We can never have a way to view issued ('currently valid') tokens. That's conceptually impossible. PKI / "client-side sessions" has/have strengths and weaknesses; this is a weakness.

"Server side sessions" allow for listing sessions, and securely invalidating individual sessions. The session state is defined in a specific database, which is the source of truth.

"Client side sessions" (based on PKI) do not allow for listing and securely invalidating individual sessions. The session state's source of truth is the 'soup of tokens out there in the wild'. Any attempt to keep track in a central place is error-prone.

**Comment by MatApple** [comment]
> Managing (public) keys via the/a UI is not yet captured by any ticket, but would be the obvious extension of that idea, and is something we should do! Will be quite nice, actually.

@jgehrcke feel free to sketch some rough UX for this and I'll put that into Figma.

**Comment by jgehrcke** [comment]
https://github.com/opstrace/opstrace/blob/726e305d557a71bb0fa63d7b238b1256a4a450bd/packages/cli/src/index.ts#L261

```
  // About those next two args: that's just brainstorm, maybe do not build
  // that... Maybe _always_ drop that private key. maybe only provide one
  // qualified method that involves: generating a new keypair, configuring the
  // authenticator with the pub key, and then creating new authentication
  // tokens with the priv key

  // parserCreate.add_argument("--tenant-api-authenticator-privkey-file", {
  //   help:
  //     "Instead of generating a fresh RSA key pair, use this private key to " +
  //     "sign tenant API authentication tokens. " +
  //     "Extract public key and configure authenticator with it. File path " +
  //     "must point to a PEM RSA private key file using the " +
  //     "PKCS#8 (RFC 3447) serialization format. (experimental, noop)",
  //   type: "str",
  //   metavar: "PATH",
  //   dest: "tenantApiAuthenticatorPrivkeyFilepath",
  //   default: ""
  // });

  // parserCreate.add_argument("--write-tenant-api-authenticator-privkey", {
  //   help:
  //     "Write the RSA private key used for signing tenant API authentication " +
  //     "tokens to this file. If not specified, the private key is dropped and " +
  //     "lost. The private key is written to a PEM file using using the " +
  //     "PKCS#8 (RFC 3447) serialization format. (experimental, noop)",
  //   type: "str",
  //   metavar: "PATH",
  //   dest: "tenantApiAuthenticatorPrivkeyFilepath",
  //   default: ""
  // });
```

**Comment by vjrngn** [comment]
Hi folks, I heard about opstrace on the SE Daily podcast and it piqued my interest. I'd like to contribute to the project and pick this issue as my first.

**Comment by spahl** [comment]
@vjrngn and I started chatting in the community slack to get started about how to join as a contributor. Here is the link for others: https://join.slack.com/t/opstrace-community/shared_invite/zt-ol8v4zpc-qy2CutVePuA71prfQ_fqcw (will be posted on the website/readme)

**Comment by jgehrcke** [comment]
we got a story: https://opstrace.com/blog/introducing-dynamic-tenant-addition-and-token-management
