### ISSUE TITLE
Opstrace Agent + simplified metric/log/trace collection management

### ISSUE THREAD

**Issue by MatApple** [opstrace/opstrace#429]
Develop an agent for collecting metrics, logs and traces. This agent can be comprised of other existing agents, but the goal is to simplify configuration and management.

## Current Behavior
A user has to choose an existing agent (Promtail, Fluentd, Fluentbit, Vector, Prometheus, Datadog, etc) to collect their metrics and logs. All of these require a great deal of configuration that must be done correctly in order to work with the authenticated Opstrace data APIs. There is a great deal of pain here for users, since they have to mostly deal with this on their own since they are most familiar with the environment they are monitoring.

## Proposed Behavior
Develop an Opstrace agent that can be configured and managed remotely from the Opstrace instance for which it is going to send data. Through the Opstrace UI, a user would be presented a simple URL which they could use to install the agent in their environment. Once running, the agent would call into the Opstrace instance and register itself. From there, it can be configured with a live reloading mechanism. This would allow for the following type of benefits:
* Configure the agent live, results in a much improved config/test/validation cycle
* The agent could automatically send contextual info from its environment that would help configure it correctly. For example, the Opstrace UI could request a list of services/pods from an agent that is running in a Kubernetes cluster, and then provide a checkbox next to each option in the UI so the user simply has to select which services/pods they would like the agent to scrape. The agent would then configure itself accordingly.
* To control the relabelling process more carefully.
* Turn off collection of metrics/logs that are not wanted (more efficient to never send than to filter on the ingestion end)
* Pause/buffer data during certain upgrades and resume with a greater level of control (slowly ramp back up for example and control the buffer window)
* Gain additional insights that can help identify Instance scale requirements (can carefully monitor symptoms like hitting ratelimits too frequently, local buffer growing, etc)

## Possible Technical Solution
Wrap some existing agents (logs, metrics, traces, eBPF) with a live-reloading config management interface that connects through a socket to the Opstrace Instance/UI.

## Alternatives Considered
N/A

**Comment by MatApple** [comment]
@spahl @sreis @jgehrcke @nickbp @terrcin @triclambert

**Comment by jgehrcke** [comment]
Thanks @MatApple this sounds like a valuable direction.

I want to add: the software running local to the source of metrics/logs (the "agent") _is part of the system_, and therefore contributes to defining the robustness properties of the system.

It therefore needs to behave in a certain way in view of errors when the goal is that the complete system lives up to certain robustness expectations. That is, we need to either be in control of the agent or we need to rely on another party to configure things according to a specification that we create. The former is clearly the better option.

We have to specify correct behavior in view of errors, adjusted to the actual Opstrace system (pusher and to-be-pushed-to-thing need be tuned). This includes, for logs, metrics, ... separately:
- whether or not the node-local buffer should persist unflushed data on disk, or only in memory
- how exactly individual push requests are to be retried in view of which failures

The details must be derived from higher-level robustness goals. Let's start with answering the following questions:

- Is an agent crash allowed to result in significant data loss (if it holds unflushed data in memory, this can easily happen)?
- If the agent buffers unflushed data on local disk: what's the upper limit, starting from which it's OK to drop data (ballpark.. 10 MB, 1 GB, 100 GB)?
- If the to-be-pushed-to system is not available for a longer period of time: is there an upper limit to the _age_ of unflushed data before it is supposed to be dropped by the agent?

**Comment by MatApple** [comment]
All good questions! I'd take some inspiration from other collectors like Fluentd, Prometheus, Promtail to get an initial starting point from which we can learn and tune under tests
