### ISSUE TITLE
ci-instability: unit tests failed on copyfile

### ISSUE THREAD

**Issue by triclambert** [opstrace/opstrace#440]
* **Test Name**:

Unit tests step failed unexpectedly on #437.

* **Console Output:**

```
error An unexpected error occurred: "ENOENT: no such file or directory, copyfile '/build/.cache/yarn/v6/npm-@auth0-auth0-react-1.3.0-f449c0abca2cb8f0fba0d1919a25685bcc90b925-integrity/node_modules/@auth0/auth0-react/CHANGELOG.md' -> '/build/node_modules/@auth0/auth0-react/CHANGELOG.md'".
```
* **Build Links**:

https://buildkite.com/opstrace/prs/builds/3700#6d84f9e3-b0f4-43ed-8096-83b205ac61c8/85-237

**Comment by jgehrcke** [comment]
merged with https://github.com/opstrace/opstrace/issues/439.
