### ISSUE TITLE
CLI: add cluster-info command

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#454]
## Current Behavior / Proposed Behavior

The CLI version flag only prints the CLI installer version. 

```bash
$ opstrace --version 
   Version vX.Y.Z (CLI installer version)
```

When upgrading the Opstracer controller with the current work-in-progress `upgrade` command, the installer and controller versions will diverge. We need a way to show this information to the user.

```bash
$ opstrace cluster-info CLOUD_PROVIDER CLUSTER_NAME
   cluster/infra: version A.B.C
   controller: version X.Y.Z
   installer: version A.B.C
```

## Context

Cluster or infra version refers to all the components not created by the opstrace-controller, for example, the cloud instances, the VPC, and the Kubernetes cluster.

The installer version refers to the Opstrace CLI the user downloads and executes to run commands.

Controller version refers to the Docker image tag used in the Opstrace controller deployment installed in the Kubernetes cluster.

## Possible Technical Solution

Add cluster/infra (CLI version that created the cluster infrastructure) and controller version in the controller config map. Add version subcommand to print cluster/infra version, controller version, and installer CLI version.

**Comment by jgehrcke** [comment]
Which alternatives to `cluster-info` did we consider? Just `info`?

Side note about

> The CLI version flag only prints the CLI installer version.

I think we should call this "the CLI version". Which implies the "installer version", if we wish to think of it that way :).

**Comment by jgehrcke** [comment]
Just doing a bit of specification brainstorming here.

> controller: version X.Y.Z

That's easy: the version of the _currently running controller_. Yes?

> installer: version A.B.C

The version of the CLI (and, with that, installer) that was used to 
1. create the cluster in the first place?
2. execute the last `upgrade` command?

> cluster/infra: version A.B.C

- k8s version
- what else?
