### ISSUE TITLE
Release cadence and strategy

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#455]
## Current Behavior / Proposed Behavior

The current upgrade test only covers upgrades between the last two main versions. As discussed in a previous meeting, this is not enough. 

What was agreed was to introduce a weekly release cadence:

1. Tag main (version scheme to be discussed separately)
2. During the week, test upgrades against the previous tag
3. Upgrade all managed customers

To achieve monthly releases by:
1. Create a branch from main
2. Branch name is YEAR.MONTH

@jgehrcke came up with an [alternative in](https://github.com/opstrace/opstrace/issues/450#issuecomment-791965299) a separate issue #450 to address short term requirements, quoting:

>Maybe a pragmatic approach here is the following:
> * We should always assume that an upgrade from wherever to current main is broken.
> * We may then, ad-hoc, make it our goal that an upgrade from a specific commit to another specific commit (the target commit) should work. We can then set out and make it work, assuming that this requires extra work, i.e. assuming it currently does not work. That is, the target commit will after all not be the actual target commit. It's that, plus only those changes that are required to make the upgrade work. An obvious method to do this w/o slowing down merges to main is to put the required patches into a branch.

> I think we can and should take the more heavy-weight "releases" topic out of the upgrade discussion again for now. We will simply set the goal "now, let's make a build, that we can upgrade to" (for the current high-prio SM target environment), and then do the necessary testing and patching work (in a branch).

**Comment by triclambert** [comment]
Moving this back to "unscheduled" from "backlog," as we don't currently have an intent to start on this right now.

**Comment by jgehrcke** [comment]
good thinking in here, and we're putting some things into action. more specific tasks: more specific tickets.
