### ISSUE TITLE
cortex api proxy: transparently rewrite 429 responses to requests to api/v1/push

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#464]
In view of https://github.com/prometheus/prometheus/issues/8418 any pusher Prometheus drops data when Cortex responds with 429 responses. 

A pragmatic way to have a pusher Prometheus retry is to emit a 503 response instead.

We can implement this rather easily in our Cortex API proxy.

**Comment by jgehrcke** [comment]
this is initially done after https://github.com/opstrace/opstrace/pull/471 landed.

**Comment by jgehrcke** [comment]
Note that https://github.com/prometheus/prometheus/pull/8237/files landed, but there does not seem to be a Prom release yet with this patch. Probably coming soon.

When this release is there, this work here can be looked at as a strategy to support older pusher Prom versions.

**Comment by jgehrcke** [comment]
> this is initially done after #471 landed.

landed, closing for now!

**Comment by spahl** [comment]
Awesome! Please write a small blog post about the fact that we did this and our motivations why:-)
