### ISSUE TITLE
Implement "don't touch" annotation or label for K8s objects

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#467]
This idea came from an earlier discussion around productionization. At the moment any changes to the cluster require shutting off the controller, since it'll automatically squash/replace those changes with its desired state if it's left online. As a workaround, it'd be useful to have some kind of label or annotation that can be added to objects which will tell the controller to ignore them.

This could be used in a few ways:
- Adding custom objects to the cluster that are not managed by the controller, and should not be automatically deleted by the controller. This would probably mainly be for testing (e.g. I was thinking of deploying hasura console directly into test clusters occasionally)
- Making custom modifications to existing objects that should be left as-is by the controller while the annotation is present. This may be to resolve a production issue, where the label/annotation is effectively an "escape hatch" that allows working behind the controller.

As an optional extra, the controller could log a message periodically that says "I would perform action X against object Y, but am not because the object is labeled 'dont touch'". This may help in the scenario where we make some changes, then finish with them, but forget to unlabel the objects when finished.

When discussing this with Mat, he recommended looking at the existing handling around `setImmutable()` in the controller code, since the "dont touch" feature would probably touch the same places.

**Comment by nickbp** [comment]
When adding custom objects, the controller already will not delete them, because they do not have an `opstrace` annotation showing ownership. However, it will "modify" them if it has a local desired resource that collides with the custom object, regardless of whether the `opstrace` annotation is present.

So what I'm thinking we can do is to just say that the controller will never touch something that lacks an `opstrace` annotation. This logic feels pretty intuitive to me.

Given this, if someone wants to make custom modifications to an opstrace-owned resource, they should also remove the `opstrace` annotation so that the controller refrains from automatically overriding the modifications. Once the custom modifications are no longer needed, an `opstrace` annotation can be re-added (with any value, except special ones like `no-update` for immutable) and the controller can then take over.

**Comment by MatApple** [comment]
💯👍

**Comment by jgehrcke** [comment]
> they should also remove the opstrace annotation so that the controller refrains from automatically overriding the modifications

Would the controller then immediately re-create the same resource / duplicate it, just with the `opstrace` label set?

**Comment by triclambert** [comment]
Document in our private wiki rather than in public docs.
