### ISSUE TITLE
Backing out of device association at login prompt results in invalid code

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#476]
When creating a dev cluster, I followed these steps:

- Started CLI create
- Got URL to visit, opened it in browser A
- Confirmed the code, got the github/google association options
- Picked the google option, then got a login prompt, realized that I should be in browser B instead
- Open browser B to the code URL provided by the CLI, get "Invalid or expired user code" error

Maybe we could mark the code invalid only after it's been successfully associated?

I was able to work around the issue by Ctrl+Cing the running CLI (waiting on association) and restarting the create command, but only using browser B this time to finish the association.

**Comment by jgehrcke** [comment]
Can indeed be looked at as an inconvenience, but it's one imposed by the design of the login process and the way state is shifted between systems.

> Maybe we could mark the code invalid only after it's been successfully associated?

The ignorant argument for why we can't quite do that is: that's beyond our control, within Auth0's part of the system.

However, there is a much better line of reasoning for why this can't quite work architecturally, I think.

The "successfully associated" part is where the details matter a lot. This is about a multi-step single sign-on process with two SSO providers involved and the actual user agent.

The source of truth w.r.t. the state of the process evolves throughout the process. With every step, some state information gets passed on to the next item in the chain.

While Auth0 _initiates_ this multi-step single sign-on process, it cannot reliably, securely know when the _last_ step of the process succeeded. That's an invariant imposed by the nature of the single sign-on architecture involved.

The device code protects against certain classes of attacks, and for that to work reliably I am reasonably sure that Auth0 tries hard to guarantee that it can only be used _once_ (replay attacks with this code must not be allowed, for example). They can do that by managing the relevant state centrally and _consistently_, in a source of truth (some database on their side).

In the moment we click `Confirm`, the device code either gets explicitly or implicitly marked as _consumed_ in that source of truth. Subsequently, the single sign-on process continues and the corresponding state is "let go" by Auth0, leaves their regime of their influence -- state is shifted from backend to frontend. 

That is, the device code *is* marked invalid only after it has been "successfully associated" (as you wish) -- but the definition of "successfully associated" might be a little disappointing :)
