### ISSUE TITLE
non-containerized looker build: Cannot find type definition file for 'src' and other TSC compile errors

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#493]
In directory `opstrace/test/test-remote`:

```
$ yarn run tsc tsconfig.json
yarn run v1.22.10
$ tsc -b tsconfig.json
error TS2688: Cannot find type definition file for 'flow-typed'.

error TS2688: Cannot find type definition file for 'src'.

error TS2688: Cannot find type definition file for 'test'.


Found 3 errors.

error Command failed with exit code 1.
```

This is how I used to build looker locally, especially in combination with `--watch`.

Yes, that's not covered by CI. In CI, we build looker via `make rebuild-looker-container-images`.

Which creates an isolated build environment: the only context is the big `yarn.lock` at the root, everything else present during the build is below `/test/test-remote`. That isolated environment is a little easier to reason about and results in much faster yarn install (when doing things from scratch).

Task: make local looker build work again via `--watch`. Cover that in CI. Document it.

**Comment by jgehrcke** [comment]
https://github.com/microsoft/TypeScript/issues/27956 @mattmccutche genious.

> These errors occur when you have subdirectories of a typeRoots directory (in this case node_modules/@types) that do not contain index.d.ts files. I agree the error message is mysterious and should be improved.

> In your case, the errors occur because your package.json specifies a package named @types/, which is a silly thing to do.

We do have this situation:

```
± cat node_modules/@types/package.json
{
  "name": "@jcoreio/async-throttle",
  "version": "0.0.0-development",
  "description": "throttle async and promise-returning functions.  Other packages don't do it right.",
  "main": "index.js",
  "sideEffects": false,
  "files": [
    "index.js",
    "index.js.flow"
  ],
...
```

https://github.com/opstrace/opstrace/blob/6332a5014b8213fbe4080fff5072cab8787ecee7/packages/app/package.json#L155

```
    "@types/": "jcoreio/async-throttle",
```

**Comment by mattmccutchen** [comment]
I'm glad you found the explanation of the error!  I don't see the purpose of subscribing me to this issue though.
