### ISSUE TITLE
Update out-of-date CRDs automatically in controller

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#498]
We've recently updated the CRDs for prometheus in order to support adding custom HTTP headers to remoteWrite (which our non-system tenants use for sending metrics to cortex). This feature was only added in the latest version of prometheus, so running clusters will need a CRD update in order to support custom HTTP headers in remoteWrite.

The controller currently doesn't automatically update CRDs that already exist, however it will automatically recreate CRDs if they are manually deleted (and thereby update them to the new version hardcoded in the controller).

From Nick's previous experience with setting up CRDs in Helm, its possible that we'll need slightly different logic for updating CRDs. For example, maybe we just check for CRD _updates_ once on controller startup, then in the reconciliation loop only do creates for missing CRDs? This wouldn't protect against a user manually editing a CRD behind our back though. Seb also knows a lot about CRDs.

**Comment by MatApple** [comment]
@nickbp can we replace the internals of this (https://github.com/opstrace/opstrace/blob/6e9a9c4894c73d401f1a4790a2e597058ce983da/lib/kubernetes/src/kinds/CustomResourceDefinition.ts#L217) method with a:
```
await this.delete();
return this.create();
```
The CRs should still be fine, but in the background we'll essentially delete the existing CRD and create a new CRD. It's blunt and there is likely a more nuanced way but would be interesting to see if this simplicity would work for now.
