### ISSUE TITLE
Investigate automating getting data from an external K8s cluster?

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#565]
At the moment, getting metrics/logs from an external K8s cluster into Opstrace is a manual process via [this user guide](https://opstrace.com/docs/guides/user/instrumenting-a-k8s-cluster).

Investigate about how we could automate this, where e.g. a user might submit a working kubeconfig as credentials and then Opstrace controller would use that to deploy a Prometheus operator into the remote cluster to scrape and send metrics back into the Opstrace cluster (or similar for fluentd and collecting logs).

At this point this is just a ticket for thinking about how we might do this and what caveats there might be, for example:
- It's worth pointing out that this feature can just target the "80%" use-case of a simple cluster without additional networking/auth requirements. Meanwhile users in the more complicated "20%" case could fall back on doing the setup manually via the [user guide](https://opstrace.com/docs/guides/user/instrumenting-a-k8s-cluster).
- After the operators are installed, maybe the controller doesn't keep managing them from there. Instead we could just launch the deployment, then wait for it to finish, then discard the credentials, rather than doing ongoing monitoring of the remote cluster to check that the operator is healthy. This may reduce complexity in terms of the Controller needing to manage local AND remote kubernetes clusters all the time. However it might be annoying if the user wants to change things frequently, or if the prometheus or fluentd operator need regular babysitting.

**Comment by sreis** [comment]
Besides the kubeconfig, it might also need cloud credentials to access remote clusters.

> This may reduce complexity in terms of the Controller needing to manage local AND remote kubernetes clusters all the time. 

Have a look at https://github.com/kubernetes-sigs/kubefed to see if it would be useful to manage the state of resources in remote clusters.

Another option that has been discussed in the past would be to expose an endpoint, and the user could use `kubectl` to deploy it to the target cluster.

```
kubectl apply -f https://cluster.opstrace.io/some/endpoint
```

**Comment by nickbp** [comment]
I really like the generated kubectl endpoint idea. It would give users a window to inspect/edit the result to fit their environment before applying it to their cluster.

It also leaves us out of the loop in terms of needing to get access to the user's cluster. I could see a lot of customers (especially the sort with budget to have lots of K8s clusters lying around) having a lot of pushback with storing their kube credentials directly into Opstrace - particularly given these credentials would need sufficient access to install operators into a cluster. So just rendering an install spec feels like it'd be the best of both worlds.

**Comment by sreis** [comment]
> I could see a lot of customers (especially the sort with budget to have lots of K8s clusters lying around) having a lot of pushback with storing their kube credentials directly into Opstrace - particularly given these credentials would need sufficient access to install operators into a cluster. 

Good point!

**Comment by terrcin** [comment]
FYI: Just bumped into this ticket for the first time.

I've started working on our first [onboarding process](https://github.com/opstrace/opstrace/issues/598) for the webapp which I think this intersects with as the first step of that process is to get new users to monitor a k8s cluster. Initially I wasn't expecting anything as fancy as Opstrace talking to their cluster and doing the setup but rather a wizard interface automating the linked how to guide on this asking them some questions around namespace names etc... and generating the yaml for them to download, and providing the shell commands to run.

**Comment by nickbp** [comment]
This ticket is superceded by #601.

In terms of the method to use, I think the flow mentioned earlier by Simao around displaying a kubectl configuration to the user and having them verify+submit it makes the most sense.
