### ISSUE TITLE
proposal: method to allow Cortex and Loki configuration tuning/override

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#580]
We need a practical way to change Cortex and Loki configuration settings in a running cluster.

Currently, it requires changing the Opstrace controller code, building and pushing a new image, and then upgrading the cluster. This means any parameter tunning becomes the default setting going forward for all Opstrace clusters.

# Proposal 1

Add a new field to the cluster config file to allow overriding configuration.

This is how it could look like to tune [`max_label_names_per_series` in Cortex](https://cortexmetrics.io/docs/configuration/configuration-file/#limits_config). 

```
tenants:
  - default
env_label: opstrace-ci
node_count: 3
cert_issuer: letsencrypt-staging

advanced_config:
	cortex:
		limits_config:
			max_label_names_per_series: 45
```

The Opstrace CLI, in the create and upgrade commands, adds the `advanced_config` section to the controller configuration as JSON (keeps the current behavior).

The controller is responsible for merging the default Opstrace settings with the overrides when it handles the [Cortex](https://github.com/opstrace/opstrace/blob/main/packages/controller/src/resources/cortex/index.ts#L248) and [Loki](https://github.com/opstrace/opstrace/blob/main/packages/controller/src/resources/loki/index.ts#L151) deployments.

# Proposal 2

Create a Kubernetes ConfigMap named, for example, `opstrace-controller-config-overrides` in the default namespace (where Opstrace controller ConfigMap is stored).

The ConfigMap would have a field where we add the Cortex and Loki config overrides as a YAML string. 

This is how it could look like to tune [`max_label_names_per_series` in Cortex](https://cortexmetrics.io/docs/configuration/configuration-file/#limits_config). 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: opstrace-controller-config-overrides
  namespace: default
data:
  cortex: |
	limits_config:
		max_label_names_per_series: 45  
```

The controller is responsible for merging the config defaults with the overrides when it handles the [Cortex](https://github.com/opstrace/opstrace/blob/main/packages/controller/src/resources/cortex/index.ts#L248) and [Loki](https://github.com/opstrace/opstrace/blob/main/packages/controller/src/resources/loki/index.ts#L151) deployments.

Deployment of the configuration overrides, in this scenario, is done via `kubectl`.

**Comment by sreis** [comment]
Did some [prototyping in a typescript playground](https://www.typescriptlang.org/play?#code/PTBQIAgGQewawJYQMYwHYDMEHMIBMBTDAQwFcAbAFwGdwxU1rKJz4EBhdLXAXggG9QEYRGoEATgDcJALgFCRwgBaVKABwD65BEwJoNamOMpyAjAAYAHOYA0CxdnFrkGsVIkaAtsQAeG8QTIkl7U2K4IAF4EcgAspgCcMQDM5jG2EJCEJBTMABQxEACyAEIAlBAAVBAW9iKOzq4S0uJevo1oeCFh1JHREHGJKWkZwPhEZFQQ+UVlldXmtQC+dopklEoaesQARuQEeHKU4qQEKyLISqRocK6URgQaDNxygorCF1c3yMQXD084L1qim2PzgjhgVwO8jebwA7uIEJQCCDkDdtqQMBhZBAAKzmfFAkTLQnCTwETzfX6dZDaPQmaEw87oHq6NCUDRKYjUJSHY6nEkiNySBDIPoAIjJFJ+Sn2AFoaQg6WKBYtCarFMTFNpPIjqI8uACGYo9BgjKKvAQjiKNGhiGS5CRyGIzooEGhsAQmAh0P5iEivNs5HjbIS3R6vT70eImOEogG5AAmfEhmGQE1m-YQN0QACOJwREkJ3j8dILeu1iIMHjzEgAnnIAGzJ8wjCAABQksqRtrZEFLtZYCB1zDUElz+drS1AiwA3KA6HQIABRHx2tR7aBsFAG3AwZoIwjUCDEDBI8QsGDEPBhiDrAgQWt28gAOgXDCYF8QAHl9whDxA+FeEQKxofVMENICYVNGAQXEMwbFbK88GPCA0AIWEICwAhyDwAUw09ShvX0cQ-QeTxA3mFtID3CQD3vYgxmySZJGIcgTinVV5xARdOEITDxBgTwIBUdRqBkEBsB0Shn0k9ZSG2Z9UE8YAdXEGIiGAZBTAAdgTHFLCSbY8G2eIG0seIcVMPB4gIHFtIwbY8TwGIYmQJIMG0xc7nwGAxgINQIBggArQJmDJcRJPdCBYURJRb1rUdqGQBE1Gkhc3TPEhRQgABJHLqC-bYQuQZggNyRFyTkYg0FrUo5G2GAYD2aq504jKJCy+8csK4rSoUABtOACHrUQrXdABdKqata+d2vETrcoAEQIfzCgkD0GVyShiAiy05G6orQoQ58TuoCFxFFMSIAAQXEEjawAHgO3qAD46tynrQpm8AKgqIQqgAAUPZKEFSoiiktJQYGQ7zflRLMMGPNAsyRISdCRwLDpK58IEW0ikeQgAxK4SvBnb73fP8JH2f6MeCo7RF8hBEdrCFUJWmHfIIHwaVIPj1hgZ0IHXAguXvUg1DwfG7wgMkBeQn5UHEa93XIWtXzmAG1B2u0UfJCBZQgAAVGU9aE9Y-XZ-Yj287YKZlVEac1gJKFIcRkf4YpGuatBFggAB1GU73PIxUJgZgAYqtGj2qzHev++hmWYHRPpK-b8tT5g+HK1Gptq+rvdF5GeBehkXbd5Gc-1nga4gTOq88coADIm4gABCW77ufHRO+IWsG9KUpWrnH6-s14GUsI9AIfl29fNHeajCEhjCH82X1vvGBEfpkraE17WSKE-hM797bduYQ2TfvM+PSRZCd+YC3mDQ6254gO31925CYvWW9TeoCW65FTIQBmdN2l1aZax1kfXuj1M4vT9mAi6noDbG3-udUUuRqDlCftFBA5ByDv3FmITmEAJZSyRH-e8AMb6WjjqFSB5d3YCBPmg+8WBbSEPCh6e+WNKAJ1AO+Zgq81BrV2vtZaq0N4ASmLQ+kz0GYnWfEgy6chYFPXge9BRJUAKlyApAJhyMZZyIRmHRm4CUHa2oCQhQzMphtxUZ6Z8ex3TrHKJBCAhjbw7VvnOYQnF3hJ08Z6HI+1M4yLkSPYQdjyoFT4bkAIACqCDyNNuRgzAXFyDQKQciY4+COOoM4vQ2B1hRJEKac8uQ9jJxkeYGcWYIAPRYHoepSAADUfBTDuMJEIvs5BPB5xkQU-qCBxplNdIjWJ9dsKN26YyTCodci9KGgObMMy5nzNMbkGZz5OQFVhGgNsAkF6UH7islJHj5kxJTvEmZg1hrjQuQKGEMS26JJyPc2s40IAAB8fntxub1BJISqCfMeRszZbx3mgpWd8wCs5nlvHVJCkQIixEemBUkygYKEJ3NhUPRF-i+liFSZCmJsDu7UFgZij5+KIAtxundPulLqV4oeU8lFbxIAMG+N2aWptKCwl8jte6McOjBM8DRJGA48AS20Ly+8agETDgQNICALE2KekJVCkF2LYUyIpRgASnhchoQwgAZUtDSmFDzFLoF5ds-pYLB4Es5US7CJLLkouhXqh5Mi2VfL8W65FkKQ2MjDRqNUU5-HzmEF4n1w8uJgEgAACRgBhRE0UIQ4QvPAQcQ037cOvqbLIEwaB4N-jLGid0qaFLfEE1giB0X7E4OBXgAgEVoo3lUtgza8Ctu4AhRtHAdxDrYD+WitbShJsXJa9hbpWL0J0dmGW74mqb1IOoTdgUjGmwRNgFQOMcrMAYNtN0NtTZmswoqHN1V76-kPIudAm9EYyw1ScOt3E117GcTAbAPam0b37TuAlQA) to do the object merging proposed in the controller. You'll have to click the Run button to see the final object in the console output.

**Comment by jgehrcke** [comment]
Yes, we need a documented way to allow for users to override / set / tune specific Loki & Cortex configuration parameters. 

I think that indeed in most cases it would be really valuable to our users when we can provide them with a way to change these settings at runtime _easily_, so that we facilitate _finding_ good configuration parameters.

Of course another perspective is that the cluster config document should _also_ allow for a way to set parameters (to allow for a simple, reproducible deployment with just the `create` operation), but we can add this later.

That is, I like that you want to  and started exploring proposal 2.

**Comment by MatApple** [comment]
The tenant list config is a good example of what we could also apply here. It allows you to set the tenant list at install time in the config.yaml.

After that, the config is synced to Postgres (cluster-external source of truth) which the UI (and an API) can interact with. By having this config in Postgres, we automatically get a GraphQL API for it through Hasura. Any changes to the config in Postgres automatically cause the Kubernetes ConfigMap (cluster-local source of truth) to update. https://github.com/opstrace/opstrace/blob/main/packages/controller/src/tasks/syncTenants.ts

The controller then uses that cluster-local config (a ConfigMap) to reconcile the tenant state by creating/destroying namespaces etc.

**Comment by sreis** [comment]
Discussed with @MatApple offline and he agreed to merge #606 with what is described in Proposal 2 to unblock the feature as soon as possible.

I'll update this issue with the changes to integrate with the  CLI and store the config in Postgres.

**Comment by sreis** [comment]
Discussed with @terrcin how we can add config validation in the controller using the methods for [alert manager config schema validation](https://github.com/opstrace/opstrace/tree/main/packages/app/src/client/validation/alertmanager/config). 

We will have to manually write the yup schema definition for both Cortex and Loki configuration. Afterward, use the schema to validate the result of merging the Opstrace defaults with the user-defined overrides. Another thing to consider is using [ramdajs](https://ramdajs.com/docs/#mergeDeepWith) for the deep merge step because it's already being used in the app.

**Comment by sreis** [comment]
Closing since there's ongoing work on the runtime config API in #745.
