### ISSUE TITLE
can only query first set of rules that are posted

### ISSUE THREAD

**Issue by triclambert** [opstrace/opstrace#593]
**Describe the bug**

Fetching the configured rules via `/api/v1/rules/myns` returns only the first posted set of rules, ignoring subsequent posts.  This is confirmed by inspecting the S3 bucket and finding both sets of rules successfully stored.

**To Reproduce**

Post different rules multiple times, then query them back:
```
curl -H "Authorization: Bearer $(cat tenant-api-token-system)" https://cluster.opstrace.io/api/v1/rules/myns
```

**Expected behavior**

Return only the latest rules that were posted.

Note:  `/api/v1/alerts` behaves as expected.

**Comment by nickbp** [comment]
I think these endpoints are being routed through to Cortex, so it might actually be a bug in Cortex's storage layer. They recently refactored their storage handling so it wouldn't be surprising if a bug got through. Worst case we can send them a fix.

**Comment by triclambert** [comment]
Worked on this a bit.  Calculating the comparison of 1K metrics per month (which is how Grafana Labs prices their cloud service), we see that the Stripe demo in AWS was cheaper than our original cost blog post:

![image](https://user-images.githubusercontent.com/19239758/127206254-c85ed005-4641-404d-a17c-666eff951c3b.png)

This is pretty great because the workload there is much more aggressive (because of the churn).

**Comment by nickbp** [comment]
Some references from looking at cortex code. From how the `handler logic` code is written it looks like the new rulegroup is _supposed_ to override the old rulegroup. Maybe there's some vagaries to the API that lead to unexpected behavior?

1. Endpoint for `POST /api/v1/rules/<namespace>` is configured in [pkg/api/api.go](https://github.com/cortexproject/cortex/blob/20f8931/pkg/api/api.go#L314)
2. Handler logic in [pkg/ruler/api.go](https://github.com/cortexproject/cortex/blob/68a917d/pkg/ruler/api.go#L442) calls `SetRuleGroup` with the new group content
3. `SetRuleGroup` has two implementations:
  - bucket ([thanos/current](https://github.com/cortexproject/cortex/blob/6529041/pkg/ruler/storage.go#L119)) in [pkg/ruler/rulestore/bucketclient/bucket_client.go](https://github.com/cortexproject/cortex/blob/6318b7b/pkg/ruler/rulestore/bucketclient/bucket_client.go#L222) - I think we're on this one
  - object ([legacy](https://github.com/cortexproject/cortex/blob/6529041/pkg/ruler/storage.go#L78)) in [pkg/ruler/rulestore/objectclient/rule_store.go](https://github.com/cortexproject/cortex/blob/6318b7b/pkg/ruler/rulestore/objectclient/rule_store.go#L203) - mentioning this too just in case
4. The [bucket implementation's `SetRuleGroup`](https://github.com/cortexproject/cortex/blob/6318b7b/pkg/ruler/rulestore/bucketclient/bucket_client.go#L222) is internally calling into [these](https://github.com/cortexproject/cortex/blob/df80ec1/pkg/storage/bucket/sse_bucket_client.go#L50) [wrappers](https://github.com/cortexproject/cortex/blob/78a6245/pkg/storage/bucket/prefixed_bucket_client.go#L34) around the [underlying thanos storage library](https://github.com/cortexproject/cortex/blob/02bcf27/vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go#L438).
5. The thanos library calls [PutObject](https://github.com/cortexproject/cortex/blob/02bcf27/vendor/github.com/thanos-io/thanos/pkg/objstore/s3/s3.go#L438) which I would've expected to overwrite the existing files...

PS: The rule content is stored as a [serialized protobuf](https://github.com/cortexproject/cortex/blob/282a092/pkg/ruler/rulespb/compat.go#L16) to `<opstrace-instance>-cortex-config/rules/<tenant>/<b64(namespace)>/<b64(group)>`, e.g. `nick-test-cortex-config/rules/system/b64(system)/b64(node-exporter)`

**Comment by nickbp** [comment]
I tried manually reproing the issue and wasn't able to get it - the rulegroup I tried was updated correctly as expected.

I manually created a rule group, then edited the content to have a different ALLCAPS alert name. After querying the rule group again, it looked like the new ALLCAPS names had taken effect. Here's the exact steps I took:

```
$ kubectl port-forward -n cortex ruler-64954c7485-6f4rw 8080:80
```

check existing content (expect missing for `default` tenant):
```
$ curl -H "X-Scope-OrgID: default" http://localhost:8080/api/v1/rules/system/node-exporter
group does not exist
```

get copy of rule group from `system` tenant (selection is arbitrary, just grabbing an easy copy of something), then submit it to `default` tenant:
```
$ curl -s -H "X-Scope-OrgID: system" http://localhost:8080/api/v1/rules/system/node-exporter > system_node-exporter
$ cat system_node-exporter | curl -H "X-Scope-OrgID: default" --data-binary @- -H "Content-Type: application/yaml" http://localhost:8080/api/v1/rules/system
```

check the initial alert names in the `default` tenant:
```
$ curl -s -H "X-Scope-OrgID: default" http://localhost:8080/api/v1/rules/system/node-exporter | grep -i 'alert: nodefilesystemspace'
    - alert: NodeFilesystemSpaceFillingUp
    - alert: NodeFilesystemSpaceFillingUp
```

replace the above alert names with ALLCAPS versions and apply to the same `default` rule group:
```
$ sed 's/NodeFilesystemSpace/NODEFILESYSTEMSPACE/g' system_node-exporter | curl -H "X-Scope-OrgID: default" --data-binary @- -H "Content-Type: application/yaml" http://localhost:8080/api/v1/rules/system
{"status":"success","data":null,"errorType":"","error":""}
```

refetch the alert group and find that the ALLCAPS name change took effect:
```
$ curl -s -H "X-Scope-OrgID: default" http://localhost:8080/api/v1/rules/system/node-exporter | grep -i 'alert: nodefilesystemspace'
    - alert: NODEFILESYSTEMSPACEFillingUp
    - alert: NODEFILESYSTEMSPACEFillingUp
```

tidy up:
```
$ curl -H "X-Scope-OrgID: default" -XDELETE http://localhost:8080/api/v1/rules/system/node-exporter
{"status":"success","data":null,"errorType":"","error":""}
$ curl -H "X-Scope-OrgID: default" http://localhost:8080/api/v1/rules/system/node-exporter
group does not exist
```

FWIW this may be a problem specifically for the `system` tenant rulegroups in the `system` namespace (like the one we copied into `default` above), since the controller will automatically override any changes every [60 seconds](https://github.com/opstrace/opstrace/blob/main/packages/controller/src/tasks/cortexRules.ts#L79)

**Comment by triclambert** [comment]
Thanks for investigating, @nickbp.
