### ISSUE TITLE
Onboarding process

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#598]
# Current Situation

At the moment new users are just dumped into the website without explanation or guidance about what to do next. They are shown a list of all Tenants and Users with the main area showing the "System" Tenant detail page that includes a link to it's Grafana instance.

# Goal

Introduce a guided "New user/cluster" onboarding process enabling users to be successful as quickly and easily as possible. The best way for users to see the value of Opstrace is by quickly and easily monitoring their software infrastructure.

# Process

The process is [described in this ticket](https://github.com/opstrace/opstrace/issues/600)

**Comment by opstracy** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Create "Application Creation Guidelines" documentation #599](https://github.com/opstrace/opstrace/issues/599) | N/A | terrcin | Open


###### do-not-edit-end-codetree-epic-issues
