### ISSUE TITLE
UI/UX design for Onboarding Processs

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#600]
Epic: [Onboarding Process](https://github.com/opstrace/opstrace/issues/598)

After setting up their Opstrace Cluster the new user goes to their URL and logs in via the Auth0 social login. This is the process we want to put them straight into that we need UI/UX designs for:

1. They are welcomed to the site, this is their first visit so some explanation is required

2. Currently opstrace isn't doing much for them so we encourage them to setup their first monitoring - our initial best guess for their first task is to monitor an external k8s cluster

3. They enter a process for adding the "k8s cluster monitoring" integration

3a. We tell them how this works, what we'll require from them and what types of access they'll need and tasks we'll ask them to perform etc...

3b. We ask them for some inputs, for example the namespace to install into and the namespaces to monitor and which tenant to send the data to. Note: this doesn't work at the moment, but ultimately they should be able to add a new Tenant here and download the access token as part of this process.

3c. We generate the k8s yaml for installing Prometheus into their cluster (
 this is generated based on data from their responses) which they can inspect and download (or copy+paste)

3d. We provide commands to run in their shell that installs the Prometheus monitoring on their k8s cluster. This uses the download yaml as well as their tenant`s access token generated as part of the cluster install or addationally downloaded from here as they add a new Tenant

3e. They explicitly tell us once they have done this so that our backend can pre-setup dashboards in that Tenant's Grafana for visualising the expected data and providing a quick feedback loop

3f. We provide links to directly view the dashboard(s) at the end of this process and easily from the webapp after they exit this process

3g. We show if there is yet to be any data received and offer debugging advice if not

This whiteboard diagram was the brainstorming for the above process:
![opstrace-onboard-thoughts.jpg](https://codetreeusercontent.s3.amazonaws.com/uploads/0b5044a6-481e-4d8d-9ee2-c2f574dce794/opstrace-onboard-thoughts.jpg)

**Comment by terrcin** [comment]
Note: work from this ticket will generate the main tasks for this epic around implementation of this design work.

**Comment by ShreyasGit51283** [comment]
@terrcin I've started doing the onboarding screens here
https://www.figma.com/file/hTCk38dJkaHN7Ae0dmguWy/OpsTrace?node-id=0%3A1

Need help here -
- Need to breakdown the wizard a bit more. 
- I didn' t quite understand step 3b. Could you help out there.
- https://opstrace.com/docs/guides/user/instrumenting-a-k8s-cluster/#sending-logs-and-metrics-from-a-kubernetes-cluster is this the tutorial for this setup? 
Thanks
