### ISSUE TITLE
Determine how  to setup monitoring of a k8s cluster

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#601]
Epic: [Onboarding Process](https://github.com/opstrace/opstrace/issues/598)
Background: to the [onboarding process](https://github.com/opstrace/opstrace/issues/600)

It might be as straightforward as generating the yaml from the templates shown in [our userguide on this exact topic](https://opstrace.com/docs/guides/user/instrumenting-a-k8s-cluster/#prerequisites)

Additonally [this ticket](https://github.com/opstrace/opstrace/issues/565) is related, mostsly around potential future work on this topic.

The outcomes needed:
* work out what a user need to do to setup monitoring of a k8s cluster
* what requirements are there? obviously access to the cluster to be monitored etc... what do they need installed on their computer etc...
* what variables are there involved that we can ask the user to fill in for generating the yaml with, eg Namespace to install under, names of namespaces to monitor
* the shell command(s) to run for istallation
* how can they test it's running as expected?
* any other requirements?

**Comment by sreis** [comment]
> what variables are there involved that we can ask the user to fill in for generating the yaml with, eg Namespace to install under, names of namespaces to monitor

The following has come up in discussions with users:

* Metrics collection:
  * Deploy `node_exporter` to collect Kubernetes node metrics (user might be running it already)
  * Deploy `kube-state-metrics` to collect more Kubernetes metrics (user might not want it). On this topic, leaving a note for us to filter out some high cardinality metrics, for example, `apiserver_admission_controller_admission_latencies_seconds_.*`, by default.
  * Global Scrape Limit

* Log collection
  * Application logs in JSON format?

* Both for metrics and log collection:
  * Add custom labels (for example, `cluster_name`, `cloud_provider` etc.)

> It might be as straightforward as generating the yaml from the templates shown in our userguide on this exact topic

Something else to consider for metrics scraping. Do we want to deploy the Prometheus operator instead? One added benefit is that creating scrape rules is easier. Easy in the sense that the user creates a Kubernetes [ServiceMonitor](https://github.com/opstrace/opstrace/blob/main/packages/controller/src/resources/loki/index.ts#L411-L445) resource for the target it wants to scrape.

> how can they test it's running as expected?

I've recently learned about [Loki canary](https://grafana.com/docs/loki/latest/operations/loki-canary/). I'm thinking of deploying it as part of our CI test upgrades pipeline to have something running during the upgrade test. The project tests a Loki endpoint and emits metrics. The user could also install it on their Kubernetes cluster and confirm data reaches the Opstrace cluster via a grafana dashboard, or some new UI component could query that information. Just sharing ideas around.

**Comment by triclambert** [comment]
I believe this is overcome by our integration.
