### ISSUE TITLE
Show installed integrations for a tenant

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#604]
Epic: [Onboarding Process](https://github.com/opstrace/opstrace/issues/598)

As part of the onboarding process we're directing the user through adding the K8s Metrics Integration. This means that once they have successfully completed that process we'll need to show them that they have installed/set this up etc... And allow them to add another for for another K8s cluster.

This means we'll need to start storing Integration data for each Tenant in the database, the data the user gave us when setting it and it's current status. Atleast the following is needed:

  - New table representing integrations added for a Tenant
    - need to be able to store data inputed from user - eg k8s monitoring namespace name
    - include status of integration - `installing`, `pending`, `active`, `error`, `no data`, `stopped`, `unknown`
      + installing: user has started the processs of setting up and installing this integration, but has not indicated they have finished this
      + pending: awaiting for data as user has indicated that they have installed/setup the integration
      + active: opstrace is actively receiving data from this integration
      + error: something isn't working right (can't think of what, but we'll eventually need this)
      + no data: this integration has stopped receiving data, it had been active but now isn't
      + stopped: user has said they have stopped/paused/disabled/removed this integration
      + unknown: catch all for anything else

**Comment by triclambert** [comment]
I do believe this is done.
