### ISSUE TITLE
ci: gcp: create SQLInstance: failed: reached the max instance per project/creator limit

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#62]
**Describe the bug**

```
[2020-12-01T20:13:53Z] 2020-12-01T20:13:53.517Z error: error during cluster creation (attempt 3):
[2020-12-01T20:13:53Z] GaxiosError: Failed to create instance because the project or creator has reached the max instance per project/creator limit.
[2020-12-01T20:13:53Z]     at Gaxios._request (/snapshot/build/node_modules/gaxios/src/gaxios.ts:117:15)
[2020-12-01T20:13:53Z]     at runMicrotasks (<anonymous>)
[2020-12-01T20:13:53Z]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2020-12-01T20:13:53Z]     at JWT.requestAsync (/snapshot/build/node_modules/google-auth-library/build/src/auth/oauth2client.js:343:18) {
[2020-12-01T20:13:53Z]   response: [Object],
[2020-12-01T20:13:53Z]   config: [Object],
[2020-12-01T20:13:53Z]   code: 403,
[2020-12-01T20:13:53Z]   errors: [Array]
[2020-12-01T20:13:53Z] }
```
https://buildkite.com/opstrace/scheduled-main-builds/builds/1285#f7b824b4-4945-488d-8367-0cc01229c654/200-1075

**Comment by triclambert** [comment]
Request approved, up to the _maximum_ allowable instances.

![DEE50250-27AC-4056-BF19-D36EA4091C3C_1_105_c](https://user-images.githubusercontent.com/19239758/100953937-6f479d80-34c8-11eb-9666-73bd596d14de.jpeg)

**Comment by spahl** [comment]
damn I bet we already do more that 100 build a week. Maximum for sure?

**Comment by triclambert** [comment]
I didn't specifically ask about that one, but I did ask if the 7 days was fixed...

> Regarding your question, I’m afraid that this limit of waiting 7 days is fixed for now.

**Comment by spahl** [comment]
Ah the time window is fine but we probably need 250-300 to get a margin of
safety. Did you explain our use case that we spin these up in CI?

**Comment by triclambert** [comment]
I did; they explicitly asked.  I'll reply with a thanks and one last check if the 100 can increase.  

(FWIW, we're dealing with a limit that is the function of the max over a time window...  if we shortened the window to 2 days we'd be fine.)

**Comment by triclambert** [comment]
Their reply...

> I'd like to mention that this limit is also fixed (max of 100 instances per project) because of the architecture of Cloud SQL and engineering team's recommendation is to create multiple projects to house the various instances.
> 
> I hope this information provides the needed clarification regarding this inquiry.

**Comment by spahl** [comment]
Stupid reco. Play stupid games, win stupid prizes... We will have to shard CI accross N projects...

**Comment by triclambert** [comment]
Possibly the 1hr main builds could be a bad idea until we do.  /cc @jgehrcke @sreis

**Comment by jgehrcke** [comment]
OK. We'll find a way. Thanks for the updates, everyone.
Indeed a key metric is the desired number of GCP builds per week as of today; and of course the expected number of GCP builds per week in the mid term. The solution we pick should predictably satisfy that.

**Comment by MatApple** [comment]
> Possibly the 1hr main builds could be a bad idea until we do. /cc @jgehrcke @sreis

I think we can increase the period between main builds again now.

**Comment by jgehrcke** [comment]
> I think we can increase the period between main builds again now.

Not sure I understand what the proposal is :) We have been running with one build every 4 hours for the last weeks; we didn't change that during the last few days. In particular, doing one build per hour was just an idea; didn't act on that.

I'm OK with the current build frequency; I would however _love to_ increase it so that we get better stability sampling. Let's review cost and quota issues and discuss where we want our limits to be (esp. in terms of cost).

About this issue here in particular: the pressure is off, for now. Closing.

**Comment by jgehrcke** [comment]
Problem is back, as expected. Re-opening.

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1341: manual build, gcp should work again after landing https://github.com/opstrace/opstrace/pull/128 (using a single gcp project, different than the one before).

**Comment by jgehrcke** [comment]
> https://buildkite.com/opstrace/scheduled-main-builds/builds/1341

`main-test-gcp` failed in here because `ingress/https-cert` never got ready:
```
[2020-12-10T15:53:01Z] 2020-12-10T15:53:01.258Z info: waiting for 0 DaemonSets
[2020-12-10T15:53:01Z] 2020-12-10T15:53:01.258Z info: waiting for 0 StatefulSets
[2020-12-10T15:53:01Z] 2020-12-10T15:53:01.258Z info: waiting for 1 Certificates
[2020-12-10T15:53:01Z] 2020-12-10T15:53:01.259Z debug:     Waiting for Certificate ingress/https-cert to be ready
[2020-12-10T15:53:05Z] 2020-12-10T15:53:05.059Z warning: cluster creation attempt timed out after 2400 seconds
[2020-12-10T15:53:05Z] 2020-12-10T15:53:05.060Z error: 3 attempt(s) failed. Stop retrying. Exit.
```

**Comment by sreis** [comment]
> main-test-gcp failed in here because ingress/https-cert never got ready:

Had a look at the [logs in CI](https://system.ci.aws.opstrace.io/grafana/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22tenant-builds-logs%22,%7B%22expr%22:%22%7Bopstrace_cluster_name%3D%5C%22bk-1341-738-g%5C%22,%20k8s_namespace_name%3D%5C%22ingress%5C%22,%20k8s_app%3D%5C%22ingress%2Fcert-manager%5C%22%7D%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D):

It was waiting for the DNS to propagate:
```
2020-12-10 13:44:24	
E1210 14:44:24.288410 1 sync.go:183] cert-manager/controller/challenges "msg"="propagation check failed" "error"="DNS record for \"system.bk-1341-738-g.opstrace.io\" not yet propagated" "dnsName"="system.bk-1341-738-g.opstrace.io" "resource_kind"="Challenge" "resource_name"="https-cert-hbht5-3263228420-2590738829" "resource_namespace"="ingress" "resource_version"="v1" "type"="DNS-01"
```

But all of a sudden the domain disappeared:
```
2020-12-10 13:46:00	
E1210 14:46:00.508950 1 controller.go:158] cert-manager/controller/challenges "msg"="re-queuing item due to error processing" "error"="No matching GoogleCloud domain found for domain opstrace.io." "key"="ingress/https-cert-hbht5-3263228420-3959882636"
```

Which is strange since the [teardown started ~1h10m later](https://buildkite.com/opstrace/scheduled-main-builds/builds/1341#d4dae6f8-41a1-4b9f-acdb-03dd9c577f21/6775-6776)
```
[2020-12-10T14:53:05Z] + echo '--- initiate teardown'
```

**Comment by jgehrcke** [comment]
`main-test-gcp` is now choosing randomly between two newly set up GCP projects. The last three scheduled builds from `main` had passing `main-test-gcp` jobs. Closing this. Let's see when and how badly this comes back... :-).

**Comment by sreis** [comment]
A few failures over the weekend.

https://buildkite.com/opstrace/scheduled-main-builds/builds/1441#322a0217-508b-448a-b39c-dc7423c9fa70/222-1569

https://buildkite.com/opstrace/scheduled-main-builds/builds/1443#c80f9de9-8646-4908-a5f9-1aeafcf9eb56/222-626

https://buildkite.com/opstrace/scheduled-main-builds/builds/1444#775e6f6b-b880-4f24-a13e-80c0b23d1958/222-626

https://buildkite.com/opstrace/scheduled-main-builds/builds/1447#260292e7-306f-41b7-8a43-54bcb5daf418/222-626

https://buildkite.com/opstrace/scheduled-main-builds/builds/1448#72b44f8f-8656-44da-bd91-b18619716752/222-636

https://buildkite.com/opstrace/scheduled-main-builds/builds/1449#8285b35e-9d73-4933-9167-263b1f385604/222-636

**Comment by jgehrcke** [comment]
Interesting. Especially during those last ~7 days I think we did did not have more builds than during those seven days before that. Hm. Activating a third GCP project for CI and temporarily disabling one project in https://github.com/opstrace/opstrace/pull/218.

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/3362#32c30f00-7938-450c-b412-ab2334d56b83/237-1865

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/scheduled-main-builds/builds/1507#242a447d-cf26-4807-9308-b06450bb4880/222-844

**Comment by sreis** [comment]
The `bbb` shard also seems to have the same issues https://buildkite.com/opstrace/prs/builds/3375#1fa14d81-4238-4700-9c5b-f374d27b8fcb/189
