### ISSUE TITLE
Onboarding: Add I9n Wizard - K8s Metrics

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#626]

**Comment by opstracy** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Create basic coding framework for multi-step wizard #627](https://github.com/opstrace/opstrace/issues/627) | N/A | N/A | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by nickbp** [comment]
There's still an issue left open for being able to edit I9ns, but otherwise the rest is complete. The edit ticket (#641) has been decoupled from this epic in the meantime, since it would indeed be useful to support editing existing integrations.
