### ISSUE TITLE
Create basic coding framework for multi-step wizard

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#627]
Epic: Onboarding: Add I9n Wizard - K8s Metrics https://github.com/opstrace/opstrace/issues/626

Typically our wizards will take the form of four stages:

1. Introduction, explain what this is, what the requirements are, what i required of the user, what the end result will be
2. Ask the user for their inputs to the process
3. Generate outputs, this could be instructions to follow, download artefacts etc.. May ask the user to confirm here when they have completed their tasks
4. Show the user the result of what they have done, eg new I9n installed with dashboard links. If it doesn't work then show debugging info here.

**Comment by nickbp** [comment]
Clearing out old tickets, base I9n support is mostly complete now
