### ISSUE TITLE
Add I9n Wizard - K8s Metrics user indicates they have successfully run the

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#634]
Epic: Onboarding: Add I9n Wizard - K8s Metrics https://github.com/opstrace/opstrace/issues/626

Have an explicit action the user must perform, eg press a button, that indicates they have successfully setup the I9n on their K8s cluster and that it should now be sending data. This updates the underlying data and triggers the background monitoring service to start checking for the data.

**Comment by nickbp** [comment]
Clearing out old tickets, base I9n support is mostly complete now. At this point the flow is the user submits the integration wizard first, then takes/deploys any config from the integration instructions. The UI periodically checks in the background whether data has started to arrive. Under this flow there isn't much need for a separate button.
