### ISSUE TITLE
Add I9n Wizard - K8s Metrics - Install pre-configured alerts

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#636]
Epic: Onboarding: Add I9n Wizard - K8s Metrics https://github.com/opstrace/opstrace/issues/626

As the user goes through the Add I9n Wizard they will eventually indicate that they have down the setup steps required and their K8s cluster should now be sending logs and metrics to their Opstrace cluster. When they tell is this we'll ask them if they'd like a default set of Alerts installed, maybe just focusing on attached storage filling up and/or too much load on the system. This is so that they can quickly see a result of their actions and the value then can get from Opstrace. Aiming for a nice and quick feedback loop here 

This task is very much a long term asperational task and depends on the user having configured Alert Manager already and the App understanding that config and presenting a list of receivers etc... for the user to pick from for the Alerts we want to setup for them.

**Comment by nickbp** [comment]
Clearing out old tickets, base I9n support is mostly complete now. Thinking of the individual integrations themselves, we can probably get away without alerts for most of them.

For example, maybe the new Cockroach integration could have some predefined alerts? But even then it's a bit of a corner case and depends on knowing universal things that we should always alert for any Cockroach deployment. If anything it's a similar problem to how we define alerts on Opstrace itself across a variety of deployments.
