### ISSUE TITLE
Add I9n Wizard - K8s Metrics - Show user on finals stop when we see their data coming in

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#638]
Epic: Onboarding: Add I9n Wizard - K8s Metrics https://github.com/opstrace/opstrace/issues/626

Poll / subscribe (what ever is initially easiest) the I9n status to show user that we are detecting data coming in. Provide a link to the installed Grafatna dashboards when those are a thing.

**Comment by nickbp** [comment]
Checking for data is implemented now - it's shown as a status after the I9n entry has been created
