### ISSUE TITLE
Add I9n Wizard - User can exit and re-enter countinuing from where they left off

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#639]
Epic: Onboarding: Add I9n Wizard - K8s Metrics https://github.com/opstrace/opstrace/issues/626

I hate it when I accidently close a browser tab and lose my progress, or need to pause what I'm doing for a few days before I can come back to it and there is no mechnism to save progress.

**Comment by nickbp** [comment]
Clearing out old tickets, base I9n support is mostly complete now. So far the wizards haven't been particularly complicated (usually 1-3 text boxes total) so keeping our spot probably isn't super important.
