### ISSUE TITLE
Onboarding: Background I9n Monitoring Service

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#642]

**Comment by opstracy** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Simple but smart pollig period bassed on status of I9n #644](https://github.com/opstrace/opstrace/issues/644) | N/A | nickbp | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by nickbp** [comment]
Clearing out old tickets, base I9n support is mostly complete now
