### ISSUE TITLE
Onboarding: Global Dashboard

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#647]

**Comment by opstracy** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Create Global Dashboard page #648](https://github.com/opstrace/opstrace/issues/648) | N/A | terrcin | Open


###### do-not-edit-end-codetree-epic-issues
