### ISSUE TITLE
Onboarding: Detect I9n being installed manually

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#651]
Note: this could be from a users devops automation system such as Terraform or a CI tool creating cluster on each run

**Comment by opstracy** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Determine if data is coming in for a K8s Metrics I9n that the user has yet to setup #660](https://github.com/opstrace/opstrace/issues/660) | N/A | nickbp | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by nickbp** [comment]
Clearing out old tickets, base I9n support is mostly complete now
