### ISSUE TITLE
Show user new K8s Metrics I9n created based on something new sending data

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#661]
Epic: Onboarding: Detect I9n being installed manually https://github.com/opstrace/opstrace/issues/651

Use new flag on the I9n table to draw the users attention to this automatically created I9n. We might need to get them to cornfirm this is legit, or it might not be what they were expecting to happen. Additionally they might need to edit some of it's metadata.

What happens about automatically installed Dashboards are Alerts?

**Comment by nickbp** [comment]
Clearing out old tickets, base I9n support is mostly complete now
