### ISSUE TITLE
Determine if multiple K8s clusters are sending their data to a single I9n instance 

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#662]
Epic: Onboarding: Detect I9n being installed manually https://github.com/opstrace/opstrace/issues/651

This could be happening as someone reused the download yaml in their terraform scripts for example.

Set a flag on the table and details / explination for the UI to use.

**Comment by nickbp** [comment]
Clearing out old tickets, base I9n support is mostly complete now
