### ISSUE TITLE
Onboarding: Refactor Exporters to be I9ns

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#664]
At the moment we're treating Credentials and Exporters as seperate entities, ie a Credential can exist without an Exporters. This work is about changing that relationship. As a user creates an Exporter I9n (of which there are several) they will fill in the wizard form which may include credential information, such as for Cloud Watch and Stackdriver, but this isn't needed for Blackbox.

The UX flow won't be "User says they want a Exporter I9n then as part of that setup process selects a type of Exporter" but rather each type of Exporter is it's own I9n. So the UX flow will have user saying they wish to add the CloudWatch I9n which just so happens to be an Exporter.

**Comment by opstracy** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Exporter I9n - refactor underlying data structure for exporters and credentials #665](https://github.com/opstrace/opstrace/issues/665) | N/A | nickbp, terrcin | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by nickbp** [comment]
Clearing out old tickets, base I9n support is mostly complete now
