### ISSUE TITLE
Exporter I9n - refactor underlying data structure for exporters and credentials

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#665]
Epic - Onboarding: Refactor Exporters to be I9ns https://github.com/opstrace/opstrace/issues/664

**Comment by nickbp** [comment]
Effectively in progress in these branches: `nick/i9n-exporter-schema` and `nick/i9n-migrate-exporters-to-integrations-mergelast`

**Comment by terrcin** [comment]
completed
