### ISSUE TITLE
UX/UI of the Opstrace WebApp

### ISSUE THREAD

**Issue by ShreyasGit51283** [opstrace/opstrace#670]
@MatApple @terrcin @spahl 
Here are design proposals for the Web app  that take into account scalability, intuitiveness, and a little bit of aesthetics. Happy to iterate based on feedbacks and technical constraints. 
@terrcin I think we need to freeze on these design before we tackle the onboarding flow in #600 

Please leave comments on the design itself in Figma here
https://www.figma.com/file/hTCk38dJkaHN7Ae0dmguWy/OpsTrace?node-id=0%3A1

Preview the screen here( Low res)

![1Login](https://user-images.githubusercontent.com/35736086/116814768-0dbf5400-ab78-11eb-952f-8f65dbfdfe80.png)
![2tenant](https://user-images.githubusercontent.com/35736086/116814769-0ef08100-ab78-11eb-94b4-575ae71401a3.png)
![3Alert Manager](https://user-images.githubusercontent.com/35736086/116814771-1021ae00-ab78-11eb-9442-af197a3e7d78.png)
![4Cloud Metrics - Credentials](https://user-images.githubusercontent.com/35736086/116814773-10ba4480-ab78-11eb-9ca3-8fea79f1a04d.png)
![5Cloud Metrics - AddCloudProvider](https://user-images.githubusercontent.com/35736086/116814774-10ba4480-ab78-11eb-9186-29103b7050da.png)
![6CloudMetrics-Exporters](https://user-images.githubusercontent.com/35736086/116814776-1152db00-ab78-11eb-8602-933dcb254fb7.png)

**Comment by ShreyasGit51283** [comment]
![1 Login](https://user-images.githubusercontent.com/35736086/116814600-70642000-ab77-11eb-9d86-9b9d043b0b3b.png)
![2 tenant](https://user-images.githubusercontent.com/35736086/116814601-72c67a00-ab77-11eb-8ae2-e1cbfa95c3c4.png)
![3 Alert Manager](https://user-images.githubusercontent.com/35736086/116814603-735f1080-ab77-11eb-8e30-ce3d019f3bd5.png)
![5 CloudMetrics](https://user-images.githubusercontent.com/35736086/116814606-73f7a700-ab77-11eb-8fd6-59715ddcdf75.png)
![6 Cloud Metrics - AddCloudProvider](https://user-images.githubusercontent.com/35736086/116814609-74903d80-ab77-11eb-89b9-a193a20fada3.png)
![7 CloudMetrics_Exporters](https://user-images.githubusercontent.com/35736086/116814611-7528d400-ab77-11eb-9da3-e2d1731206fb.png)

**Comment by MatApple** [comment]
Just dropping a note here as we close this because @ShreyasGit51283 and I have been talking in our public Slack channel and after our recent UI release, we decided not to pursue this. Thank you so much @ShreyasGit51283 for your contribution here, we really appreciate it!
