### ISSUE TITLE
Migrate all system rules/alerts to Cortex

### ISSUE THREAD

**Issue by MatApple** [opstrace/opstrace#720]
Currently, we configure the system tenant's Prometheus with our system rules/alerts. We need to migrate these to the multi-tenant Cortex ruler.

https://github.com/opstrace/opstrace/blob/d8b55da58726b07f9f75fdde0f380c0cf16c464a/packages/controller/src/resources/monitoring/system/index.ts#L225

**Comment by nickbp** [comment]
Mat recently finished this via #882, adding a push/sync in the controller.
