### ISSUE TITLE
Adding a tenant via UI: API never comes up, no error message shown

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#733]
When you add a tenant via UI and use capital letters, the tenant's API will never come available. The exact technical problem is described in https://github.com/opstrace/opstrace/issues/710.

**Comment by jgehrcke** [comment]
To make this a tiny little less severe, in the blog post we wrote:

> Warning: we do not yet do strict tenant name validation. To make sure things work, please keep the name lower case [a-z] for now.

https://opstrace.com/blog/introducing-dynamic-tenant-addition-and-token-management/

**Comment by terrcin** [comment]
I've updated the validation regex used in https://github.com/opstrace/opstrace/pull/994 to exclude uppercase.

The main problem here is that the interface we use for getting the tenant name from users doesn't allow for validation feedback, so if they put in some invalid we accept it from them then do nothing.

**Comment by jgehrcke** [comment]
> The main problem here is that the interface we use for getting the tenant name from users doesn't allow for validation feedback, so if they put in some invalid we accept it from them then do nothing.

Ouch. That is of really limited value; and almost as annoying UX-wise as the previous state. 

Let's accelerate the work on the API-based validation seriously; and then make sure that the API-based validation feedback is displayed to the user.

**Comment by jgehrcke** [comment]
This is fixed now that the API rejects invalid tenant names.
