### ISSUE TITLE
GCP: Failed to reuse buckets marked for deletion

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#747]
**Describe the bug**

This [build](https://buildkite.com/opstrace/prs/builds/4206#484c2206-e5b1-4181-885c-9b44cdb902e9) used the GCP credentials for shard `eee` but failed to create [a GKE cluster](https://buildkite.com/opstrace/prs/builds/4206#484c2206-e5b1-4181-885c-9b44cdb902e9/319-1377). It created the bucket successfully and marked it for deletion during teardown. 

The follow-up [retry](https://buildkite.com/opstrace/prs/builds/4206#254ad184-4529-43b4-a53e-7628e95d18bd) used GCP credentials for shard `fff` and failed because it tried to use the [previous bucket](https://buildkite.com/opstrace/prs/builds/4206#254ad184-4529-43b4-a53e-7628e95d18bd/323-676) and ended up in a loop trying to set it up.

```
[2021-05-17T17:26:11Z] 2021-05-17T17:26:11.077Z info: create GCS bucket: prs-bk-4206-47f-g-loki
[2021-05-17T17:26:11Z] 2021-05-17T17:26:11.393Z info: bucket not returned by getBuckets()
[2021-05-17T17:26:11Z] 2021-05-17T17:26:11.393Z info: call createBucket()
[2021-05-17T17:26:13Z] 2021-05-17T17:26:13.026Z info: bucket not returned by getBuckets()
[2021-05-17T17:26:13Z] 2021-05-17T17:26:13.026Z info: call createBucket()
[2021-05-17T17:26:14Z] 2021-05-17T17:26:14.706Z info: bucket not returned by getBuckets()
```

**Comment by sreis** [comment]
It looks like we swallow [409s](https://github.com/opstrace/opstrace/blob/main/lib/gcp/src/bucket.ts#L114-L132). Check if we can use some other field in the error message to exit early with a clearer error.

**Comment by jgehrcke** [comment]
@sreis this looks like the same symptom as tracked in https://github.com/opstrace/opstrace/issues/192 -- can you maybe double-check? :)

So you think that `createBucket()` may fail with a 409 indicating cross-credential "visibility" whereas `getBuckets()` would not return what's there as of the credential mismatch?

>  to exit early with a clearer error.

Do you envision a "bucket exists, but is marked for deletion via a lifecycle rule and must not be re-used" kind of exit from `create`?

**Comment by sreis** [comment]
> Do you envision a "bucket exists, but is marked for deletion via a lifecycle rule and must not be re-used" kind of exit from `create`?

No. I'm thinking it doesn't let you create the bucket in a new account without it being deleted in the other one first but it returns a 409 instead of a more standard 401/403.

Closing since it's a duplicate of #192.
