### ISSUE TITLE
tenant names are not properly validated

### ISSUE THREAD

**Issue by triclambert** [opstrace/opstrace#799]
**Describe the bug**

Tenant names are currently not validated properly.  

**Expected behavior**

Tenant names must be validated (in both the CLI and UI) to conform to DNS naming standards since the tenant name is used as a DNS subdomain.  That means there must be a 63 char limit; it can not start with a digit or with a hyphen, and must not end with a hyphen.

References:
https://en.wikipedia.org/wiki/Hostname
https://www.ietf.org/rfc/rfc1035.txt

**Comment by jgehrcke** [comment]
Oh. :)

Existing bug ticket: https://github.com/opstrace/opstrace/issues/733

Existing task ticket: https://github.com/opstrace/opstrace/issues/710

Work done in the CLI: https://github.com/opstrace/opstrace/pull/712

Useful validation specifics (a regex that does its job, modulo length constraint): https://github.com/opstrace/opstrace/issues/710#issuecomment-838446595

Work left to be done: https://github.com/opstrace/opstrace/issues/710#issuecomment-845829240

There also is a conversation on Slack covering angles with more detail.

**Comment by MatApple** [comment]
Cool, thanks for linking to your recent work and findings on this @jgehrcke!

**Comment by jgehrcke** [comment]
I am going to close this in favor of https://github.com/opstrace/opstrace/issues/733.
