### ISSUE TITLE
scale out (horizontally): add nodes to an opstrace instance via the CLI

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#817]
Investigate how we can add nodes via the CLI.  

Note: allow only scale-up and document how the user can [scale down](https://docs.google.com/document/d/1wqTE2Evr2sAcfsSxkd7VD4cy8QqjaCnyCYiVoJ4i9gk/edit#heading=h.be52qvr5vh8y).

**Comment by nickbp** [comment]
FYI in some scale tests I've been successfully manually increasing the size of AWS Auto Scaling Groups as well as GCP Instance Groups and things have behaved largely cleanly: opstrace-controller detected the new node count and automatically scaled up deployments/statefulsets that depended on the node count. So that half of things seems to work fine as-is. I did not try decreasing the size however.

**Comment by sreis** [comment]
> FYI in some scale tests I've been successfully manually increasing the size of AWS Auto Scaling Groups as well as GCP Instance Groups and things have behaved largely cleanly: opstrace-controller detected the new node count and automatically scaled out any deployments/statefulsets/etc whose replicas are configured based on the node count. So that half of things seems to work fine as-is.

Nice! Thank you for reporting back.

> I did not try decreasing the size however, and IIRC the cortex ingester docs basically say "dont do that".

Yeah, that'll be "fun".

**Comment by triclambert** [comment]
> > I did not try decreasing the size however, and IIRC the cortex ingester docs basically say "dont do that".
> 
> Yeah, that'll be "fun".

While it is extremely tedious, it can be done by hitting the `/ingester/shutdown` endpoint on the "last" ingester and deleting its pod.

**Comment by nickbp** [comment]
Now that I think about it, does the cortex operator handle ingester teardown these days? In other words if the controller reduced the desired ingester count, would the operator then automatically do the `/ingester/shutdown` sequence?

cc @sreis

**Comment by sreis** [comment]
>  In other words if the controller reduced the desired ingester count, would the operator then automatically do the /ingester/shutdown sequence?

The cortex-operator doesn't support that operation yet, but all the scaffolding to build it is there. We need to come up with a roadmap for that project.
