### ISSUE TITLE
app unit tests failed: The value provided to the Tabs component is invalid.

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#822]
```
FAIL src/client/views/ring-health/RingHealth.test.tsx (26.849 s)

Test Suites: 1 failed, 12 passed, 13 total
[2021-06-02T16:23:44Z] Tests:       2 failed, 53 passed, 55 total
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2407#f7d06d99-a502-4eb1-b1ed-435d67d06e53/500-3300

**Comment by sreis** [comment]
@MatApple @MoSattler Can one of you have a look, please? It seems like #812, or #813 might have broken the main branch.

**Comment by MatApple** [comment]
It doesn't appear that we've got a broken main, so going to let @MoSattler investigate this when he's back online

**Comment by MoSattler** [comment]
Sorry, I missed this somehow - I will take a look.

**Comment by MoSattler** [comment]
I cannot reproduce it locally at all - they work fine their. 
For now I deactivated them in #888, as to unblock merging. Furthermore I will try to get them to work against in #915.
