### ISSUE TITLE
UI does not render in Brave browser

### ISSUE THREAD

**Issue by MatApple** [opstrace/opstrace#838]
**Describe the bug**
UI does not load (Login Page) in Brave browser.

**To Reproduce**
1. Create an Opstrace instance
2. Install Brave browser
3. Ensure Brave Shields are "Down"
4. Open UI in Brave

Information from user:
> Brave Shields are down for the page
> Brave Version: 1.25.70 Chromium: 91.0.4472.77 (Official Build) (x86_64)
>OS: macOS 11.4 (20F71)
> I’m guessing the cookie isn’t being passed through from auth0 or something?
> Having said that, Brave does send the following cookie to the originator page:
> _legacy_auth0.is.authenticated=true; auth0.is.authenticated=true; > opstrace.sid=s%3AREDACTED%2BREDACTED%2BREDACTED

> UI rendered correctly when using Chrome instead of Brave.

**Expected behavior**
Login page should render and logging in should result in correct redirect back to the authenticated Opstrace UI.

**Comment by MatApple** [comment]
I could not reproduce with the following Brave version and OS:

**Brave**: Version 1.25.68 Chromium: 91.0.4472.77 (Official Build) (x86_64)
**OS**: macOS Catalina 10.15.7

I will try to test with the same version as the affected user.

**Comment by MoSattler** [comment]
@MatApple I cannot reproduce this with

**Brave:** Version 1.26.74 Chromium: 91.0.4472.124 (Official Build) (arm64)
**OS:** MacOS BigSur 11.4 (20F71)

**Comment by MatApple** [comment]
Thanks, @MoSattler! Going to close because we cannot reproduce and have not had another instance reported.
