### ISSUE TITLE
ci instability: yarn install exits with ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#873]
```
install yarn workspace dependencies
...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@material-ui/icons/-/icons-4.11.2.tgz: ESOCKETTIMEDOUT".
```
https://buildkite.com/opstrace/prs/builds/4614#06d0a6e6-bcd5-4860-b4bf-a941dc7ef00f/916-927

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/4619#8fe084d0-4afc-410c-a4b0-5363b2a1c521/925-935

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/4620#8d93d91f-d05c-4a2b-9cb1-c6edcf9c45ca/946-961

**Comment by jgehrcke** [comment]
A manual build retry has helped. That is, this does not happen _every_ time, but 'just' with elevated frequency. Let's hope that this rate drops again asap.

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/4631#7128a1e7-dd1f-4144-b60e-e924eb105b5e/924-934

**Comment by jgehrcke** [comment]
https://buildkite.com/opstrace/prs/builds/4733#3a6bb9a9-3665-444e-8cce-e345e9f82c33/933-943

**Comment by MoSattler** [comment]
https://buildkite.com/opstrace/prs/builds/4839#53fa0140-1a7e-42cb-96f1-1e48dc9a0c12/925-931

**Comment by MoSattler** [comment]
https://buildkite.com/opstrace/prs/builds/4839#53fa0140-1a7e-42cb-96f1-1e48dc9a0c12/925-931

**Comment by nickbp** [comment]
Lots of failures in mid-late June followed by no repros, feels like an upstream issue
