### ISSUE TITLE
Larger clusters start to hit anonymous dockerhub limits for pulling dockerhub images

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#881]
**Describe the bug**
If a cluster with a large number of nodes is deployed, images on dockerhub can be stuck on pulling due to their anonymous quota limits.
To give an idea of scale, this was seen on an 18 node cluster, but not on a 9 node cluster, implying that the threshold where this starts to be a problem is somewhere in that range.

**To Reproduce**
Create a large cluster (observed on 18 nodes) for running opstrace, observe that some deployments are stalled due to image pull errors.

**Expected behavior**
The cluster should deploy successfully without image pull errors.

**Comment by nickbp** [comment]
As a quick fix, I'm planning on adding support for providing the cluster with a docker credentials secret, which can then be picked up and used by the controller in deployments. I think just using `imagePullSecrets` for configuring the credentials would overall be the easiest route, since it'd be compatible across a variety of cluster types. Otherwise the methods for getting the credentials onto the host start to involve getting files onto the host node filesystem.

Steps:
- The user would create a Secret with a predetermined in the `default` namespace containing the credentials configuration. We could also have the Installer create this secret on the user's behalf, later, if needed.
- The controller would see this Secret and would copy it into namespaces being managed by the controller (`application`, `cortex`, `loki`, `x-tenant`, etc...)
- The controller would append an `imagePullSecrets` setting in all Deployments/StatefulSets/DaemonSets that it manages, pointing to the copied Secret in each respective namespace.

**Comment by nickbp** [comment]
(Mat has a solution in #892)

**Comment by MatApple** [comment]
Thanks for linking @nickbp!

**Comment by MatApple** [comment]
This has been addressed
