### ISSUE TITLE
expired JWT credentials being used when destroy and creating clusters

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#884]
I was encountering the following error when trying to destroy a cluster and also when creating a new cluster, this was with a fresh version of the binary downloaded ~4 hours ago.

```
GET HTTP request to https://dns-api.opstrace.net/dns/ failed. Attempt: 1. Error: ETIMEDOUT, Timeout awaiting 'request' for 30000ms. Retry in 1.6 s.
```

I was not asked to `confirm` via a browser for either of the commands I was running. @MatApple suggesed I delete the `id.jwt` and `access.jwt` files in my code root and try the commands again. This worked, I was asked to `confirm` via the website and I stopped getting the timeout. I had new jwt files in my code root.

The jwt files I deleted were timestamp ~14 hours prior to me running the commands. Maybe some sort of time/timezone mismatch between the binary and the dns service in checking their `exp` attribute or something else like that?

**Comment by triclambert** [comment]
I have encounters this as well. If you waited longer (I'm not sure how much, maybe 10hr) then you would be prompted to login, as one would expect.

**Comment by MatApple** [comment]
A fix for this should be treated as a high priority. The resulting error is a timeout on the DNS service request, so the user is left with no clear path to move forward

**Comment by MatApple** [comment]
@jgehrcke could you help with this one, please? :-)

**Comment by jgehrcke** [comment]
> The resulting error is a timeout on the DNS service request, so the user is left with no clear path to move forward

Yes. This is the actual bug (in the DNS service) which is already being tracked via https://github.com/opstrace/opstrace/issues/833.

**Comment by jgehrcke** [comment]
> @jgehrcke could you help with this one, please? :-)

I can. It's however not entirely straight-forward; requires a little bit of 'reverse-engineering' the things that actually happen in the DNS service. I looked into this when building the client for it. A conclusion from that investigation is here: https://github.com/opstrace/opstrace/blob/1c7608164c2a87ccb0ffdb84876fdbe3eab4c2e9/lib/dns/src/opstrace.ts#L207

What I can say is that there is unnecessary complexity in the DNS service, which is actually trying to validate two different authentication tokens where only _one_ is needed -- I think in one of both validation procedures there is an uncached JWKS request involved which is probably where things may fall down.

Part of this fix is to make clear which of both tokens the client _must_ present, and in the implementation we need to make sure to properly cache the JWKS response.

**Comment by MatApple** [comment]
Cool, it'd be great to get to the bottom of this :-)
