### ISSUE TITLE
installer: Re-running the installer regenerates public key but not private key

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#894]
**Describe the bug**
Observed when running the installer command a second time for the same cluster:

- The `tenant_api_authenticator_pubkey_set_json` value in the `default/opstrace-controller-config` configmap had been updated to a new key. This resulted in new replicasets for cortex-api/dd-api/etc in the tenant namespaces with the newly generated public key (and the old public key could be recovered by looking at the env in their old replicasets).
- Meanwhile the private key in the `system-tenant/system-tenant-api-auth-token` was NOT updated by the installer, so `system-tenant/prometheus-system-prometheus-0` was using the old (private) key to send data to `system-tenant/cortex-api` which was checking against the new (public) key.

As a result, the system grafana dashboards were showing no metrics for the interval where the certificates had a mismatch. After the public key was restored to an old value (via hand editing `default/opstrace-controller-config`), metrics resumed.

Would have expected the installer to update both the secret and the configmap, or neither?

**To Reproduce**
Run the installer against the same cluster a second time, check `system-tenant` `cortex-api` pods for errors like this:
```
time="2021-06-16T02:16:08Z" level=info msg="jwt verification failed: jwt verif: unknown kid: daf5d0edd714bf6def7f1f7590d51555d6471a36"
time="2021-06-16T02:16:08Z" level=info msg="emit 401. Err: bad authentication token"
```
Meanwhile `system-tenant` `prometheus-system-prometheus-0` will show errors like:
```
ts=2021-06-16T02:13:43.680Z caller=dedupe.go:112 component=remote level=error remote_name=78b32e url=http://cortex-api.system-tenant.svc.cluster.local:8080/api/v1/push msg="non-recoverable error" count=197 err="server returned HTTP status 401 Unauthorized: bad authentication token"
```

**Comment by nickbp** [comment]
Also seems to affect the tokens written to disk after the installer has finished.

**Comment by jgehrcke** [comment]
https://github.com/opstrace/opstrace/issues/20  : )
