### ISSUE TITLE
Bad Gateway errors in Grafana: fixed after restarting grafana-datasource-splitter pods

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#896]
**Describe the bug**
After e.g. rolling out a cortex change (which redeploys the cortex query-frontend pods), Grafana will start failing its dashboard and logs queries, showing `Bad Gateway` errors.
These errors go away on their own if the corresponding tenant `grafana-datasource-splitter` pod is restarted.
My suspicion is that these splitter pods are caching DNS results, and when cortex or loki pods move to a new pod IP, suddenly the splitter pod can't reach cortex/loki anymore.
It looks like the splitter pods are running nginx internally so this is probably a shortcoming with nginx (non-broken DNS caching might even be a paid feature).

Possible solutions:
- Use something other than nginx that reacts better to loki/cortex query pods changing IPs?
- Use a different kind of K8s Service with an IP that doesn't change?

Example logs when nginx is acting up:
```
$ kubectl logs -n system-tenant grafana-datasource-splitter-cortex-559d4dfdbd-dwj2d
2021/06/16 04:45:22 [error] 22#22: *2830 no live upstreams while connecting to upstream, client: 192.168.42.224, server: _, request: "POST /api/v1/query_range HTTP/1.1", upstream: "http://query-frontend.cortex.svc.cluster.local/api/v1/query_range", host: "grafana-datasource-splitter-cortex.system-tenant.svc.cluster.local"
192.168.42.224 - - [16/Jun/2021:04:45:22 +0000] "POST /api/v1/query_range HTTP/1.1" 502 157 "-" "Grafana/8.0.0"
```

**Comment by sreis** [comment]
Got a repro of this issue by upgrading from last week's version to the latest main. Another way to repro is to rollout restart the `query-frontend` deployment. 

This is the error that the `grafana-datasource-splitter-cortex` pod is logging.
```
2021/06/16 10:41:23 [error] 21#21: *618 upstream timed out (110: Connection timed out) while connecting to upstream, client: 192.168.32.194, server: _, request: "GET /api/v1/query_range?query=sum%20by%20(namespace%2Cstatus_code)%20(rate(cortex_api_proxy_request_duration_seconds_count%7Bcontainer%3D%22cortex-api%22%2Cmethod%3D%22POST%22%2Croute%3D%22api_v1_push%22%7D%5B5m%5D))&start=1623838275&end=1623840075&step=15 HTTP/1.1", upstream: "http://192.168.37.13:80/api/v1/query_range?query=sum%20by%20(namespace%2Cstatus_code)%20(rate(cortex_api_proxy_request_duration_seconds_count%7Bcontainer%3D%22cortex-api%22%2Cmethod%3D%22POST%22%2Croute%3D%22api_v1_push%22%7D%5B5m%5D))&start=1623838275&end=1623840075&step=15", host: "grafana-datasource-splitter-cortex.system-tenant.svc.cluster.local"
192.168.32.194 - - [16/Jun/2021:10:41:23 +0000] "GET /api/v1/query_range?query=sum%20by%20(namespace%2Cstatus_code)%20(rate(cortex_api_proxy_request_duration_seconds_count%7Bcontainer%3D%22cortex-api%22%2Cmethod%3D%22POST%22%2Croute%3D%22api_v1_push%22%7D%5B5m%5D))&start=1623838275&end=1623840075&step=15 HTTP/1.1" 404 19 "-" "Grafana/8.0.0"
```

Notice the `http://192.168.37.13:80` IP. It doesn't match any of the the expected IP addresses for the query-frontend pods.

```
> kubectl -n cortex get pods -o wide
NAME                              READY   STATUS    RESTARTS   AGE    IP               NODE                                           NOMINATED NODE   READINESS GATES
...
query-frontend-59d8c45d74-698wf   1/1     Running   0          101m   192.168.62.212   ip-192-168-46-232.us-west-2.compute.internal   <none>           <none>
query-frontend-59d8c45d74-cjmfz   1/1     Running   0          101m   192.168.32.93    ip-192-168-35-58.us-west-2.compute.internal    <none>           <none>
....
```

I exec'd to the `grafana-datasource-splitter-cortex` pod and queried DNS for the `query-frontend` service and got the following: 
```
root@grafana-datasource-splitter-cortex-5fbcfd6f5b-lxmhh:/# nslookup query-frontend.cortex.svc.cluster.local                                                               
Server:         10.100.0.10                                                                                                                                                
Address:        10.100.0.10#53                                                                                                                                             
                                                                                                                                                                           
Name:   query-frontend.cortex.svc.cluster.local                                                                                                                            
Address: 192.168.62.212                                                              
Name:   query-frontend.cortex.svc.cluster.local                                      
Address: 192.168.32.93    
```

This means nginx is caching the DNS entries. With some [help from google](https://serverfault.com/questions/240476/how-to-force-nginx-to-resolve-dns-of-a-dynamic-hostname-everytime-when-doing-p/593003#593003) it seems that using a variable in proxy_pass forces re-resolution of the DNS names because NGINX treats variables differently to static configuration. From the [NGINX proxy_pass documentation](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass):

> Parameter value can contain variables. In this case, if an address is specified as a domain name, the name is searched among the described server groups, and, if not found, is determined using a resolver.

I'll try this workaround locally and report back.

**Comment by jgehrcke** [comment]
> This means nginx is caching the DNS entries. With some help from google it seems that using a variable in proxy_pass forces re-resolution of the DNS names because NGINX treats variables differently to static configuration. From the NGINX proxy_pass documentation:

Haha :D We used that in DC/OS : ) https://github.com/dcos/dcos/blob/780e481f86be75e1cffe18a6e891e275de92fef0/packages/adminrouter/extra/src/README.md#dns-resolution

https://github.com/dcos/dcos/blob/780e481f86be75e1cffe18a6e891e275de92fef0/packages/adminrouter/extra/src/includes/server/master.conf#L63
