### ISSUE TITLE
check cortex distributor logs: Error: Expectation not fulfilled within 30 s

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#905]
**Describe the bug**

This test is failing consistently after upgrading to latest main: 

```
[2021-06-17T05:36:37Z]   1) system logs test suite
[2021-06-17T05:36:37Z]        check cortex distributor logs:
[2021-06-17T05:36:37Z]      Error: Expectation not fulfilled within 30 s
[2021-06-17T05:36:37Z]       at Object.waitForLokiQueryResult (testutils/logs.ts:275:9)
[2021-06-17T05:36:37Z]       at query (test_systemlogs.ts:52:20)
[2021-06-17T05:36:37Z]       at Context.<anonymous> (test_systemlogs.ts:72:5)
```

**Comment by sreis** [comment]
We bumped [Loki](https://github.com/opstrace/opstrace/commit/a8ae291b471b37c2a1e733c0cb9e7ea5786958ff) and that means the queriers restart after the upgrade which [triggers this closed but not resolved issue](https://github.com/grafana/loki/issues/3085).

**Comment by sreis** [comment]
This is still bitting the upgrade CI pipeline.

**Comment by sreis** [comment]
Ran another test locally this time after the upgrade the only pod logs in the cortex namespace were for the alertmanager and store-gateway. (Thought I had a screenshot of the log ingestion rate in this period but I don't). This is the log browser output:

![Screenshot from 2021-06-22 12-03-56](https://user-images.githubusercontent.com/495294/122922119-d177cb00-d352-11eb-9113-22aed349c0ae.png)

Used kubectl to check fluentd pod logs and didn't find any errors. Nevertheless, I did a rollout restart of the fluentd daemonset and it's now ingesting logs.

![Screenshot from 2021-06-22 12-12-16](https://user-images.githubusercontent.com/495294/122922465-2ddaea80-d353-11eb-90de-cb50c8449b19.png)

Log browser output.

![Screenshot from 2021-06-22 12-14-00](https://user-images.githubusercontent.com/495294/122922631-5a8f0200-d353-11eb-8388-e3ccd25cf647.png)

**Comment by sreis** [comment]
Was able to repro by restarting the Loki ingesters via `kubectl rollout restart`. This is how it looks right now:

![Screenshot from 2021-06-22 13-16-34](https://user-images.githubusercontent.com/495294/122931154-25d37880-d35c-11eb-851b-d7752eded659.png)

![Screenshot from 2021-06-22 13-17-19](https://user-images.githubusercontent.com/495294/122931202-3257d100-d35c-11eb-8fc8-5a8a4cc7d7ed.png)

**Comment by sreis** [comment]
Ran more tests locally but haven't been able to repro this again...

The following was done to avoid waiting for the the AWS infrastructure to be created. Set the `terminate` field to true in the controller config to make it delete all the Opstrace resources and clean up the cluster. Then proceed to change the image version of the controller deployment to `6cb91909-ci` and set the terminate field in the controller config back to `false`. The controller then deployed all the resources for version `6cb91909-ci`.  When the controller finished I ran a few logql queries to check everything was working as intended. Afterward, I set the controller image to version `bc424dc8-ci` from PR #918. After everything finished I ran logql queries to check everything was working and didn't hit any problems. 

I tried the above process multiples times and also restarted the ingesters but couldn't repro the issue.

**Comment by sreis** [comment]
Created a cluster with version `6cb91909-ci` and upgraded to latest main and it's showing the same problem.

Some pod logs are just not showing up. Including the cortex distributor logs.

It doesn't look related to any specific node. For example right now, it's missing the `opstrace-api` pod logs.

![Screenshot from 2021-06-23 10-13-36](https://user-images.githubusercontent.com/495294/123080358-5d99f900-d40c-11eb-9949-8895b1df8d78.png)

```
> kubectl -n application get pods -o wide
NAME                                  READY   STATUS    RESTARTS   AGE   IP               NODE                                           NOMINATED NODE   READINESS GATES
graphql-dc5d5d45c-9smtw               1/1     Running   0          51m   192.168.50.80    ip-192-168-45-167.us-west-2.compute.internal   <none>           <none>
opstrace-api-fd4b47c96-78xdm          1/1     Running   0          51m   192.168.52.22    ip-192-168-61-13.us-west-2.compute.internal    <none>           <none>
opstrace-application-98fd5679-p4b74   1/1     Running   0          51m   192.168.62.233   ip-192-168-45-167.us-west-2.compute.internal   <none>           <none>
redis-master-699669bb46-wlrwl         1/1     Running   0          66m   192.168.58.86    ip-192-168-61-13.us-west-2.compute.internal    <none>           <none>
redis-slave-7d48c5f4f9-j7rh8          1/1     Running   0          66m   192.168.37.15    ip-192-168-45-167.us-west-2.compute.internal   <none>           <none>
redis-slave-7d48c5f4f9-v54rm          1/1     Running   0          66m   192.168.41.166   ip-192-168-42-30.us-west-2.compute.internal    <none>           <none>
```

**Comment by sreis** [comment]
All the pods in the `loki` namespace, except Memcached pods, restarted during the upgrade. I decided to restart all Memcached deployments in the `loki` namespace to check if it changed anything—same story. Still not showing up logs from some pods.

**Comment by sreis** [comment]
Created a new cluster from latest main. When it finished it didn't show any issues. After restarting loki components it's now showing the same symptoms. Queries that were working before are now not returning any results.

No logs are showing up before the restart.
![Screenshot from 2021-06-23 11-50-56](https://user-images.githubusercontent.com/495294/123091916-6e9d3700-d419-11eb-87cc-3efae40d955b.png)

Expected logs:

![Screenshot from 2021-06-23 11-51-23](https://user-images.githubusercontent.com/495294/123092002-85dc2480-d419-11eb-91c9-897776d930df.png)

Makes me think something is going on with the state that is cached by the ingesters when they restart.

**Comment by nickbp** [comment]
Tried an upgrade of `nick-test` from `6129f8c1` to `c88abeaa`, didn't notice any gaps in data.

Then tried manually restarting loki ingester-0 thru ingester-2 via `kubectl delete pod`. This was done in sequence, giving each pod time to be Ready before restarting the others. I ran some log queries after each ingester was restarted and didn't notice missing data.

Following this, I started deleting querier pods, also in sequence. After having restarted `querier-0` and `querier-1` (hadn't gotten to `querier-2` yet), I noticed that 45 minute gap in data appeared. It might be a coincidence, but the gap ended at the point that ingester-1 had resumed logging `uploading tables` after being restarted:

- gap: 05:40:24 until 06:26:03, appears in queries for `{k8s_namespace_name="loki"}` and `{k8s_namespace_name="cortex"}` in the system tenant
- querier-0 was restarted around 06:35
- querier-1 was restarted around 06:40
- ingester-1 start time aligns with end of gap:
```
level=info ts=2021-06-24T06:25:29.401276106Z caller=lifecycler.go:406 msg="observing tokens before going ACTIVE" ring=ingester
level=info ts=2021-06-24T06:25:59.383714672Z caller=table_manager.go:171 msg="uploading tables"
level=info ts=2021-06-24T06:25:59.401770782Z caller=lifecycler.go:425 msg="token verification successful" ring=ingester
level=info ts=2021-06-24T06:25:59.401826564Z caller=lifecycler.go:746 msg="changing instance state from" old_state=JOINING new_state=ACTIVE ring=ingester
```

It feels like maybe there's some interaction between the ingesters restarting and the queriers restarting. Could be related to in-memory caching in the ingesters, if Loki does that? Maybe the queriers "lost track" of what cache the ingesters had when they were restarted. Again from what I could tell, restarting the ingesters on their own wasn't enough to create the gap and I only noticed gaps appearing after a couple queriers had also been restarted.

Something I noticed in the ingester logs during shutdown that they try to do handoff to a pending instance before exiting. From [this loki architecture page](https://grafana.com/docs/loki/latest/architecture/) I noticed that they mention `Handoff - Deprecated in favor of the WAL`. Might be related? I'm just guessing though and haven't tried enabling the WAL. But if the thing broken in recent Loki releases was relating to the deprecated handoff method, it'd sort of make sense...
```
level=info ts=2021-06-24T07:52:46.568014629Z caller=lifecycler.go:746 msg="changing instance state from" old_state=ACTIVE new_state=LEAVING ring=ingester
level=error ts=2021-06-24T07:52:46.568700615Z caller=transfer.go:201 msg="transfer failed" err="cannot find ingester to transfer chunks to: no pending ingesters"
[...]
level=error ts=2021-06-24T07:53:07.132789223Z caller=lifecycler.go:803 msg="failed to transfer chunks to another instance" ring=ingester err="terminated after 10 retries"
```

I tried deleting `querier-1` and `querier-0` again, but didn't see a new gap. Followed this with trying to delete `querier-2`, just in case, and still no gap.
However, once I also restarted all three of the ingester pods, a new gap appeared - or technically the existing gap was widened. Now the gap was 05:40:24 until 07:54:48. The gap only grew after all three ingester pods had been restarted. I queried after each was restarted, one at a time.

**Comment by sreis** [comment]
I just tested the rollout restart of loki ingesters and other components in a GCP Opstrace instance and could not reproduce this issue. I tested several times over the last hour and was able to query back data. To rule out queries that are cached in Memcached I always queried for pod logs of different applications (ex, graphql in application namespace then ingester in cortex namespace) after the restarts.  

I also deleted all the ingester pods simultaneously to simulate an outage. After this `ingester-0` failed to start:
```
level=info ts=2021-06-24T09:59:13.043667312Z caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"                                                                   
level=info ts=2021-06-24T09:59:13.044630819Z caller=lifecycler.go:447 msg="lifecycler loop() exited gracefully" ring=ingester                                                          
level=info ts=2021-06-24T09:59:13.044665757Z caller=lifecycler.go:746 msg="changing instance state from" old_state=ACTIVE new_state=LEAVING ring=ingester                              
level=error ts=2021-06-24T09:59:13.045127185Z caller=transfer.go:201 msg="transfer failed" err="cannot find ingester to transfer chunks to: no pending ingesters"
```

After clearing the `/ring` using the distributor endpoint `ingester-0` was able to start and the other pods in the ingester statefulset started as well. Afterward, I was able to query back data.

Going to go back to AWS and check if enabling `wal` in loki addresses this problem. I'm assuming we'll still lose data but hopefully, afterward, we can do rollouts of the ingesters without data loss.

**Comment by sreis** [comment]
> Going to go back to AWS and check if enabling wal in loki addresses this problem. I'm assuming we'll still lose data but hopefully, afterward, we can do rollouts of the ingesters without data loss.

Enabling the [ingester wal](https://grafana.com/docs/loki/latest/configuration/#ingester_config) seems to address this problem. According to the documentation, the next hurdle might be migrating to statefulset with wal [might come up with other challenges](https://grafana.com/docs/loki/latest/operations/storage/wal/#migrating-from-stateless-deployments). Going to open a PR to check that.

> Makes me think something is going on with the state that is cached by the ingesters when they restart.

The fact that tests worked on GCP threw me off. It looks like on AWS, during the rollout restart the ingesters default `terminationGracePeriod` of `30s` is not sufficient for the terminating ingester to handover to the other ones.
