### ISSUE TITLE
Roadmap link to community discussions is not working

### ISSUE THREAD

**Issue by timaa2k** [opstrace/opstrace#91]
**Describe the bug**

The link to community discussions at the end of the Roadmap is not working.
(I assume because I'm not a member of the organization so maybe that is by intention.)
https://opstrace.com/docs/references/roadmap

The link leads to
https://go.opstrace.com/community
which redirects to
https://github.com/opstrace/opstrace/discussions
where I get a 404 response.

**To Reproduce**

1. Go to the aforementioned Roadmap link
2. Scroll down to the end of the page
3. Click the link while not being signed into GitHub/the Opstrace org.

**Expected behavior**

I expected to be redirected to a page where I can see ongoing community discussions or a note that this is intended only for members of the organization.

**Comment by jgehrcke** [comment]
Heyyy Tim! Thank you for dropping by, nice to read from you. Hope things are good!

Indeed, the discussions feature is not yet enabled. As we speak, we're still waiting / hoping for GitHub to enable this on this repository :) The dead link you found is rooted in optimism!

From https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more:

> We are in beta with a few open source communities and will be making Discussions available to other projects soon

Also here we see that GH gets many requests: https://github.community/t/can-one-apply-for-github-discussions-beta/121120/519

We'll see! :shrug: 
Cheers :)

**Comment by jgehrcke** [comment]
@timaa2k https://github.com/opstrace/opstrace/discussions :-) :rocket:
