### ISSUE TITLE
ci instability: `expected workspace package to exist for` ... during `yarn add ...`

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#958]
```
error An unexpected error occurred: "expected workspace package to exist for \"table\"".
info If you think this is a bug, please open a bug report with the information provided in "/build/test/test-remote/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
make: *** [Makefile:763: preamble] Error 1
[2021-06-29T09:36:13Z] make: *** [ci-preamble] Error 2
```
https://buildkite.com/opstrace/prs/builds/4869#a0106b29-120b-4500-9fe0-cda868c1b747/3294-3334

**Comment by jgehrcke** [comment]
https://github.com/yarnpkg/yarn/issues/7807

**Comment by jgehrcke** [comment]
I think this is actually a permanent problem that 'only' shows itself when doing `yarn add ...` in the `test-remote` package. We're not doing this as of now in `main`. Closing for now.

**Comment by MoSattler** [comment]
@jgehrcke I actually just encountered this local, when trying to add a package. I tried googling it, and that led me here.
