### ISSUE TITLE
ci-instability: cannot stat 'browser-test-results': No such file or directory

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#979]
**Describe the bug**

```
Exit status of make test-browser: 2
[2021-07-02T01:22:53Z] + mkdir -p /build/bk-artifacts/browser-test-result
[2021-07-02T01:22:53Z] + mv browser-test-results /build/bk-artifacts/
[2021-07-02T01:22:53Z] mv: cannot stat 'browser-test-results': No such file or directory
[2021-07-02T01:22:53Z] + true
[2021-07-02T01:22:53Z] + echo '--- run looker tests'
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/2588#2cee2437-b364-4a39-9e31-131c695aac58/8665-8668

**Comment by jgehrcke** [comment]
is this a permanent one?

**Comment by sreis** [comment]
No, seems transient. It also doesn't look like it ran the browser tests at all.

**Comment by sreis** [comment]
I missed this in the [logs](https://buildkite.com/opstrace/scheduled-main-builds/builds/2588#2cee2437-b364-4a39-9e31-131c695aac58/8633-8659):

> [2021-07-02T01:22:52Z] Unable to connect to the server: error executing access token command "/usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=fork/exec /usr/lib/google-cloud-sdk/bin/gcloud: no such file or directory output= stderr=

Duplicate of #977
