### ISSUE TITLE
looker: follow wall time? maybe not

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#982]
For Looker, there seems to be desire to generate data synthetically using "wall time" as a time source. This what both Chris and Nick have expressed.

I think I understand where you're coming from. I think this is one of those typical proposals that seems like "yeah sure let's do this" at the surface; with an exciting twist however when you really start thinking this through!

We need to understand better why we think we need that. I believe that this probably comes from the desire to generate data that looks more like real-world data, right?

Okay, let's take a breath. Looker tries to be CPU-bound. What does that mean? It wants to get a lot out of the hardware that it is running on.

Being CPU-bound can be considered as "generate samples as fast as I can", i.e. without doing artificial waits.

Using "wall time" as a time source and "generate samples as fast as I can" in combination mean that the time difference between adjacent samples will become difficult to control.

However, it is precisely the time difference between two adjacent samples that must be controllable in order to make synthetically generated data look similar to  real-world data. And that's the twist :rainbow: 

In what I wrote so far it should be obvious that there may be conflicting goals and that this topic is non-trivial.

To make this point, let's look at what this means for metrics:

- When generating samples for a single time series based on wall time w/o artificial waits: adjacent samples will be ridiculously close to each other in time. The time difference is certain to be smaller than 1 milliscond. Two problems:
    - In Prometheus, metric time series samples have a time resolution of only 1 millisecond; the time resolution of the underlying data structures is only that.
    - Real-world metric time series exhibit a time difference between adjacent samples of  O(10 s) to (1 min). It should obvious that O(1 ms) is far from anything real-world.

Now, one could think of a way to be CPU-bound and at the same time make it so that adjacent samples are apart by many seconds: this can be achieved by generating samples for a large number of time series L (e.g., 10^6), and where a single HTTP request sent out contains precisely 1 sample for N time series; N as a subset of L with N being much smaller than L. This is not a sane option. Two specific disadvantages:

1. while the time difference between adjacent samples will be come large, it will also become really difficult to control. It may be 1 second, it may be 10 seconds, it may be 5 minutes -- really depending on L and N, required trial and error to achieve the desired outcome.
2. this limits the number of samples _per time series_ one can encode into a single push message (HTTP request) to 1, and therefore removes an important degree of freedom from the game.

What this means for logs: largely the same. It's a little different, because the time stamp resolution for log samples in Loki is 1 nanosecond. However, the same disadvantages count: the time difference between adjacent samples will become difficult to control.

I think Looker should continue to follow the principle of being largely CPU-bound for sample generation _unless_ specific input parameters tell it to _not_ be. "Use wall time as a time source" is _not_ that input parameter, because as argued above I believe we still want to be able to control the time difference between adjacent samples.

I think there are smarter ways of doing things. We need good goal statements, and I am happy to work on those. In the metrics mode I have actually started to build things in _one_ smarter way, towards more real-world load characteristics. I think of this as **synthetic time source loosely coupled to wall time**. I have explained this to some of you, but I want to explain how this works using maybe different words:

1) You set the desired time difference between adjacent samples (say, 30 seconds) -- as one of the _most important_ parameters to approximate a property of real-world workload.

2) You choose everything else that you can choose in Looker. Note that all these other things you define (say, the number of time series to generate) really determine how much CPU work it actually has to do.

If (1) and (2) result in Looker generating samples faster than wall time, it will automatically slow itself down (it will _not_ consume CPU for a while every now and then).

If (1) and (2) result in Looker generating samples slower than wall time then it will have largish CPU utilization all the time, and every now and then artificially leaps the metrics forward to not fall behind wall time too much.

The slow-down and the leap-forward follow specific rules involving time constants. These time constants can be tuned to make things appear less artificial, if that's a goal! :) :rainbow:

You ask yourself whether looker is in slow-down or leap-forward mode (in metrics mode)? This can be monitored in various ways; either through the metrics it exposes about itself, or just via having a look at `top`.

Here are exciting follow-up options for the future:

1) Implement the "synthetic time source loosely coupled to wall time" approach also for logs mode. That is rather easy to do.

2) Parameterize the "leap-forward" technique so that it more closely resembles real-world work loads.

3) Instead of picking a _fixed_ time difference between adjacent samples, one could pick randomly from a distribution -- this would be super powerful for approximating real-world data.

4) For logs, we may want to do something funny and artifically generate say web server access logs -- actually easy to do I think, involving some message pool and some statistical distributions.

1 + 2 + 3 mean that we could get a powerful combination: CPU-bound log generation that resembles real-world load in certain ways.

1 + 3 + 4 mean that we can get another super useful combination: generate 'some' log load that looks real-worldish (not CPU-bound, because not required).

**Comment by nickbp** [comment]
This sounds good to me, I'd been thinking of it as a scheduling problem, where at the moment there's sort of a fixed schedule and it's more subject to drift. The idea you have of adding delays/skips feels like it'd be a good way of keeping the pushes aligned

BTW it looks like the current looker code is accumulating the per-series fragments [into an array](https://github.com/opstrace/opstrace/blob/main/test/test-remote/looker/src/index.ts#L634) before sending them, do you know if it'd be possible to stream this, as in stream directly to an open socket? Mostly just thinking about memory usage with aggregating them in memory, but haven't actually benchmarked this to see if it's really an issue.

**Comment by jgehrcke** [comment]
> BTW it looks like the current looker code is accumulating the per-series fragments into an array before sending them .... Mostly just thinking about memory usage with aggregating them in memory

Great point. For the record: we talk about https://github.com/opstrace/opstrace/blob/482ea641bc6a3676f10778496de040f3786377dc/test/test-remote/looker/src/index.ts#L634 (non-moving target link)

The `streams` object [passed to this function](https://github.com/opstrace/opstrace/blob/482ea641bc6a3676f10778496de040f3786377dc/test/test-remote/looker/src/index.ts#L599) corresponds to a subset of all time series managed by Looker. Here is where these individual 'stream chunks' are built:

```
  const streamChunks = util.chunkify<DummyStream | DummyTimeseries>(
    streams,
    CFG.n_fragments_per_push_message
  );

  for (const sc of streamChunks) {
    // new concept: N streams per pushrequestproducernadPOSTer
    actors.push(pushrequestProducerAndPOSTer(sc, writeConcurSemaphore));
  }
```
(https://github.com/opstrace/opstrace/blob/482ea641bc6a3676f10778496de040f3786377dc/test/test-remote/looker/src/index.ts#L583)

So, the `fragments` array you were linking to is actually of length `--n-fragments-per-push-message F`. Of these functions, at most `--max-concurrent-writes W` run concurrently.

So, `N*W` of these arrays may be in memory at the same time. Depending on the choice of these parameters, this may theoretically be 'a lot', but in sane usage scenarios it should still be much much less than keeping a fragment for all time series managed by Looker in mem. Example for an extreme scenario I have created in the past:

- N time series: 1.000.000 
- `--n-concurrent-writes`: 20
- `--n-fragments-per-push-message`: 1000

What's more interesting is that after all a single snappy-compressed push message must not be larger than 1 MB (as of receiving end limits), and we can say that we hold `--n-concurrent-writes` times the _uncompressed_ version of that in memory at most.

Just talking about what's happening, no strong conclusions.
